-- ============================================================================
-- Persisch-Refresh-Seed v2 – 500 Wörter (Frequenzrang 1–500), Lektionen in 4 Teilen.
-- Quelle: Wiktionary „A Frequency Dictionary of Persian" (Miller/Aghajanian-Stewart,
--          Routledge 2009). Erstellt nach dem Review-Workflow der Arbeitsmappe:
--   • Funktionswörter mit Beispielsätzen/Hinweisen behalten,
--   • korrupte Quell-Schreibungen (لا↔ال, vertauschte Verb-Token) korrigiert,
--   • Eigennamen / religiös-politische / medienlastige Begriffe im Hinweis markiert.
-- Rang 121–500 sind redaktioneller ENTWURF – vor Veröffentlichung bitte durchsehen.
-- Voraussetzung: Migrationen 0001–0004. Im Supabase SQL Editor ausführen.
-- >>> App-Login-E-Mail (eine Stelle): jreitzenstein@gmail.com
-- ============================================================================

-- 1) Lektionen
insert into public.lessons (user_id, buch, lektion_nummer, titel, beschreibung, reihenfolge)
select (select id from auth.users where email='jreitzenstein@gmail.com'), v.buch, v.lektion_nummer, v.titel, v.beschreibung, v.reihenfolge
from (values
  (1, 101, 'Konnektoren', 'Teil 1 – Grammatik-Gerüst', 101),
  (1, 102, 'Präpositionen', 'Teil 1 – Grammatik-Gerüst', 102),
  (1, 103, 'Pronomen', 'Teil 1 – Grammatik-Gerüst', 103),
  (1, 104, 'Quantoren', 'Teil 1 – Grammatik-Gerüst', 104),
  (1, 105, 'Fragewörter', 'Teil 1 – Grammatik-Gerüst', 105),
  (1, 106, 'Verneinung', 'Teil 1 – Grammatik-Gerüst', 106),
  (2, 201, 'Kernverben 1', 'Teil 2 – Verben', 201),
  (2, 202, 'Kernverben 2', 'Teil 2 – Verben', 202),
  (2, 203, 'Modalverben', 'Teil 2 – Verben', 203),
  (2, 204, 'Funktionsverbgefüge', 'Teil 2 – Verben', 204),
  (3, 301, 'Abstrakta 1', 'Teil 3 – Wortschatz', 301),
  (3, 302, 'Abstrakta 2', 'Teil 3 – Wortschatz', 302),
  (3, 303, 'Abstrakta 3', 'Teil 3 – Wortschatz', 303),
  (3, 304, 'Abstrakta 4', 'Teil 3 – Wortschatz', 304),
  (3, 305, 'Abstrakta 5', 'Teil 3 – Wortschatz', 305),
  (3, 306, 'Abstrakta 6', 'Teil 3 – Wortschatz', 306),
  (3, 307, 'Abstrakta 7', 'Teil 3 – Wortschatz', 307),
  (3, 308, 'Gesellschaft 1', 'Teil 3 – Wortschatz', 308),
  (3, 309, 'Gesellschaft 2', 'Teil 3 – Wortschatz', 309),
  (3, 310, 'Gesellschaft 3', 'Teil 3 – Wortschatz', 310),
  (3, 311, 'Orte', 'Teil 3 – Wortschatz', 311),
  (3, 312, 'Adjektive 1', 'Teil 3 – Wortschatz', 312),
  (3, 313, 'Adjektive 2', 'Teil 3 – Wortschatz', 313),
  (3, 314, 'Adjektive 3', 'Teil 3 – Wortschatz', 314),
  (3, 315, 'Adverbien', 'Teil 3 – Wortschatz', 315),
  (4, 401, 'Zeit 1', 'Teil 4 – Zeit & Zahlen', 401),
  (4, 402, 'Zeit 2', 'Teil 4 – Zeit & Zahlen', 402),
  (4, 403, 'Zahlen', 'Teil 4 – Zeit & Zahlen', 403)
) as v(buch, lektion_nummer, titel, beschreibung, reihenfolge)
on conflict (user_id, lektion_nummer) do update
  set titel=excluded.titel, buch=excluded.buch, beschreibung=excluded.beschreibung, reihenfolge=excluded.reihenfolge;

-- 2) Vorherige Seed-Vokabeln dieses Nutzers entfernen (idempotent).
delete from public.vocab_items where user_id = (select id from auth.users where email='jreitzenstein@gmail.com') and lektion_nummer between 101 and 499;

-- 3) 500 Vokabeln
insert into public.vocab_items
  (user_id, hangul, romanisierung, deutsch, lektion_nummer, beispielsatz_ko, beispielsatz_de, hinweis, haeufigkeit)
select (select id from auth.users where email='jreitzenstein@gmail.com'), v.*
from (values
  -- L101
  ('و', 'vâv / va', 'und', 101, 'من و تو', 'ich und du', 'Extrem häufig; verbindet Wörter und Satzteile.', 5),
  ('که', 'ke', 'dass / der / die / welcher', 101, 'می‌دانم که او می‌آید.', 'Ich weiß, dass er/sie kommt.', 'Sehr häufiges Relativ- und Ergänzungswort; mit ganzen Sätzen lernen.', 5),
  ('تا', 'tâ', 'bis / damit / um zu', 101, 'تا فردا صبر کن.', 'Warte bis morgen.', 'Polyfunktional: Grenze, Zweck, bis dass.', 5),
  ('پس', 'pas', 'dann / also / nach', 101, 'پس شروع کنیم.', 'Dann fangen wir an.', 'Diskursmarker: also/dann; auch räumlich/zeitlich.', 5),
  ('دیگر', 'digar', 'anderer / sonst / nicht mehr', 101, 'یک بار دیگر', 'noch einmal', 'Polyfunktional; in Negationen: دیگر نه.', 5),
  ('اما', 'ammâ', 'aber', 101, 'می‌خواستم بیایم، اما نتوانستم.', 'Ich wollte kommen, aber ich konnte nicht.', 'Formeller als ولی, aber beide sehr wichtig.', 5),
  ('هم', 'ham', 'auch / ebenfalls / beide', 101, 'من هم می‌آیم.', 'Ich komme auch.', 'Extrem häufig; in Kombinationen: هم... هم.', 5),
  ('یا', 'yâ', 'oder', 101, 'چای یا قهوه؟', 'Tee oder Kaffee?', 'Alternative/Entscheidung.', 5),
  ('نیز', 'niz', 'auch / ebenfalls', 101, 'او نیز آمد.', 'Er/sie kam ebenfalls.', 'Schriftsprachlicher als هم.', 4),
  ('اگر', 'agar', 'wenn / falls', 101, 'اگر باران بیاید، نمی‌رویم.', 'Wenn es regnet, gehen wir nicht.', NULL, 5),
  ('یعنی', 'ya''ni', 'das heißt / nämlich', 101, 'دیر شد، یعنی باید عجله کنیم.', 'Es ist spät, das heißt, wir müssen uns beeilen.', NULL, 4),
  ('ولی', 'vali', 'aber', 101, 'من خسته‌ام، اما خوشحالم.', 'Ich bin müde, aber glücklich.', NULL, 5),
  ('چون', 'chun', 'weil / wie', 101, 'چون باران می‌بارید، نرفتم.', 'Weil es regnete, ging ich nicht.', NULL, 4),
  ('همچنین', 'hamchenin', 'außerdem / ebenso', 101, 'او آمد، همچنین برادرش.', 'Er kam, ebenso sein Bruder.', NULL, 4),
  ('بلکه', 'balke', 'sondern / vielmehr', 101, 'او نیامد، بلکه تلفن کرد.', 'Er kam nicht, sondern rief an.', NULL, 4),
  ('وقتی', 'vaghti', 'wenn / als', 101, 'وقتی آمد، خوابیده بودم.', 'Als er kam, schlief ich.', NULL, 4),
  ('جز', 'joz', 'außer / abgesehen von', 101, 'همه آمدند جز او.', 'Alle kamen außer ihm.', NULL, 4),
  -- L102
  ('از', 'az', 'von / aus / seit', 102, 'من از آلمانم.', 'Ich bin aus Deutschland.', 'Sehr produktive Präposition; auch in Vergleichen und Herkunft.', 5),
  ('به', 'be', 'zu / nach / an', 102, 'به تهران می‌روم.', 'Ich gehe nach Teheran.', 'Richtung, Dativ-ähnliche Funktionen und feste Wendungen.', 5),
  ('در', 'dar', 'in / in dem', 102, 'در خانه هستم.', 'Ich bin zu Hause.', 'Eine der wichtigsten Orts- und Bereichspräpositionen.', 5),
  ('با', 'bâ', 'mit', 102, 'با دوستم آمدم.', 'Ich kam mit meinem Freund.', 'Mittel, Begleitung; sehr häufig in Alltagsrede.', 5),
  ('برای', 'barâye', 'für', 102, 'این برای شماست.', 'Das ist für Sie/dich.', 'Zweck, Empfänger, Vorteil.', 5),
  ('بر', 'bar', 'auf / über / an', 102, 'بر اساس این گزارش', 'auf Grundlage dieses Berichts', 'Schriftsprachlich/gehoben; in vielen festen Verbindungen.', 4),
  ('میان', 'miyân', 'zwischen / Mitte', 102, 'میان دو کشور', 'zwischen zwei Ländern', 'Nahe bei بین; in Medien/Schrift häufig.', 4),
  ('بین', 'beyn', 'zwischen', 102, 'مغازه بین بانک و داروخانه است.', 'Der Laden ist zwischen Bank und Apotheke.', NULL, 5),
  ('بدون', 'bedun', 'ohne', 102, 'بدون تو نمی‌روم.', 'Ohne dich gehe ich nicht.', NULL, 4),
  ('رو', 'ru', 'auf / Gesicht / Oberfläche', 102, 'کتاب رو میز است.', 'Das Buch ist auf dem Tisch.', NULL, 4),
  ('جهت', 'jahat', 'Richtung / wegen', 102, 'به جهت سرما نرفتیم.', 'Wegen der Kälte gingen wir nicht.', NULL, 4),
  ('داخل', 'dâkhel', 'innen / innerhalb', 102, 'داخل خانه گرم است.', 'Im Haus ist es warm.', NULL, 4),
  ('درباره', 'darbâre', 'über / betreffend', 102, 'درباره‌ی این کتاب حرف زدیم.', 'Wir sprachen über dieses Buch.', NULL, 4),
  ('تحت', 'taht', 'unter', 102, 'تحت فشار هستم.', 'Ich stehe unter Druck.', NULL, 4),
  ('طی', 'tey', 'während / im Verlauf', 102, 'طی این هفته کار کردم.', 'Im Laufe dieser Woche habe ich gearbeitet.', NULL, 4),
  ('توسط', 'tavassot', 'durch / seitens', 102, 'این کتاب توسط او نوشته شد.', 'Dieses Buch wurde von ihm geschrieben.', NULL, 4),
  ('زیر', 'zir', 'unter / unterhalb', 102, 'کتاب زیر میز است.', 'Das Buch ist unter dem Tisch.', NULL, 4),
  ('مقابل', 'moghâbel', 'gegenüber', 102, 'مقابل خانه ایستادم.', 'Ich stand gegenüber dem Haus.', NULL, 4),
  ('کنار', 'kenâr', 'neben / Seite', 102, 'کنار من بنشین.', 'Setz dich neben mich.', NULL, 4),
  ('تو', 'to', 'in / hinein (ugs. „du")', 102, 'تو خانه هستم.', 'Ich bin zu Hause.', NULL, 4),
  -- L103
  ('این', 'in', 'dies / dieser / diese', 103, 'این کتاب خوب است.', 'Dieses Buch ist gut.', 'Deiktisches Pronomen; oft als Demonstrativbegleiter.', 5),
  ('خود', 'khod', 'selbst / sich', 103, 'خودم انجام دادم.', 'Ich habe es selbst gemacht.', 'Reflexiv/Intensivierung: خودم، خودت، خودش.', 5),
  ('آن', 'ân', 'das / jener / jene', 103, 'آن روز را یادم هست.', 'Ich erinnere mich an jenen Tag.', 'In geschriebener Sprache häufiger; gesprochen oft اون.', 5),
  ('ما', 'mâ', 'wir', 103, 'ما فارسی می‌خوانیم.', 'Wir lernen/lesen Persisch.', 'Personalpronomen.', 5),
  ('او', 'u', 'er / sie', 103, 'او اینجاست.', 'Er/sie ist hier.', 'Geschlechtsneutral im Persischen.', 5),
  ('همین', 'hamin', 'genau dieser / derselbe', 103, 'همین را می‌خواستم.', 'Genau das wollte ich.', NULL, 5),
  ('من', 'man', 'ich / mich', 103, 'من فردا می‌آیم.', 'Ich komme morgen.', NULL, 4),
  ('وی', 'vey', 'er / sie', 103, 'وی سال‌ها در اینجا کار کرده است.', 'Er hat jahrelang hier gearbeitet.', NULL, 4),
  ('شما', 'shomâ', 'ihr / Sie', 103, 'شما کجا هستید؟', 'Wo seid ihr / sind Sie?', NULL, 5),
  ('چنین', 'chenin', 'solch / derartig', 103, 'چنین چیزی ندیده بودم.', 'So etwas hatte ich nicht gesehen.', NULL, 4),
  ('همان', 'hamân', 'eben jener / derselbe', 103, 'همان فیلم را دوباره دیدیم.', 'Wir sahen denselben Film nochmal.', NULL, 4),
  ('سایر', 'sâyer', 'übrige / andere', 103, 'سایر مهمانان هم آمدند.', 'Die übrigen Gäste kamen auch.', NULL, 4),
  ('ایشان', 'ishân', 'sie / er/sie (höflich)', 103, 'ایشان استاد دانشگاه هستند.', 'Er/Sie ist Universitätsprofessor(in).', NULL, 4),
  -- L104
  ('هر', 'har', 'jede/r/s', 104, 'هر روز تمرین می‌کنم.', 'Ich übe jeden Tag.', 'Sehr häufig vor Nomen: هر روز، هر کس.', 5),
  ('بیش', 'bish', 'mehr', 104, 'بیش از ده نفر آمدند.', 'Mehr als zehn Personen kamen.', 'Oft in بیش از = mehr als; بیشتر gebräuchlicher im Alltag.', 4),
  ('همه', 'hame', 'alle / alles', 104, 'همه چیز خوب است.', 'Alles ist gut.', 'Allquantor.', 5),
  ('کم', 'kam', 'wenig / niedrig', 104, 'وقت کم است.', 'Die Zeit ist knapp.', 'Gegensatz zu زیاد/بیشتر.', 5),
  ('تمام', 'tamâm', 'ganz / vollständig / alle', 104, 'تمام روز کار کردم.', 'Ich habe den ganzen Tag gearbeitet.', NULL, 5),
  ('چند', 'chand', 'einige / mehrere / wie viele', 104, 'چند روز اینجا می‌مانی؟', 'Wie viele Tage bleibst du hier?', NULL, 5),
  ('برخی', 'barkhi', 'einige / manche', 104, 'برخی از مردم آمدند.', 'Einige der Leute kamen.', NULL, 5),
  -- L105
  ('چه', 'che', 'was / welcher / wie', 105, 'چه کتابی می‌خوانی؟', 'Welches Buch liest du?', NULL, 4),
  ('آیا', 'âyâ', 'ob (Fragepartikel)', 105, 'آیا تو می‌آیی؟', 'Kommst du?', NULL, 4),
  ('چرا', 'cherâ', 'warum', 105, 'چرا نیامدی؟', 'Warum bist du nicht gekommen?', NULL, 4),
  -- L106
  ('هیچ', 'hich', 'kein / nichts / überhaupt', 106, 'هیچ کس خانه نبود.', 'Niemand war zu Hause.', NULL, 4),
  ('نه', 'na', 'nein / nicht (auch: neun)', 106, 'نه، من نمی‌آیم.', 'Nein, ich komme nicht.', 'Homograph: نه = nein / neun', 4),
  -- L201
  ('بودن', 'budan', 'sein', 201, 'من خانه بودم.', 'Ich war zu Hause.', 'Präsensstamm: باش. Zentrales Verb; auch als Kopula/Perfekt-Hilfsverb wichtig.', 5),
  ('شدن', 'shodan', 'werden / geschehen', 201, 'هوا سرد شد.', 'Das Wetter wurde kalt.', 'Präsensstamm: شو. Sehr wichtiges Voll- und Hilfsverb; viele zusammengesetzte Verben.', 5),
  ('خواستن', 'khâstan', 'wollen / wünschen', 201, 'می‌خواهم فارسی بخوانم.', 'Ich möchte Persisch lernen/lesen.', 'Präsensstamm: خواه. Für Wünsche und Futurbildung wichtig: خواهم رفت.', 5),
  ('داشتن', 'dâshtan', 'haben', 201, 'من وقت دارم.', 'Ich habe Zeit.', 'Präsensstamm: دار. Besitz, Zustände und Progressive-Konstruktionen.', 5),
  ('کردن', 'kardan', 'machen / tun', 201, 'این کار را کردم.', 'Ich habe diese Arbeit gemacht.', 'Präsensstamm: کن. Basis vieler zusammengesetzter Verben: فکر کردن، شروع کردن.', 5),
  ('کرد', 'kard', 'tat / machte; Kurd', 201, 'او کار کرد.', 'Er/sie arbeitete.', 'Präsensstamm: کن. Als Verbform von کردن erkennen; homonym mit Kurd.', 4),
  ('رسیدن', 'residan', 'ankommen / erreichen', 201, 'قطار رسید.', 'Der Zug kam an.', 'Präsensstamm: رس. Auch: zu etwas gelangen, reif werden.', 5),
  ('گرفتن', 'gereftan', 'nehmen / bekommen / greifen', 201, 'تصمیم گرفتم بروم.', 'Ich entschied mich zu gehen.', 'Präsensstamm: گیر. Sehr produktiv: تصمیم گرفتن، تماس گرفتن.', 5),
  ('گفتن', 'goftan', 'sagen / sprechen', 201, 'او گفت که می‌آید.', 'Er/sie sagte, dass er/sie kommt.', 'Präsensstamm: گوی. Basisverb für Rede und Berichten.', 5),
  ('دادن', 'dâdan', 'geben', 201, 'کتاب را به من داد.', 'Er/sie gab mir das Buch.', 'Präsensstamm: ده. Basis vieler zusammengesetzter Verben: نشان دادن، انجام دادن.', 5),
  ('داشته', 'dâshte', 'gehabt / Besitz', 201, 'او این تجربه را داشته است.', 'Er/sie hat diese Erfahrung gehabt.', 'Präsensstamm: دار. Partizip/Perfektformen von داشتن.', 4),
  ('کند', 'konad / kond', 'macht / langsam', 201, 'او کار می‌کند.', 'Er/sie arbeitet.', 'Präsensstamm: کن. Form von کردن oder Adjektiv کند=langsam.', 4),
  ('داده', 'dâde', 'gegeben / Daten', 201, 'داده‌ها مهم هستند.', 'Die Daten sind wichtig.', 'Präsensstamm: ده. Partizip von دادن; auch داده = Daten.', 4),
  ('دانستن', 'dânestan', 'wissen / kennen', 201, 'می‌خواهم جواب را بدانم.', 'Ich möchte die Antwort wissen.', 'Präsensstamm: دان.', 4),
  ('آمدن', 'âmadan', 'kommen', 201, 'او دیر آمد.', 'Er ist spät gekommen.', 'Präsensstamm: آی.', 4),
  ('یافتن', 'yâftan', 'finden', 201, 'راه‌حل را یافتیم.', 'Wir haben die Lösung gefunden.', 'Präsensstamm: یاب.', 4),
  -- L202
  ('آوردن', 'âvardan', 'bringen', 202, 'برایم یک لیوان آب بیاور.', 'Bring mir ein Glas Wasser.', 'Präsensstamm: آور.', 4),
  ('وارد', 'vâred', 'eintretend / importiert / hinein', 202, 'او وارد اتاق شد.', 'Er trat ins Zimmer ein.', NULL, 4),
  ('رفتن', 'raftan', 'gehen', 202, 'فردا به مدرسه می‌روم.', 'Morgen gehe ich zur Schule.', 'Präsensstamm: روب.', 5),
  ('بردن', 'bordan', 'tragen / bringen / nehmen', 202, 'این نامه را به پست ببر.', 'Bring diesen Brief zur Post.', 'Präsensstamm: بر.', 5),
  ('رساندن', 'resândan', 'überbringen / zustellen', 202, 'او ما را به خانه رساند.', 'Er hat uns nach Hause gebracht.', 'Präsensstamm: رسان.', 4),
  ('گذاشتن', 'gozâshtan', 'legen / lassen', 202, 'کلید را روی میز گذاشتم.', 'Ich habe den Schlüssel auf den Tisch gelegt.', 'Präsensstamm: گذار.', 4),
  ('دیدن', 'didan', 'sehen', 202, 'دیروز او را دیدم.', 'Gestern habe ich ihn gesehen.', 'Präsensstamm: بین.', 4),
  ('پرداختن', 'pardâkhtan', 'zahlen / sich befassen', 202, 'صورت‌حساب را پرداختم.', 'Ich habe die Rechnung bezahlt.', 'Präsensstamm: پرداز.', 4),
  ('گذشتن', 'gozashtan', 'vorbeigehen / vergehen', 202, 'سال‌ها زود می‌گذرند.', 'Die Jahre vergehen schnell.', 'Präsensstamm: گذر.', 4),
  ('افزودن', 'afzudan', 'hinzufügen', 202, 'کمی نمک به غذا افزود.', 'Er fügte dem Essen etwas Salz hinzu.', 'Präsensstamm: افزا.', 4),
  ('یافته', 'yâfte', 'gefunden / vorgefunden', 202, 'او شغل تازه‌ای یافته است.', 'Er hat eine neue Stelle gefunden.', NULL, 4),
  ('خواندن', 'khândan', 'lesen / studieren', 202, 'هر شب کتاب می‌خوانم.', 'Jeden Abend lese ich ein Buch.', 'Präsensstamm: خوان.', 4),
  ('نمودن', 'nemudan', 'zeigen / tun', 202, 'او سعی نمود به ما کمک کند.', 'Er versuchte, uns zu helfen.', 'Präsensstamm: نمای.', 3),
  ('زدن', 'zadan', 'schlagen / klopfen', 202, 'در زد و داخل شد.', 'Er klopfte und kam herein.', 'Präsensstamm: زن.', 3),
  ('نوشتن', 'neveshtan', 'schreiben', 202, 'نامه‌ای به دوستم نوشتم.', 'Ich habe meinem Freund einen Brief geschrieben.', 'Präsensstamm: نویس.', 3),
  ('ساختن', 'sâkhtan', 'bauen / herstellen', 202, 'آن‌ها خانه‌ای نو ساختند.', 'Sie haben ein neues Haus gebaut.', 'Präsensstamm: ساز.', 3),
  -- L203
  ('بایستن', 'bâyestan', 'müssen / sollen', 203, 'باید بروم.', 'Ich muss gehen.', 'Präsensstamm: بای. In moderner Umgangssprache oft باید statt Infinitiv.', 4),
  ('توانستن', 'tavânestan', 'können / fähig sein', 203, 'می‌توانم کمک کنم.', 'Ich kann helfen.', 'Präsensstamm: توان. Modalverb; gesprochen oft تونستن.', 5),
  ('شایستن', 'shâyastan', 'möglich sein / sich geziemen', 203, 'شایستن یعنی سزاوار بودن.', '„Schâyestan“ bedeutet „würdig sein“.', 'Präsensstamm: شای.', 3),
  -- L204
  ('نشان دادن', 'neshân dâdan', 'zeigen', 204, 'راه را به من نشان داد.', 'Er zeigte mir den Weg.', 'Präsensstamm: ده.', 4),
  ('قرار گرفتن', 'gharâr gereftan', 'sich befinden / liegen', 204, 'خانه در شمال شهر قرار گرفته است.', 'Das Haus liegt im Norden der Stadt.', 'Präsensstamm: گیر.', 5),
  ('وجود داشتن', 'vojud dâshtan', 'existieren', 204, 'چنین چیزی وجود دارد.', 'So etwas existiert.', 'Präsensstamm: دار.', 4),
  ('انجام دادن', 'anjâm dâdan', 'durchführen / erledigen', 204, 'کار را انجام دادم.', 'Ich habe die Arbeit erledigt.', 'Präsensstamm: ده.', 4),
  ('دست دادن', 'dast dâdan', 'die Hand geben / verlieren', 204, 'با هم دست دادند.', 'Sie gaben sich die Hand.', 'Präsensstamm: ده.', 4),
  ('پیدا کردن', 'peydâ kardan', 'finden', 204, 'کلید را پیدا کردم.', 'Ich habe den Schlüssel gefunden.', 'Präsensstamm: کن.', 4),
  ('قرار دادن', 'gharâr dâdan', 'platzieren / festlegen', 204, 'گلدان را کنار پنجره قرار داد.', 'Sie stellte die Vase ans Fenster.', 'Präsensstamm: ده.', 3),
  ('قرار داشتن', 'gharâr dâshtan', 'sich befinden / liegen', 204, 'خانه در مرکز شهر قرار دارد.', 'Das Haus befindet sich im Stadtzentrum.', 'Präsensstamm: دار.', 3),
  ('استفاده کردن', 'estefâde kardan', 'benutzen / verwenden', 204, 'از این روش استفاده می‌کنیم.', 'Wir benutzen diese Methode.', 'Präsensstamm: کن.', 3),
  ('خارج شدن', 'khârej shodan', 'hinausgehen / herauskommen', 204, 'از اتاق خارج شد.', 'Er ging aus dem Zimmer hinaus.', 'Präsensstamm: شو.', 3),
  ('ادامه دادن', 'edâme dâdan', 'fortsetzen', 204, 'به کارش ادامه داد.', 'Er setzte seine Arbeit fort.', 'Präsensstamm: ده.', 3),
  ('قرار بودن', 'gharâr budan', 'vorgesehen sein / sollen', 204, 'قرار بود ساعت پنج بیاید.', 'Er sollte um fünf kommen.', 'Präsensstamm: باش.', 3),
  ('انجام شدن', 'anjâm shodan', 'erledigt werden / geschehen', 204, 'کار به‌موقع انجام شد.', 'Die Arbeit wurde rechtzeitig erledigt.', 'Präsensstamm: شو.', 3),
  ('انتخاب کردن', 'entekhâb kardan', 'wählen / auswählen', 204, 'او را به عنوان رئیس انتخاب کردند.', 'Sie wählten ihn zum Vorsitzenden.', 'Präsensstamm: کن.', 3),
  -- L301
  ('کار', 'kâr', 'Arbeit / Sache', 301, 'کار دارم.', 'Ich habe zu tun.', 'Sehr breit: Arbeit, Angelegenheit, Funktion.', 5),
  ('صورت', 'surat', 'Gesicht / Form / Weise', 301, 'به صورت رسمی', 'auf offizielle Weise', 'In festen Wendungen: به صورتِ = in Form von/als.', 4),
  ('نظر', 'nazar', 'Meinung / Sicht', 301, 'نظر شما چیست؟', 'Was ist Ihre/deine Meinung?', 'Sehr wichtig in نظر داشتن/به نظر.', 5),
  ('عنوان', 'onvân', 'Titel / Überschrift / Bezeichnung', 301, 'عنوان این کتاب چیست؟', 'Wie lautet der Titel dieses Buches?', NULL, 5),
  ('مورد', 'mowred', 'Fall / Gegenstand / betreffend', 301, 'در این مورد بعداً حرف می‌زنیم.', 'Über diesen Punkt sprechen wir später.', NULL, 5),
  ('دست', 'dast', 'Hand', 301, 'دستم درد می‌کند.', 'Meine Hand tut weh.', NULL, 5),
  ('قرار', 'gharâr', 'Vereinbarung / Lage / Plan', 301, 'فردا با دکتر قرار دارم.', 'Morgen habe ich einen Termin beim Arzt.', NULL, 5),
  ('برنامه', 'barnâme', 'Programm / Plan', 301, 'برنامه‌ی امروز چیست؟', 'Was ist das Programm für heute?', NULL, 5),
  ('بخش', 'bakhsh', 'Teil / Abschnitt / Bereich', 301, 'این بخش از کتاب سخت است.', 'Dieser Teil des Buches ist schwer.', NULL, 5),
  ('وجود', 'vojood', 'Existenz / Vorhandensein', 301, 'مشکلی وجود ندارد.', 'Es gibt kein Problem.', NULL, 5),
  ('مسئله', 'mas''ale', 'Problem / Frage / Angelegenheit', 301, 'این مسئله را حل کردیم.', 'Wir haben dieses Problem gelöst.', NULL, 5),
  ('توجه', 'tavajjoh', 'Aufmerksamkeit', 301, 'لطفاً به من توجه کن.', 'Bitte schenk mir Aufmerksamkeit.', NULL, 5),
  ('امر', 'amr', 'Angelegenheit / Sache / Befehl', 301, 'این امر مهمی است.', 'Das ist eine wichtige Angelegenheit.', NULL, 5),
  ('طور', 'towr', 'Art / Weise', 301, 'این طور بهتر است.', 'So ist es besser.', NULL, 5),
  ('مشکل', 'moshkel', 'Problem / schwierig', 301, 'مشکلی پیش آمد.', 'Ein Problem ist aufgetreten.', NULL, 4),
  ('نتیجه', 'natije', 'Ergebnis / Folge', 301, 'نتیجه‌ی امتحان خوب بود.', 'Das Ergebnis der Prüfung war gut.', NULL, 4),
  ('رابطه', 'râbete', 'Beziehung / Verbindung', 301, 'رابطه‌ی خوبی با هم داریم.', 'Wir haben eine gute Beziehung zueinander.', NULL, 4),
  ('شرط', 'shart', 'Bedingung', 301, 'به یک شرط می‌آیم.', 'Ich komme unter einer Bedingung.', NULL, 4),
  ('اساس', 'asâs', 'Grundlage / Basis', 301, 'این کار اساس درستی دارد.', 'Diese Sache hat eine solide Grundlage.', NULL, 4),
  ('زمینه', 'zamine', 'Hintergrund / Feld / Grundlage', 301, 'در این زمینه تجربه دارم.', 'Auf diesem Gebiet habe ich Erfahrung.', NULL, 4),
  ('دلیل', 'dalil', 'Grund', 301, 'دلیل تأخیرت چیست؟', 'Was ist der Grund für deine Verspätung?', NULL, 5),
  ('نقش', 'naghsh', 'Rolle', 301, 'او نقش مهمی دارد.', 'Er spielt eine wichtige Rolle.', NULL, 5),
  ('نام', 'nâm', 'Name', 301, 'نام تو چیست؟', 'Wie ist dein Name?', NULL, 5),
  ('استفاده', 'estefâde', 'Verwendung / Gebrauch', 301, 'استفاده از تلفن اینجا ممنوع است.', 'Der Gebrauch des Telefons ist hier verboten.', NULL, 5),
  ('حرکت', 'harekat', 'Bewegung', 301, 'قطار در حال حرکت است.', 'Der Zug ist in Bewegung.', NULL, 5),
  ('طرح', 'tarh', 'Entwurf / Plan', 301, 'طرح تازه‌ای داریم.', 'Wir haben einen neuen Plan.', NULL, 5),
  ('حدود', 'hodud', 'Grenzen / etwa', 301, 'حدود صد نفر آمدند.', 'Etwa hundert Leute kamen.', NULL, 5),
  -- L302
  ('ایجاد', 'ijâd', 'Schaffung / Erzeugung', 302, 'این کار شغل ایجاد می‌کند.', 'Diese Maßnahme schafft Arbeitsplätze.', NULL, 5),
  ('حضور', 'hozur', 'Anwesenheit / Präsenz', 302, 'حضور شما باعث افتخار است.', 'Ihre Anwesenheit ist eine Ehre.', NULL, 4),
  ('نیرو', 'niru', 'Kraft / Truppe', 302, 'دیگر نیرو ندارم.', 'Ich habe keine Kraft mehr.', NULL, 4),
  ('فعالیت', 'fa''âliyat', 'Aktivität / Tätigkeit', 302, 'فعالیت ورزشی خوب است.', 'Sportliche Aktivität ist gut.', NULL, 4),
  ('تن', 'tan', 'Körper / Tonne', 302, 'تنش از سرما می‌لرزید.', 'Sein Körper zitterte vor Kälte.', NULL, 4),
  ('اشاره', 'eshâre', 'Hinweis / Andeutung', 302, 'با دست به در اشاره کرد.', 'Er deutete mit der Hand auf die Tür.', NULL, 4),
  ('درصد', 'darsad', 'Prozent', 302, 'ده درصد تخفیف گرفتم.', 'Ich habe zehn Prozent Rabatt bekommen.', NULL, 4),
  ('قانون', 'ghânun', 'Gesetz', 302, 'باید قانون را رعایت کنیم.', 'Wir müssen das Gesetz beachten.', NULL, 4),
  ('هدف', 'hadaf', 'Ziel', 302, 'هدف من یادگیری فارسی است.', 'Mein Ziel ist es, Persisch zu lernen.', NULL, 4),
  ('بزرگی', 'bozorgi', 'Größe / Ausmaß', 302, 'بزرگی این شهر مرا شگفت‌زده کرد.', 'Die Größe dieser Stadt erstaunte mich.', NULL, 4),
  ('حق', 'hagh', 'Recht', 302, 'تو حق داری.', 'Du hast recht.', NULL, 4),
  ('اثر', 'asar', 'Spur / Wirkung / Werk', 302, 'این دارو اثر خوبی دارد.', 'Dieses Medikament hat eine gute Wirkung.', NULL, 4),
  ('بحث', 'bahs', 'Diskussion / Debatte', 302, 'بحث جالبی بود.', 'Es war eine interessante Diskussion.', NULL, 4),
  ('ارزش', 'arzesh', 'Wert', 302, 'این انگشتر ارزش زیادی دارد.', 'Dieser Ring hat einen hohen Wert.', NULL, 4),
  ('موضوع', 'movzu''', 'Thema / Gegenstand', 302, 'موضوع جلسه چیست؟', 'Was ist das Thema der Sitzung?', NULL, 4),
  ('طرف', 'taraf', 'Seite', 302, 'از این طرف بیا.', 'Komm von dieser Seite.', NULL, 4),
  ('آب', 'âb', 'Wasser', 302, 'یک لیوان آب می‌خواهم.', 'Ich möchte ein Glas Wasser.', NULL, 4),
  ('نوع', 'nov''', 'Art / Typ', 302, 'چه نوع موسیقی دوست داری؟', 'Welche Art Musik magst du?', NULL, 4),
  ('اجرا', 'ejrâ', 'Ausführung / Umsetzung', 302, 'اجرای کنسرت عالی بود.', 'Die Aufführung des Konzerts war großartig.', NULL, 4),
  ('عمل', 'amal', 'Handlung / Tat', 302, 'به عمل خود فکر کن.', 'Denk über deine Tat nach.', NULL, 4),
  ('زندگی', 'zendegi', 'Leben', 302, 'زندگی در شهر گران است.', 'Das Leben in der Stadt ist teuer.', NULL, 4),
  ('نظام', 'nezâm', 'System / Ordnung', 302, 'نظام آموزشی تغییر کرد.', 'Das Bildungssystem hat sich geändert.', NULL, 4),
  ('شکل', 'shekl', 'Form / Gestalt', 302, 'این میز شکل گردی دارد.', 'Dieser Tisch hat eine runde Form.', NULL, 4),
  ('نسبت', 'nesbat', 'Verhältnis / Bezug', 302, 'نسبت به دیروز بهتر است.', 'Im Vergleich zu gestern ist es besser.', NULL, 4),
  ('دنیا', 'donyâ', 'Welt', 302, 'دنیا خیلی بزرگ است.', 'Die Welt ist sehr groß.', NULL, 4),
  ('کتاب', 'ketâb', 'Buch', 302, 'این کتاب را خواندم.', 'Dieses Buch habe ich gelesen.', NULL, 4),
  -- L303
  ('توسعه', 'tovse''e', 'Entwicklung / Ausbau', 303, 'توسعه‌ی شهر ادامه دارد.', 'Die Entwicklung der Stadt geht weiter.', NULL, 4),
  ('انجام', 'anjâm', 'Durchführung / Ausführung', 303, 'انجام این کار وقت می‌برد.', 'Die Durchführung dieser Arbeit braucht Zeit.', NULL, 4),
  ('اعلام', 'e''lâm', 'Bekanntgabe / Ankündigung', 303, 'نتایج فردا اعلام می‌شود.', 'Die Ergebnisse werden morgen bekannt gegeben.', NULL, 4),
  ('اطلاع', 'ettelâ''', 'Information / Kenntnis', 303, 'اطلاع تازه‌ای ندارم.', 'Ich habe keine neue Information.', NULL, 4),
  ('گفته', 'gofte', 'Aussage / gesagt', 303, 'گفته‌ی او درست بود.', 'Seine Aussage war richtig.', NULL, 4),
  ('گزارش', 'gozâresh', 'Bericht', 303, 'گزارش را به رئیس دادم.', 'Ich habe den Bericht dem Chef gegeben.', NULL, 4),
  ('سر', 'sar', 'Kopf / Spitze', 303, 'سرم درد می‌کند.', 'Mein Kopf tut weh.', NULL, 4),
  ('تغییر', 'taghyir', 'Veränderung', 303, 'تغییر بزرگی لازم است.', 'Eine große Veränderung ist nötig.', NULL, 4),
  ('تعداد', 'te''dâd', 'Anzahl / Anzahl', 303, 'تعداد دانش‌آموزان زیاد است.', 'Die Anzahl der Schüler ist hoch.', NULL, 4),
  ('بررسی', 'barresi', 'Untersuchung / Prüfung', 303, 'مدارک را بررسی کردیم.', 'Wir haben die Unterlagen geprüft.', NULL, 4),
  ('اقدام', 'eghdâm', 'Maßnahme / Schritt', 303, 'اقدام لازم انجام شد.', 'Die nötige Maßnahme wurde ergriffen.', NULL, 4),
  ('افزایش', 'afzâyesh', 'Zunahme / Erhöhung', 303, 'قیمت‌ها افزایش یافت.', 'Die Preise sind gestiegen.', NULL, 4),
  ('گونه', 'gune', 'Art / Sorte', 303, 'این گونه گل کمیاب است.', 'Diese Blumenart ist selten.', NULL, 4),
  ('خدمت', 'khedmat', 'Dienst', 303, 'او سال‌ها خدمت کرد.', 'Er hat jahrelang Dienst geleistet.', NULL, 4),
  ('خبر', 'khabar', 'Nachricht', 303, 'خبر خوبی دارم.', 'Ich habe eine gute Nachricht.', NULL, 4),
  ('منبع', 'manba''', 'Quelle', 303, 'این آب از یک منبع طبیعی است.', 'Dieses Wasser stammt aus einer natürlichen Quelle.', NULL, 4),
  ('خط', 'khatt', 'Linie / Schrift', 303, 'یک خط راست بکش.', 'Zieh eine gerade Linie.', NULL, 4),
  ('قدرت', 'ghodrat', 'Macht / Stärke', 303, 'این کشور قدرت زیادی دارد.', 'Dieses Land hat große Macht.', NULL, 4),
  ('نیاز', 'niyâz', 'Bedarf / Bedürfnis', 303, 'به کمک تو نیاز دارم.', 'Ich brauche deine Hilfe.', NULL, 4),
  ('میزان', 'mizân', 'Maß / Ausmaß', 303, 'میزان بارش کم بود.', 'Die Niederschlagsmenge war gering.', NULL, 4),
  ('اختیار', 'ekhtiyâr', 'Befugnis / Verfügung', 303, 'این تصمیم در اختیار توست.', 'Diese Entscheidung liegt bei dir.', NULL, 4),
  ('ارائه', 'erâ''e', 'Darbietung / Vorlage', 303, 'ارائه‌ی او عالی بود.', 'Seine Präsentation war ausgezeichnet.', NULL, 4),
  ('باعث', 'bâ''es', 'Ursache / Anlass', 303, 'گرما باعث خستگی می‌شود.', 'Hitze verursacht Müdigkeit.', NULL, 4),
  ('رشد', 'roshd', 'Wachstum', 303, 'رشد اقتصادی کند است.', 'Das Wirtschaftswachstum ist langsam.', NULL, 4),
  ('دنبال', 'dombâl', 'Verfolgung / hinter', 303, 'دنبال کلیدم می‌گردم.', 'Ich suche nach meinem Schlüssel.', NULL, 4),
  ('انتخاب', 'entekhâb', 'Auswahl / Wahl', 303, 'انتخاب با توست.', 'Die Wahl liegt bei dir.', NULL, 4),
  -- L304
  ('گفت‌وگو', 'goftogu', 'Gespräch', 304, 'گفت‌وگوی خوبی داشتیم.', 'Wir hatten ein gutes Gespräch.', NULL, 4),
  ('خاطر', 'khâter', 'Gedanke / um … willen', 304, 'به خاطر تو ماندم.', 'Deinetwegen bin ich geblieben.', NULL, 4),
  ('سمت', 'samt', 'Seite / Position', 304, 'به سمت چپ برو.', 'Geh nach links.', NULL, 4),
  ('عامل', 'âmel', 'Faktor / Akteur', 304, 'خواب کم عامل خستگی است.', 'Wenig Schlaf ist ein Faktor für Müdigkeit.', NULL, 4),
  ('تأثیر', 'ta''sir', 'Einfluss / Wirkung', 304, 'موسیقی تأثیر زیادی دارد.', 'Musik hat großen Einfluss.', NULL, 4),
  ('ساخت', 'sâkht', 'Bau / Herstellung', 304, 'ساخت این پل دو سال طول کشید.', 'Der Bau dieser Brücke dauerte zwei Jahre.', NULL, 4),
  ('طریق', 'tarigh', 'Weg / Methode', 304, 'از طریق ایمیل خبر بده.', 'Gib per E-Mail Bescheid.', NULL, 4),
  ('کاهش', 'kâhesh', 'Verringerung', 304, 'کاهش قیمت‌ها خوب است.', 'Die Senkung der Preise ist gut.', NULL, 4),
  ('تشکیل', 'tashkil', 'Bildung / Gründung', 304, 'جلسه تشکیل شد.', 'Die Sitzung kam zustande.', NULL, 4),
  ('غیر', 'gheyr', 'Nicht- / andere', 304, 'غیر از این راهی نیست.', 'Außer diesem gibt es keinen Weg.', NULL, 4),
  ('نقطه', 'noghte', 'Punkt', 304, 'این نقطه را روی نقشه پیدا کن.', 'Finde diesen Punkt auf der Karte.', NULL, 4),
  ('بازی', 'bâzi', 'Spiel', 304, 'بازی فوتبال شروع شد.', 'Das Fußballspiel hat begonnen.', NULL, 4),
  ('تولید', 'tovlid', 'Produktion', 304, 'تولید این کارخانه زیاد است.', 'Die Produktion dieser Fabrik ist hoch.', NULL, 4),
  ('دیده', 'dide', 'Auge / gesehen', 304, 'او را قبلاً ندیده بودم.', 'Ich hatte ihn vorher nicht gesehen.', NULL, 4),
  ('اصل', 'asl', 'Prinzip / Ursprung', 304, 'اصل کار صداقت است.', 'Das Grundprinzip ist Ehrlichkeit.', NULL, 4),
  ('کمک', 'komak', 'Hilfe', 304, 'به کمکت احتیاج دارم.', 'Ich brauche deine Hilfe.', NULL, 4),
  ('اهمیت', 'âhammiyyat', 'Bedeutung / Wichtigkeit', 304, 'این موضوع اهمیت دارد.', 'Dieses Thema ist wichtig.', NULL, 4),
  ('اندیشه', 'andishe', 'Gedanke / Idee', 304, 'اندیشه‌ی خوبی است.', 'Das ist eine gute Idee.', NULL, 4),
  ('دفاع', 'defâ''', 'Verteidigung', 304, NULL, NULL, NULL, 3),
  ('نامه', 'nâme', 'Brief', 304, NULL, NULL, NULL, 3),
  ('دیدار', 'didâr', 'Treffen / Besuch', 304, NULL, NULL, NULL, 3),
  ('فرصت', 'forsat', 'Gelegenheit / Chance', 304, NULL, NULL, NULL, 3),
  ('تأکید', 'ta''kid', 'Betonung / Nachdruck', 304, NULL, NULL, NULL, 3),
  ('ترتیب', 'tartib', 'Reihenfolge / Ordnung', 304, NULL, NULL, NULL, 3),
  ('علت', 'ellat', 'Grund / Ursache', 304, NULL, NULL, NULL, 3),
  ('آزادی', 'âzâdi', 'Freiheit', 304, NULL, NULL, NULL, 3),
  -- L305
  ('وضعیت', 'vaz''iyyat', 'Situation / Lage', 305, NULL, NULL, NULL, 3),
  ('جریان', 'jarayân', 'Strömung / Vorgang', 305, NULL, NULL, NULL, 3),
  ('تلاش', 'talâsh', 'Anstrengung / Bemühung', 305, NULL, NULL, NULL, 3),
  ('حمایت', 'hemâyat', 'Unterstützung / Schutz', 305, NULL, NULL, NULL, 3),
  ('چیز', 'chiz', 'Ding / Sache', 305, NULL, NULL, NULL, 3),
  ('ادامه', 'edâme', 'Fortsetzung', 305, NULL, NULL, NULL, 3),
  ('دلار', 'dolâr', 'Dollar', 305, NULL, NULL, NULL, 3),
  ('سطح', 'sath', 'Ebene / Niveau', 305, NULL, NULL, NULL, 3),
  ('تصویر', 'tasvir', 'Bild / Abbildung', 305, NULL, NULL, NULL, 3),
  ('سفر', 'safar', 'Reise', 305, NULL, NULL, NULL, 3),
  ('جمع', 'jam''', 'Summe / Mehrzahl', 305, NULL, NULL, NULL, 3),
  ('پیشنهاد', 'pishnehâd', 'Vorschlag', 305, NULL, NULL, NULL, 3),
  ('ماده', 'mâde', 'Material / Substanz / weiblich', 305, NULL, NULL, NULL, 3),
  ('معنا', 'ma''nâ', 'Bedeutung / Sinn', 305, NULL, NULL, NULL, 3),
  ('رأی', 'raɁy', 'Stimme / Votum', 305, NULL, NULL, NULL, 3),
  ('حقیقت', 'haghighat', 'Wahrheit / Wirklichkeit', 305, NULL, NULL, NULL, 3),
  ('تأمین', 'ta''min', 'Sicherung / Bereitstellung', 305, NULL, NULL, NULL, 3),
  ('امکان', 'emkân', 'Möglichkeit', 305, NULL, NULL, NULL, 3),
  ('علم', 'elm', 'Wissenschaft', 305, NULL, NULL, NULL, 3),
  ('انتظار', 'entezâr', 'Erwartung / Warten', 305, NULL, NULL, NULL, 3),
  ('کل', 'kol', 'Ganzes / gesamt', 305, NULL, NULL, NULL, 3),
  ('شدت', 'sheddat', 'Intensität / Heftigkeit', 305, NULL, NULL, NULL, 3),
  ('حقوق', 'hoghugh', 'Rechte / Gehalt', 305, NULL, NULL, NULL, 3),
  ('گل', 'gol', 'Blume / Tor (Sport)', 305, NULL, NULL, NULL, 3),
  ('رشته', 'reshte', 'Fach / Disziplin', 305, NULL, NULL, NULL, 3),
  ('جلسه', 'jalase', 'Sitzung / Treffen', 305, NULL, NULL, NULL, 3),
  -- L306
  ('سؤال', 'so''âl', 'Frage', 306, NULL, NULL, NULL, 3),
  ('فضا', 'fazâ', 'Raum / Atmosphäre', 306, NULL, NULL, NULL, 3),
  ('فیلم', 'film', 'Film', 306, NULL, NULL, NULL, 3),
  ('منظور', 'manzur', 'Absicht / Zweck', 306, NULL, NULL, NULL, 3),
  ('زبان', 'zabân', 'Sprache / Zunge', 306, NULL, NULL, NULL, 3),
  ('مسابقه', 'mosâbeghe', 'Wettbewerb / Wettkampf', 306, NULL, NULL, NULL, 3),
  ('حوزه', 'hovze', 'Bereich / Bezirk', 306, NULL, NULL, NULL, 3),
  ('بیان', 'bayân', 'Ausdruck / Äußerung', 306, NULL, NULL, NULL, 3),
  ('واحد', 'vâhed', 'Einheit', 306, NULL, NULL, NULL, 3),
  ('مرگ', 'marg', 'Tod', 306, NULL, NULL, NULL, 3),
  ('سخن', 'sokhan', 'Rede / Wort', 306, NULL, NULL, NULL, 3),
  ('ارتباط', 'ertebât', 'Verbindung / Kontakt', 306, NULL, NULL, NULL, 3),
  ('حد', 'hadd', 'Grenze / Maß', 306, NULL, NULL, NULL, 3),
  ('امید', 'omid', 'Hoffnung', 306, NULL, NULL, NULL, 3),
  ('روش', 'ravesh', 'Methode / Vorgehen', 306, NULL, NULL, NULL, 3),
  ('امنیت', 'amniyat', 'Sicherheit', 306, NULL, NULL, NULL, 3),
  ('نفت', 'naft', 'Erdöl', 306, NULL, NULL, NULL, 3),
  ('چاپ', 'châp', 'Druck (Print) / Auflage', 306, NULL, NULL, NULL, 3),
  ('شبکه', 'shabake', 'Netz / Netzwerk', 306, NULL, NULL, NULL, 3),
  ('مانع', 'mâne''', 'Hindernis', 306, NULL, NULL, NULL, 3),
  ('نشان', 'neshân', 'Zeichen / Abzeichen', 306, NULL, NULL, NULL, 3),
  ('روند', 'ravand', 'Prozess / Verlauf', 306, NULL, NULL, NULL, 3),
  ('پول', 'pul', 'Geld', 306, NULL, NULL, NULL, 3),
  ('پاسخ', 'pâsokh', 'Antwort', 306, NULL, NULL, NULL, 3),
  ('واقعیت', 'vâghe''iyyat', 'Wirklichkeit / Realität', 306, NULL, NULL, NULL, 3),
  ('فشار', 'feshâr', 'Druck', 306, NULL, NULL, NULL, 3),
  -- L307
  ('دستور', 'dastur', 'Befehl / Anweisung', 307, NULL, NULL, NULL, 3),
  ('اصلاح', 'eslâh', 'Korrektur / Reform', 307, NULL, NULL, NULL, 3),
  ('سعی', 'sa''y', 'Versuch / Mühe', 307, NULL, NULL, NULL, 3),
  ('پرداخت', 'pardâkht', 'Zahlung / bezahlt', 307, NULL, NULL, NULL, 3),
  ('طول', 'tul', 'Länge', 307, NULL, NULL, NULL, 3),
  ('حفظ', 'hefz', 'Bewahrung / Erhalt', 307, NULL, NULL, NULL, 3),
  ('حادثه', 'hâdese', 'Vorfall / Unfall', 307, NULL, NULL, NULL, 3),
  ('عرصه', 'arse', 'Bereich / Arena', 307, NULL, NULL, NULL, 3),
  ('مقاله', 'maghâle', 'Artikel / Aufsatz', 307, NULL, NULL, NULL, 3),
  ('وضع', 'vaz''', 'Lage / Zustand', 307, NULL, NULL, NULL, 3),
  ('دستگاه', 'dastgâh', 'Gerät / Apparat', 307, NULL, NULL, NULL, 3),
  ('سیستم', 'sistem', 'System', 307, NULL, NULL, NULL, 3),
  ('خواست', 'khâst', 'Wunsch / wollte', 307, NULL, NULL, NULL, 3),
  ('هزینه', 'hazine', 'Kosten', 307, NULL, NULL, NULL, 3),
  ('هوا', 'havâ', 'Luft / Wetter', 307, NULL, NULL, NULL, 3),
  ('فکر', 'fekr', 'Gedanke / Denken', 307, NULL, NULL, NULL, 3),
  ('انتقال', 'enteghâl', 'Übertragung / Transfer', 307, NULL, NULL, NULL, 3),
  ('انگلیسی', 'engelisi', 'Englisch / englisch', 307, NULL, NULL, 'Sprach-/Ländername', 3),
  ('تحقیق', 'tahghigh', 'Forschung / Recherche', 307, NULL, NULL, NULL, 3),
  ('پی', 'pey', 'Fundament / Folge', 307, NULL, NULL, NULL, 3),
  ('موجب', 'mujeb', 'Ursache / Grund', 307, NULL, NULL, NULL, 3),
  ('خطر', 'khatar', 'Gefahr / Risiko', 307, NULL, NULL, NULL, 3),
  ('نقل', 'naghl', 'Übertragung / Zitat', 307, NULL, NULL, NULL, 3),
  ('فوتبال', 'futbâl', 'Fußball', 307, NULL, NULL, NULL, 3),
  ('آموزش', 'âmuzesh', 'Ausbildung / Unterricht', 307, NULL, NULL, NULL, 3),
  ('کنترل', 'kontrol', 'Kontrolle / Steuerung', 307, NULL, NULL, NULL, 3),
  -- L308
  ('کشور', 'keshvar', 'Land / Staat', 308, 'کشور بزرگی است.', 'Es ist ein großes Land.', 'Häufig in Nachrichten und Politik.', 5),
  ('مردم', 'mardom', 'Menschen / Volk', 308, 'مردم آمدند.', 'Die Leute kamen.', 'Kollektiv; sehr häufig in Medien und Alltag.', 5),
  ('گروه', 'goruh', 'Gruppe', 308, 'ما یک گروه کوچک هستیم.', 'Wir sind eine kleine Gruppe.', NULL, 5),
  ('اسلامی', 'eslâmi', 'islamisch', 308, 'این یک هنر اسلامی است.', 'Das ist eine islamische Kunst.', NULL, 4),
  ('رئیس', 'ra''is', 'Leiter / Präsident / Chef', 308, 'رئیس امروز نیامد.', 'Der Chef ist heute nicht gekommen.', NULL, 4),
  ('دولت', 'dowlat', 'Regierung / Staat', 308, 'دولت قانون تازه‌ای تصویب کرد.', 'Die Regierung verabschiedete ein neues Gesetz.', NULL, 4),
  ('جمله', 'jomle', 'Satz / Summe', 308, 'این جمله را ترجمه کن.', 'Übersetze diesen Satz.', NULL, 4),
  ('نفر', 'nafar', 'Person / Kopfzahl', 308, 'ده نفر در صف بودند.', 'Zehn Personen standen in der Schlange.', NULL, 4),
  ('سیاسی', 'siyâsi', 'politisch', 308, 'این یک مسئله‌ی سیاسی است.', 'Das ist eine politische Frage.', NULL, 4),
  ('جهان', 'jahân', 'Welt', 308, 'او دور جهان سفر کرد.', 'Er reiste um die Welt.', NULL, 4),
  ('علی', 'Ali', 'Ali', 308, 'علی دوست خوبی است.', 'Ali ist ein guter Freund.', NULL, 4),
  ('سازمان', 'sâzmân', 'Organisation', 308, 'او در یک سازمان بزرگ کار می‌کند.', 'Er arbeitet in einer großen Organisation.', NULL, 4),
  ('فرد', 'fard', 'Individuum / Einzelperson', 308, 'هر فرد حقوقی دارد.', 'Jedes Individuum hat Rechte.', NULL, 4),
  ('تیم', 'tim', 'Team', 308, 'تیم ما برنده شد.', 'Unser Team hat gewonnen.', NULL, 5),
  ('شورا', 'shurâ', 'Rat / Council', 308, 'شورای شهر جلسه داشت.', 'Der Stadtrat hatte eine Sitzung.', NULL, 5),
  ('وزیر', 'vazir', 'Minister', 308, 'وزیر سخنرانی کرد.', 'Der Minister hielt eine Rede.', NULL, 5),
  ('آقا', 'âghâ', 'Herr (Anrede)', 308, 'آقای محمدی اینجاست؟', 'Ist Herr Mohammadi hier?', 'Anrede / Eigenname', 5),
  ('شرکت', 'sherkat', 'Firma / Teilnahme', 308, 'او در یک شرکت بزرگ کار می‌کند.', 'Er arbeitet in einer großen Firma.', NULL, 5),
  ('کس', 'kas', 'jemand / Person', 308, 'کسی در خانه نیست.', 'Niemand ist zu Hause.', NULL, 5),
  ('عضو', 'ozv', 'Mitglied', 308, 'او عضو باشگاه است.', 'Er ist Mitglied des Klubs.', NULL, 4),
  -- L309
  ('محمد', 'mohammad', 'Mohammad', 309, 'محمد فردا می‌آید.', 'Mohammad kommt morgen.', 'Eigenname (Person)', 4),
  ('جامعه', 'jâme''e', 'Gesellschaft', 309, 'جامعه در حال تغییر است.', 'Die Gesellschaft verändert sich.', NULL, 4),
  ('مقام', 'maghâm', 'Rang / Amt', 309, 'او به مقام بالایی رسید.', 'Er erreichte einen hohen Rang.', NULL, 4),
  ('مجلس', 'majles', 'Parlament / Versammlung', 309, 'مجلس قانون را تصویب کرد.', 'Das Parlament verabschiedete das Gesetz.', NULL, 4),
  ('زن', 'zan', 'Frau', 309, 'آن زن معلم است.', 'Diese Frau ist Lehrerin.', NULL, 4),
  ('جمهوری', 'jomhuri', 'Republik', 309, 'این کشور یک جمهوری است.', 'Dieses Land ist eine Republik.', NULL, 4),
  ('سیاست', 'siyâsat', 'Politik / Strategie', 309, 'او به سیاست علاقه دارد.', 'Er interessiert sich für Politik.', NULL, 4),
  ('نماینده', 'namâyande', 'Vertreter / Abgeordneter', 309, 'او نماینده‌ی مردم است.', 'Er ist Vertreter des Volkes.', NULL, 4),
  ('ملت', 'mellat', 'Nation / Volk', 309, 'یک ملت بزرگ است.', 'Es ist eine große Nation.', NULL, 4),
  ('روزنامه', 'ruznâme', 'Zeitung', 309, 'هر صبح روزنامه می‌خوانم.', 'Jeden Morgen lese ich die Zeitung.', NULL, 4),
  ('جنگ', 'jang', 'Krieg', 309, 'جنگ سال‌ها طول کشید.', 'Der Krieg dauerte Jahre.', NULL, 4),
  ('صنعت', 'san''at', 'Industrie', 309, 'صنعت خودرو مهم است.', 'Die Autoindustrie ist wichtig.', NULL, 4),
  ('همکاری', 'hamkâri', 'Zusammenarbeit', 309, 'از همکاری شما ممنونم.', 'Ich danke für Ihre Zusammenarbeit.', NULL, 4),
  ('اسلام', 'eslâm', 'Islam', 309, 'اسلام در این منطقه گسترش یافت.', 'Der Islam breitete sich in dieser Region aus.', 'religiöser Begriff', 4),
  ('حسن', 'hasan', 'Hasan (Name) / Tugend', 309, 'حسن همسایه‌ی ماست.', 'Hasan ist unser Nachbar.', 'Eigenname', 4),
  ('خانواده', 'khânevâde', 'Familie', 309, 'خانواده‌ی بزرگی داریم.', 'Wir haben eine große Familie.', NULL, 4),
  ('وزارت', 'vezârat', 'Ministerium', 309, 'او در وزارت کار می‌کند.', 'Er arbeitet im Ministerium.', NULL, 4),
  ('انسان', 'ensân', 'Mensch', 309, NULL, NULL, NULL, 3),
  ('دانشگاه', 'dâneshgâh', 'Universität', 309, NULL, NULL, NULL, 3),
  -- L310
  ('استاد', 'ostâd', 'Professor / Meister', 310, NULL, NULL, NULL, 3),
  ('انتخابات', 'entekhâbât', 'Wahlen', 310, NULL, NULL, NULL, 3),
  ('فرهنگ', 'farhang', 'Kultur', 310, NULL, NULL, NULL, 3),
  ('انقلاب', 'enghelâb', 'Revolution', 310, NULL, NULL, 'politischer Begriff', 3),
  ('جمعیت', 'jam''iyyat', 'Bevölkerung / Menge', 310, NULL, NULL, NULL, 3),
  ('دین', 'din', 'Religion', 310, NULL, NULL, 'religiöser Begriff', 3),
  ('دکتر', 'doktor', 'Arzt / Doktor', 310, NULL, NULL, NULL, 3),
  ('هیئت', 'hey''at', 'Gremium / Delegation', 310, NULL, NULL, NULL, 3),
  ('شهید', 'shahid', 'Märtyrer', 310, NULL, NULL, 'religiös/politischer Begriff', 3),
  ('شاهد', 'shâhed', 'Zeuge', 310, NULL, NULL, NULL, 3),
  ('حزب', 'hezb', 'Partei', 310, NULL, NULL, 'politischer Begriff', 3),
  ('حاکم', 'hâkem', 'Herrscher / herrschend', 310, NULL, NULL, NULL, 3),
  ('مرد', 'mard', 'Mann', 310, NULL, NULL, NULL, 3),
  ('امام', 'emâm', 'Imam', 310, NULL, NULL, 'religiöser Begriff', 3),
  ('کودک', 'kudak', 'Kind', 310, NULL, NULL, NULL, 3),
  ('بانک', 'bânk', 'Bank', 310, NULL, NULL, NULL, 3),
  ('اداره', 'edâre', 'Amt / Behörde', 310, NULL, NULL, NULL, 3),
  ('دوست', 'dust', 'Freund', 310, NULL, NULL, NULL, 3),
  ('صاحب', 'sâheb', 'Herr / Besitzer', 310, NULL, NULL, NULL, 3),
  -- L311
  ('شهر', 'shahr', 'Stadt', 311, 'تهران شهر بزرگی است.', 'Teheran ist eine große Stadt.', 'Zentraler Ortsbegriff.', 5),
  ('ایران', 'Irân', 'Iran', 311, 'من ایران را دوست دارم.', 'Ich mag Iran.', 'Eigenname; relevant für Medien/Alltag.', 4),
  ('راه', 'râh', 'Weg / Straße / Methode', 311, 'راه حل چیست؟', 'Was ist die Lösung?', 'Konkreter und abstrakter Weg.', 5),
  ('نزدیک', 'nazdik', 'nah / nahe bei', 311, 'خانه‌ام نزدیک ایستگاه است.', 'Mein Haus ist nahe der Station.', NULL, 5),
  ('سو', 'su', 'Seite / Richtung', 311, 'از هر سو صدا می‌آمد.', 'Von allen Seiten kamen Geräusche.', NULL, 4),
  ('منطقه', 'mantaqe', 'Region / Gebiet', 311, 'این منطقه خیلی سرسبز است.', 'Diese Region ist sehr grün.', NULL, 4),
  ('بالا', 'bâlâ', 'oben / hoch', 311, 'کتاب روی طبقه‌ی بالا است.', 'Das Buch ist im oberen Regal.', NULL, 4),
  ('آمریکا', 'âmrikâ', 'Amerika / USA', 311, 'او در آمریکا زندگی می‌کند.', 'Er lebt in Amerika.', NULL, 4),
  ('تهران', 'tehrân', 'Teheran', 311, 'تهران پایتخت ایران است.', 'Teheran ist die Hauptstadt des Iran.', 'Eigenname (Ort)', 5),
  ('جا', 'jâ', 'Platz / Stelle', 311, 'اینجا جای خوبی است.', 'Hier ist ein guter Platz.', NULL, 4),
  ('مرکز', 'markaz', 'Zentrum', 311, 'مغازه در مرکز شهر است.', 'Der Laden ist im Stadtzentrum.', NULL, 4),
  ('زمین', 'zamin', 'Boden / Erde', 311, 'توپ روی زمین افتاد.', 'Der Ball fiel auf den Boden.', NULL, 4),
  ('خارج', 'khârej', 'außen / Ausland', 311, 'او در خارج درس می‌خواند.', 'Er studiert im Ausland.', NULL, 4),
  ('استان', 'ostân', 'Provinz', 311, NULL, NULL, NULL, 3),
  ('خانه', 'khâne', 'Haus', 311, NULL, NULL, NULL, 3),
  ('بازار', 'bâzâr', 'Markt / Basar', 311, NULL, NULL, NULL, 3),
  ('میدان', 'meydân', 'Platz / Feld', 311, NULL, NULL, NULL, 3),
  ('دفتر', 'daftar', 'Büro / Heft', 311, NULL, NULL, NULL, 3),
  ('فرانسه', 'farânse', 'Frankreich / französisch', 311, NULL, NULL, 'Eigenname (Land)', 3),
  ('مدرسه', 'madrese', 'Schule', 311, NULL, NULL, NULL, 3),
  ('مسیر', 'masir', 'Weg / Route', 311, NULL, NULL, NULL, 3),
  ('افغانستان', 'afghânestân', 'Afghanistan', 311, NULL, NULL, 'Eigenname (Land)', 3),
  ('محل', 'mahal', 'Ort / Stelle', 311, NULL, NULL, NULL, 3),
  ('اروپا', 'orupâ', 'Europa', 311, NULL, NULL, 'Eigenname (Kontinent)', 3),
  ('چین', 'chin', 'China', 311, NULL, NULL, 'Eigenname (Land)', 3),
  -- L312
  ('بزرگ', 'bozorg', 'groß / wichtig', 312, 'شهر بزرگی است.', 'Es ist eine große Stadt.', 'Auch metaphorisch: wichtig/bedeutend.', 5),
  ('مهم', 'mohem', 'wichtig', 312, 'این موضوع مهم است.', 'Dieses Thema ist wichtig.', 'Sehr häufig, auch substantivisch.', 5),
  ('بهتر', 'behtar', 'besser', 312, 'امروز حالم بهتر است.', 'Heute geht es mir besser.', NULL, 4),
  ('مختلف', 'mokhtalef', 'verschieden / unterschiedlich', 312, 'رنگ‌های مختلفی دارد.', 'Es hat verschiedene Farben.', NULL, 4),
  ('جدید', 'jadid', 'neu', 312, 'این کفش‌ها جدید هستند.', 'Diese Schuhe sind neu.', NULL, 4),
  ('جوان', 'javân', 'jung', 312, 'او مرد جوانی است.', 'Er ist ein junger Mann.', NULL, 5),
  ('ملی', 'melli', 'national', 312, 'امروز جشن ملی است.', 'Heute ist Nationalfeiertag.', NULL, 5),
  ('اقتصادی', 'eghtesâdi', 'wirtschaftlich', 312, 'وضع اقتصادی بهتر شده است.', 'Die wirtschaftliche Lage hat sich verbessert.', NULL, 5),
  ('حاضر', 'hâzer', 'anwesend / bereit', 312, 'همه در جلسه حاضر بودند.', 'Alle waren bei der Sitzung anwesend.', NULL, 4),
  ('ممکن', 'momken', 'möglich', 312, 'این کار ممکن است.', 'Diese Sache ist möglich.', NULL, 4),
  ('زیادی', 'ziyâdi', 'übermäßig / zu viel', 312, 'قند زیادی خوردی.', 'Du hast zu viel Zucker gegessen.', NULL, 4),
  ('اصلی', 'asli', 'haupt- / wesentlich', 312, 'دلیل اصلی این بود.', 'Der Hauptgrund war dieser.', NULL, 4),
  ('خارجی', 'khâreji', 'ausländisch / fremd', 312, 'او یک زبان خارجی بلد است.', 'Er kann eine Fremdsprache.', NULL, 4),
  ('همراه', 'hamrâh', 'begleitend / zusammen mit', 312, 'همراه دوستم آمدم.', 'Ich kam zusammen mit meinem Freund.', NULL, 4),
  ('جهانی', 'jahâni', 'global / weltweit', 312, 'این یک مشکل جهانی است.', 'Das ist ein globales Problem.', NULL, 4),
  ('ویژه', 'vizhe', 'besonders / speziell', 312, 'این روز ویژه‌ای است.', 'Das ist ein besonderer Tag.', NULL, 4),
  ('برابر', 'barâbar', 'gleich / gegenüber', 312, 'دو نیمه برابر است.', 'Die zwei Hälften sind gleich.', NULL, 4),
  ('ایرانی', 'irâni', 'iranisch', 312, 'غذای ایرانی خوشمزه است.', 'Iranisches Essen ist lecker.', NULL, 4),
  ('کامل', 'kâmel', 'vollständig', 312, 'کار را کامل انجام بده.', 'Erledige die Arbeit vollständig.', NULL, 4),
  ('آزاد', 'âzâd', 'frei', 312, 'امروز وقت آزاد دارم.', 'Heute habe ich freie Zeit.', NULL, 4),
  ('مسئول', 'mas''ul', 'verantwortlich / zuständig', 312, 'چه کسی مسئول است؟', 'Wer ist verantwortlich?', NULL, 4),
  ('موفق', 'movaffagh', 'erfolgreich', 312, 'در امتحان موفق شدم.', 'Ich war in der Prüfung erfolgreich.', NULL, 4),
  -- L313
  ('اخیر', 'akhir', 'jüngst / kürzlich', 313, 'در روزهای اخیر سرد بوده است.', 'In den letzten Tagen war es kalt.', NULL, 4),
  ('دور', 'dovr', 'fern / Runde', 313, 'شهر آن‌ها دور است.', 'Ihre Stadt ist weit weg.', NULL, 4),
  ('برگزار', 'bargozâr', 'abgehalten / veranstaltet', 313, 'جشن دیشب برگزار شد.', 'Das Fest fand gestern Abend statt.', NULL, 4),
  ('قابل', 'ghâbel', 'fähig / verfügbar', 313, 'این آب قابل نوشیدن است.', 'Dieses Wasser ist trinkbar.', NULL, 4),
  ('عمومی', 'omumi', 'öffentlich / allgemein', 313, NULL, NULL, NULL, 3),
  ('جدی', 'jeddi', 'ernst', 313, NULL, NULL, NULL, 3),
  ('داخلی', 'dâkheli', 'intern / inländisch', 313, NULL, NULL, NULL, 3),
  ('الزم', 'lâzem', 'nötig / erforderlich', 313, NULL, NULL, NULL, 3),
  ('علمی', 'elmi', 'wissenschaftlich', 313, NULL, NULL, NULL, 3),
  ('اجتماعی', 'ejtemâ''i', 'sozial', 313, NULL, NULL, NULL, 3),
  ('مرکزی', 'markazi', 'zentral', 313, NULL, NULL, NULL, 3),
  ('مطرح', 'matrah', 'viel diskutiert / aufgeworfen', 313, NULL, NULL, NULL, 3),
  ('انسانی', 'ensâni', 'menschlich', 313, NULL, NULL, NULL, 3),
  ('خاص', 'khâss', 'speziell / eigen', 313, NULL, NULL, NULL, 3),
  ('مشخص', 'moshakhkhas', 'bestimmt / festgelegt', 313, NULL, NULL, NULL, 3),
  ('کلی', 'kolli', 'allgemein / gesamt', 313, NULL, NULL, NULL, 3),
  ('کوتاه', 'kutâh', 'kurz', 313, NULL, NULL, NULL, 3),
  ('فرهنگی', 'farhangi', 'kulturell', 313, NULL, NULL, NULL, 3),
  ('کاری', 'kâri', 'arbeits- / tätig', 313, NULL, NULL, NULL, 3),
  ('زمانی', 'zamâni', 'zeitlich', 313, NULL, NULL, NULL, 3),
  ('موافق', 'movâfegh', 'einverstanden', 313, NULL, NULL, NULL, 3),
  ('مناسب', 'monâseb', 'passend / geeignet', 313, NULL, NULL, NULL, 3),
  -- L314
  ('آماده', 'âmâde', 'bereit', 314, NULL, NULL, NULL, 3),
  ('موجود', 'movjud', 'vorhanden / Lebewesen', 314, NULL, NULL, NULL, 3),
  ('کوچک', 'kuchak', 'klein', 314, NULL, NULL, NULL, 3),
  ('پیدا', 'peydâ', 'gefunden / sichtbar', 314, NULL, NULL, NULL, 3),
  ('طولانی', 'tulâni', 'lang / langwierig', 314, NULL, NULL, NULL, 3),
  ('معتقد', 'mo''taghed', 'überzeugt / gläubig', 314, NULL, NULL, NULL, 3),
  ('مشترک', 'moshtarak', 'gemeinsam / Teilnehmer', 314, NULL, NULL, NULL, 3),
  ('مستقیم', 'mostaghim', 'direkt / gerade', 314, NULL, NULL, NULL, 3),
  ('آمریکایی', 'âmrikâyi', 'amerikanisch', 314, NULL, NULL, NULL, 3),
  ('مالی', 'mâli', 'finanziell', 314, NULL, NULL, NULL, 3),
  ('ساخته', 'sâkhte', 'hergestellt / gefertigt', 314, NULL, NULL, NULL, 3),
  ('واقعی', 'vâghe''i', 'echt / wirklich', 314, NULL, NULL, NULL, 3),
  ('دینی', 'dini', 'religiös', 314, NULL, NULL, NULL, 3),
  ('دولتی', 'dovlati', 'staatlich / Regierungs-', 314, NULL, NULL, NULL, 3),
  ('رسمی', 'rasmi', 'offiziell', 314, NULL, NULL, NULL, 3),
  ('سنگین', 'sangin', 'schwer', 314, NULL, NULL, NULL, 3),
  ('نظامی', 'nezâmi', 'militärisch', 314, NULL, NULL, 'Homograph: نظامی = militärisch / Nezami', 3),
  ('شدید', 'shadid', 'heftig / stark', 314, NULL, NULL, NULL, 3),
  ('مربوط', 'marbut', 'zugehörig / betreffend', 314, NULL, NULL, NULL, 3),
  ('واقع', 'vâghe''', 'gelegen / tatsächlich', 314, NULL, NULL, NULL, 3),
  ('کافی', 'kâfi', 'ausreichend / genug', 314, NULL, NULL, NULL, 3),
  -- L315
  ('بسیار', 'besyâr', 'sehr / viel', 315, 'بسیار خوب.', 'Sehr gut.', 'Etwas formeller als خیلی.', 5),
  ('تنها', 'tanhâ', 'allein / nur', 315, 'تنها یک راه وجود دارد.', 'Es gibt nur einen Weg.', 'Kann ''allein'' oder ''nur'' bedeuten.', 5),
  ('البته', 'albatte', 'natürlich / freilich', 315, 'البته که کمکت می‌کنم.', 'Natürlich helfe ich dir.', NULL, 5),
  ('در حال', 'darhâl', 'im Begriff (zu) / dabei', 315, 'او در حال خواندن است.', 'Er ist gerade beim Lesen.', NULL, 5),
  ('حتی', 'hattâ', 'sogar', 315, 'حتی او هم آمد.', 'Sogar er kam auch.', NULL, 4),
  ('آخر', 'âkhar', 'letzte/r/s / schließlich', 315, 'آخرِ ماه پول کم می‌آورم.', 'Am Monatsende fehlt mir Geld.', NULL, 4),
  ('کاملاً', 'kâmelan', 'völlig / vollständig', 315, 'کاملاً درست می‌گویی.', 'Du hast völlig recht.', NULL, 4),
  ('هنوز', 'hanuz', 'noch / immer noch', 315, 'او هنوز نیامده است.', 'Er ist noch nicht gekommen.', NULL, 4),
  ('نخست', 'nokhost', 'zuerst / erstens', 315, 'نخست باید استراحت کنی.', 'Zuerst musst du dich ausruhen.', NULL, 4),
  ('مانند', 'mânand', 'wie / ähnlich', 315, 'او مانند پدرش است.', 'Er ist wie sein Vater.', NULL, 4),
  ('اکنون', 'aknun', 'jetzt / nun', 315, 'اکنون وقت رفتن است.', 'Jetzt ist es Zeit zu gehen.', NULL, 4),
  ('فقط', 'faghat', 'nur / bloß', 315, NULL, NULL, NULL, 3),
  ('خیلی', 'kheyli', 'sehr', 315, NULL, NULL, NULL, 3),
  ('خوبی', 'khubi', 'Güte / gut', 315, NULL, NULL, NULL, 3),
  ('زیاد', 'ziyâd', 'viel / sehr', 315, NULL, NULL, NULL, 3),
  ('تازه', 'tâze', 'frisch / neu', 315, NULL, NULL, NULL, 3),
  ('تاکنون', 'tâknun', 'bisher', 315, NULL, NULL, NULL, 3),
  -- L401
  ('اول', 'avval', 'erste/r/s / zuerst', 401, 'اول گوش بده.', 'Hör zuerst zu.', 'Reihenfolge und Diskursstruktur.', 5),
  ('سال', 'sâl', 'Jahr', 401, 'سه سال پیش', 'vor drei Jahren', 'Zentrales Zeitwort; auch Alter: ساله.', 5),
  ('روز', 'ruz', 'Tag', 401, 'روز خوبی بود.', 'Es war ein guter Tag.', 'Zeit, Datum, Routine.', 5),
  ('پیش', 'pish', 'vor / vorher / bei', 401, 'دو سال پیش', 'vor zwei Jahren', 'Zeitlich und räumlich; auch bei Personen: پیش من.', 5),
  ('قبل', 'ghabl', 'vorher / bevor', 401, 'قبل از جلسه', 'vor dem Treffen', 'Mit از: قبل از = vor.', 5),
  ('مدت', 'moddat', 'Dauer / Zeitraum', 401, 'برای مدت کوتاهی', 'für kurze Zeit', 'Häufig in مدت کوتاه/طولانی.', 4),
  ('گذشته', 'gozashte', 'Vergangenheit / vergangen', 401, 'گذشته را فراموش کن.', 'Vergiss die Vergangenheit.', NULL, 5),
  ('ماه', 'mâh', 'Monat / Mond', 401, 'ماه آینده تعطیلات دارم.', 'Nächsten Monat habe ich Urlaub.', NULL, 5),
  ('زمان', 'zamân', 'Zeit', 401, 'زمان زود می‌گذرد.', 'Die Zeit vergeht schnell.', NULL, 4),
  ('بار', 'bâr', 'Mal / Last', 401, 'این بار من می‌پردازم.', 'Dieses Mal zahle ich.', NULL, 4),
  ('حال', 'hâl', 'Zustand / Gegenwart / jetzt', 401, 'حالت چطور است؟', 'Wie ist dein Befinden?', NULL, 4),
  ('بعد', 'ba''d', 'danach / nach / später', 401, 'بعد از ناهار می‌آیم.', 'Nach dem Mittagessen komme ich.', NULL, 4),
  ('دوره', 'dovre', 'Periode / Kurs', 401, 'یک دوره‌ی زبان شروع کردم.', 'Ich habe einen Sprachkurs begonnen.', NULL, 5),
  ('پایان', 'pâyân', 'Ende', 401, 'تا پایان فیلم ماندیم.', 'Wir blieben bis zum Ende des Films.', NULL, 4),
  ('آینده', 'âyande', 'Zukunft / künftig', 401, 'به آینده امیدوارم.', 'Ich bin hoffnungsvoll für die Zukunft.', NULL, 4),
  -- L402
  ('امروز', 'emruz', 'heute', 402, 'امروز هوا آفتابی است.', 'Heute ist das Wetter sonnig.', NULL, 4),
  ('ساعت', 'sâ''at', 'Stunde / Uhr', 402, 'ساعت چند است؟', 'Wie spät ist es?', NULL, 4),
  ('هفته', 'hafte', 'Woche', 402, 'این هفته خیلی شلوغ است.', 'Diese Woche ist sehr voll.', NULL, 4),
  ('آغاز', 'âghâz', 'Beginn / Anfang', 402, 'آغاز سال نو مبارک.', 'Frohen Beginn des neuen Jahres.', NULL, 4),
  ('مرحله', 'marhale', 'Stufe / Phase', 402, 'به مرحله‌ی بعد رسیدیم.', 'Wir haben die nächste Stufe erreicht.', NULL, 4),
  ('تاریخ', 'târikh', 'Geschichte / Datum', 402, NULL, NULL, NULL, 3),
  ('دقیقه', 'daghighe', 'Minute', 402, NULL, NULL, NULL, 3),
  ('دوران', 'dovrân', 'Ära / Zeitraum', 402, NULL, NULL, NULL, 3),
  ('وقت', 'vaght', 'Zeit', 402, NULL, NULL, NULL, 3),
  ('فصل', 'fasl', 'Jahreszeit / Kapitel', 402, NULL, NULL, NULL, 3),
  ('شب', 'shab', 'Nacht', 402, NULL, NULL, NULL, 3),
  ('شروع', 'shoru''', 'Beginn / Start', 402, NULL, NULL, NULL, 3),
  ('ابتدا', 'ebtedâ', 'Anfang / zuerst', 402, NULL, NULL, NULL, 3),
  ('شنبه', 'shambe', 'Samstag', 402, NULL, NULL, NULL, 3),
  ('دهه', 'dahe', 'Jahrzehnt', 402, NULL, NULL, NULL, 3),
  -- L403
  ('یک', 'yek', 'eins / ein', 403, 'یک سؤال دارم.', 'Ich habe eine Frage.', 'Zahlwort und unbestimmter Artikel-ähnliche Funktion.', 5),
  ('دو', 'do', 'zwei', 403, 'دو سؤال دارم.', 'Ich habe zwei Fragen.', 'Zahlwort.', 5),
  ('دوم', 'dovvom', 'zweite/r/s', 403, 'این بار دوم است.', 'Das ist das zweite Mal.', NULL, 5),
  ('سه', 'se', 'drei', 403, 'سه کتاب خریدم.', 'Ich habe drei Bücher gekauft.', NULL, 5),
  ('هزار', 'hezâr', 'tausend', 403, 'این لباس صد هزار تومان است.', 'Dieses Kleid kostet hunderttausend Tuman.', NULL, 5),
  ('میلیون', 'milyun', 'Million', 403, 'این شهر دو میلیون نفر جمعیت دارد.', 'Diese Stadt hat zwei Millionen Einwohner.', NULL, 4),
  ('سوم', 'sevvom', 'dritte/r/s', 403, 'او در مسابقه سوم شد.', 'Er wurde im Wettbewerb Dritter.', NULL, 4),
  ('میلیارد', 'milyârd', 'Milliarde', 403, NULL, NULL, NULL, 3),
  ('چهار', 'chahâr', 'vier', 403, NULL, NULL, NULL, 3),
  ('چهارم', 'chahârom', 'vierte/r/s', 403, NULL, NULL, NULL, 3),
  ('ده', 'dah', 'zehn (auch: Dorf)', 403, NULL, NULL, NULL, 3)
) as v(hangul, romanisierung, deutsch, lektion_nummer, beispielsatz_ko, beispielsatz_de, hinweis, haeufigkeit);
