-- ============================================================================
-- KANONISCHER SEED – automatisch erzeugt aus data/vokabeln.json (scripts/build.py).
-- NICHT von Hand editieren – Änderungen in data/vokabeln.json vornehmen.
-- Upsert-basiert: aktualisiert bestehende Zeilen in place → Übungsfortschritt
-- (review_state / dictation_attempts) bleibt erhalten.
-- Voraussetzung: Migrationen 0001–0007. Im Supabase SQL Editor ausführen.
-- App-Login-E-Mail: jreitzenstein@gmail.com
-- ============================================================================

-- 1) Lektionen (Upsert)
insert into public.lessons (user_id, buch, lektion_nummer, titel, beschreibung, reihenfolge)
select (select id from auth.users where email='jreitzenstein@gmail.com'), v.buch, v.lektion_nummer, v.titel, v.beschreibung, v.lektion_nummer
from (values
  (1, 101, 'Konnektoren', 'Teil 1 – Grammatik-Gerüst'),
  (1, 102, 'Präpositionen', 'Teil 1 – Grammatik-Gerüst'),
  (1, 103, 'Pronomen', 'Teil 1 – Grammatik-Gerüst'),
  (1, 104, 'Quantoren', 'Teil 1 – Grammatik-Gerüst'),
  (1, 105, 'Fragewörter', 'Teil 1 – Grammatik-Gerüst'),
  (1, 106, 'Verneinung', 'Teil 1 – Grammatik-Gerüst'),
  (2, 201, 'Kernverben 1', 'Teil 2 – Verben'),
  (2, 202, 'Kernverben 2', 'Teil 2 – Verben'),
  (2, 203, 'Modalverben', 'Teil 2 – Verben'),
  (2, 204, 'Funktionsverbgefüge', 'Teil 2 – Verben'),
  (3, 301, 'Politik & Staat', 'Teil 3 – Themen'),
  (3, 302, 'Gesellschaft & Menschen', 'Teil 3 – Themen'),
  (3, 303, 'Arbeit, Wirtschaft & Geld', 'Teil 3 – Themen'),
  (3, 304, 'Bildung & Wissenschaft', 'Teil 3 – Themen'),
  (3, 305, 'Medien, Sprache & Kommunikation', 'Teil 3 – Themen'),
  (3, 306, 'Orte, Länder & Wege', 'Teil 3 – Themen'),
  (3, 307, 'Konflikt, Recht & Sicherheit', 'Teil 3 – Themen'),
  (3, 308, 'Ursache & Zusammenhang', 'Teil 3 – Themen'),
  (3, 309, 'Art, Form, Maß & Menge', 'Teil 3 – Themen'),
  (3, 310, 'Handlung, Vorgang & Veränderung', 'Teil 3 – Themen'),
  (3, 311, 'Alltag, Körper & Natur', 'Teil 3 – Themen'),
  (3, 312, 'Adjektive 1', 'Teil 3 – Wortschatz'),
  (3, 313, 'Adjektive 2', 'Teil 3 – Wortschatz'),
  (3, 314, 'Adjektive 3', 'Teil 3 – Wortschatz'),
  (3, 315, 'Adverbien', 'Teil 3 – Wortschatz'),
  (4, 401, 'Zeit 1', 'Teil 4 – Zeit & Zahlen'),
  (4, 402, 'Zeit 2', 'Teil 4 – Zeit & Zahlen'),
  (4, 403, 'Zahlen', 'Teil 4 – Zeit & Zahlen'),
  (5, 501, 'Fußball', 'Teil 5 – Themen'),
  (5, 502, 'Ferien', 'Teil 5 – Themen'),
  (5, 503, 'Krieg & Frieden', 'Teil 5 – Themen'),
  (6, 601, 'Begrüßung & Höflichkeit', 'Teil 6 – Alltag & Redewendungen'),
  (6, 602, 'Zeit & Datum', 'Teil 6 – Alltag & Redewendungen'),
  (6, 603, 'Fragen', 'Teil 6 – Alltag & Redewendungen'),
  (6, 604, 'Aufforderungen', 'Teil 6 – Alltag & Redewendungen'),
  (6, 605, 'Alltag & Ausdrücke', 'Teil 6 – Alltag & Redewendungen'),
  (6, 606, 'Gefühle & Zustände', 'Teil 6 – Alltag & Redewendungen'),
  (6, 607, 'Umgangssprache: Beleidigungen (Vorsicht)', 'Teil 6 – Alltag & Redewendungen')
) as v(buch, lektion_nummer, titel, beschreibung)
on conflict (user_id, lektion_nummer) do update set
  buch=excluded.buch, titel=excluded.titel, beschreibung=excluded.beschreibung,
  reihenfolge=excluded.reihenfolge;

-- 2) Vokabeln (Upsert über (user_id, hangul, lektion_nummer))
insert into public.vocab_items
  (user_id, hangul, romanisierung, deutsch, lektion_nummer, beispielsatz_ko, beispielsatz_de, hinweis, haeufigkeit)
select (select id from auth.users where email='jreitzenstein@gmail.com'), v.*
from (values
  -- L101
  ('اما', 'ammâ', 'aber', 101, 'می‌خواستم بیایم، اما نتوانستم.', 'Ich wollte kommen, aber ich konnte nicht.', 'Formeller als ولی, aber beide sehr wichtig.', 5),
  ('اگر', 'agar', 'wenn / falls', 101, 'اگر باران بیاید، نمی‌رویم.', 'Wenn es regnet, gehen wir nicht.', NULL, 5),
  ('بلکه', 'balke', 'sondern / vielmehr', 101, 'او نیامد، بلکه تلفن کرد.', 'Er kam nicht, sondern rief an.', NULL, 4),
  ('تا', 'tâ', 'bis / damit / um zu', 101, 'تا فردا صبر کن.', 'Warte bis morgen.', 'Polyfunktional: Grenze, Zweck, bis dass.', 5),
  ('جز', 'joz', 'außer / abgesehen von', 101, 'همه آمدند جز او.', 'Alle kamen außer ihm.', NULL, 4),
  ('دیگر', 'digar', 'anderer / sonst / nicht mehr', 101, 'یک بار دیگر', 'noch einmal', 'Polyfunktional; in Negationen: دیگر نه.', 5),
  ('نیز', 'niz', 'auch / ebenfalls', 101, 'او نیز آمد.', 'Er/sie kam ebenfalls.', 'Schriftsprachlicher als هم.', 4),
  ('هم', 'ham', 'auch / ebenfalls / beide', 101, 'من هم می‌آیم.', 'Ich komme auch.', 'Extrem häufig; in Kombinationen: هم... هم.', 5),
  ('همچنین', 'hamchenin', 'außerdem / ebenso', 101, 'او آمد، همچنین برادرش.', 'Er kam, ebenso sein Bruder.', NULL, 4),
  ('و', 'vâv / va', 'und', 101, 'من و تو', 'ich und du', 'Extrem häufig; verbindet Wörter und Satzteile.', 5),
  ('وقتی', 'vaghti', 'wenn / als', 101, 'وقتی آمد، خوابیده بودم.', 'Als er kam, schlief ich.', NULL, 4),
  ('ولی', 'vali', 'aber', 101, 'من خسته‌ام، اما خوشحالم.', 'Ich bin müde, aber glücklich.', NULL, 5),
  ('پس', 'pas', 'dann / also / nach', 101, 'پس شروع کنیم.', 'Dann fangen wir an.', 'Diskursmarker: also/dann; auch räumlich/zeitlich.', 5),
  ('چون', 'chun', 'weil / wie', 101, 'چون باران می‌بارید، نرفتم.', 'Weil es regnete, ging ich nicht.', NULL, 4),
  ('که', 'ke', 'dass / der / die / welcher', 101, 'می‌دانم که او می‌آید.', 'Ich weiß, dass er/sie kommt.', 'Sehr häufiges Relativ- und Ergänzungswort; mit ganzen Sätzen lernen.', 5),
  ('یا', 'yâ', 'oder', 101, 'چای یا قهوه؟', 'Tee oder Kaffee?', 'Alternative/Entscheidung.', 5),
  ('یعنی', 'ya''ni', 'das heißt / nämlich', 101, 'دیر شد، یعنی باید عجله کنیم.', 'Es ist spät, das heißt, wir müssen uns beeilen.', NULL, 4),
  -- L102
  ('از', 'az', 'von / aus / seit', 102, 'من از آلمانم.', 'Ich bin aus Deutschland.', 'Sehr produktive Präposition; auch in Vergleichen und Herkunft.', 5),
  ('با', 'bâ', 'mit', 102, 'با دوستم آمدم.', 'Ich kam mit meinem Freund.', 'Mittel, Begleitung; sehr häufig in Alltagsrede.', 5),
  ('بدون', 'bedun', 'ohne', 102, 'بدون تو نمی‌روم.', 'Ohne dich gehe ich nicht.', NULL, 4),
  ('بر', 'bar', 'auf / über / an', 102, 'بر اساس این گزارش', 'auf Grundlage dieses Berichts', 'Schriftsprachlich/gehoben; in vielen festen Verbindungen.', 4),
  ('برای', 'barâye', 'für', 102, 'این برای شماست.', 'Das ist für Sie/dich.', 'Zweck, Empfänger, Vorteil.', 5),
  ('به', 'be', 'zu / nach / an', 102, 'به تهران می‌روم.', 'Ich gehe nach Teheran.', 'Richtung, Dativ-ähnliche Funktionen und feste Wendungen.', 5),
  ('بین', 'beyn', 'zwischen', 102, 'مغازه بین بانک و داروخانه است.', 'Der Laden ist zwischen Bank und Apotheke.', NULL, 5),
  ('تحت', 'taht', 'unter', 102, 'تحت فشار هستم.', 'Ich stehe unter Druck.', NULL, 4),
  ('تو', 'to', 'in / hinein (ugs. „du")', 102, 'تو خانه هستم.', 'Ich bin zu Hause.', NULL, 4),
  ('توسط', 'tavassot', 'durch / seitens', 102, 'این کتاب توسط او نوشته شد.', 'Dieses Buch wurde von ihm geschrieben.', NULL, 4),
  ('جهت', 'jahat', 'Richtung / wegen', 102, 'به جهت سرما نرفتیم.', 'Wegen der Kälte gingen wir nicht.', NULL, 4),
  ('داخل', 'dâkhel', 'innen / innerhalb', 102, 'داخل خانه گرم است.', 'Im Haus ist es warm.', NULL, 4),
  ('در', 'dar', 'in / in dem', 102, 'در خانه هستم.', 'Ich bin zu Hause.', 'Eine der wichtigsten Orts- und Bereichspräpositionen.', 5),
  ('درباره', 'darbâre', 'über / betreffend', 102, 'درباره‌ی این کتاب حرف زدیم.', 'Wir sprachen über dieses Buch.', NULL, 4),
  ('رو', 'ru', 'auf / Gesicht / Oberfläche', 102, 'کتاب رو میز است.', 'Das Buch ist auf dem Tisch.', NULL, 4),
  ('زیر', 'zir', 'unter / unterhalb', 102, 'کتاب زیر میز است.', 'Das Buch ist unter dem Tisch.', NULL, 4),
  ('طی', 'tey', 'während / im Verlauf', 102, 'طی این هفته کار کردم.', 'Im Laufe dieser Woche habe ich gearbeitet.', NULL, 4),
  ('مقابل', 'moghâbel', 'gegenüber', 102, 'مقابل خانه ایستادم.', 'Ich stand gegenüber dem Haus.', NULL, 4),
  ('میان', 'miyân', 'zwischen / Mitte', 102, 'میان دو کشور', 'zwischen zwei Ländern', 'Nahe bei بین; in Medien/Schrift häufig.', 4),
  ('کنار', 'kenâr', 'neben / Seite', 102, 'کنار من بنشین.', 'Setz dich neben mich.', NULL, 4),
  -- L103
  ('آن', 'ân', 'das / jener / jene', 103, 'آن روز را یادم هست.', 'Ich erinnere mich an jenen Tag.', 'In geschriebener Sprache häufiger; gesprochen oft اون.', 5),
  ('او', 'u', 'er / sie', 103, 'او اینجاست.', 'Er/sie ist hier.', 'Geschlechtsneutral im Persischen.', 5),
  ('ایشان', 'ishân', 'sie / er/sie (höflich)', 103, 'ایشان استاد دانشگاه هستند.', 'Er/Sie ist Universitätsprofessor(in).', NULL, 4),
  ('این', 'in', 'dies / dieser / diese', 103, 'این کتاب خوب است.', 'Dieses Buch ist gut.', 'Deiktisches Pronomen; oft als Demonstrativbegleiter.', 5),
  ('خود', 'khod', 'selbst / sich', 103, 'خودم انجام دادم.', 'Ich habe es selbst gemacht.', 'Reflexiv/Intensivierung: خودم، خودت، خودش.', 5),
  ('سایر', 'sâyer', 'übrige / andere', 103, 'سایر مهمانان هم آمدند.', 'Die übrigen Gäste kamen auch.', NULL, 4),
  ('شما', 'shomâ', 'ihr / Sie', 103, 'شما کجا هستید؟', 'Wo seid ihr / sind Sie?', NULL, 5),
  ('ما', 'mâ', 'wir', 103, 'ما فارسی می‌خوانیم.', 'Wir lernen/lesen Persisch.', 'Personalpronomen.', 5),
  ('من', 'man', 'ich / mich', 103, 'من فردا می‌آیم.', 'Ich komme morgen.', NULL, 4),
  ('همان', 'hamân', 'eben jener / derselbe', 103, 'همان فیلم را دوباره دیدیم.', 'Wir sahen denselben Film nochmal.', NULL, 4),
  ('همین', 'hamin', 'genau dieser / derselbe', 103, 'همین را می‌خواستم.', 'Genau das wollte ich.', NULL, 5),
  ('وی', 'vey', 'er / sie', 103, 'وی سال‌ها در اینجا کار کرده است.', 'Er hat jahrelang hier gearbeitet.', NULL, 4),
  ('چنین', 'chenin', 'solch / derartig', 103, 'چنین چیزی ندیده بودم.', 'So etwas hatte ich nicht gesehen.', NULL, 4),
  -- L104
  ('برخی', 'barkhi', 'einige / manche', 104, 'برخی از مردم آمدند.', 'Einige der Leute kamen.', NULL, 5),
  ('بیش', 'bish', 'mehr', 104, 'بیش از ده نفر آمدند.', 'Mehr als zehn Personen kamen.', 'Oft in بیش از = mehr als; بیشتر gebräuchlicher im Alltag.', 4),
  ('تمام', 'tamâm', 'ganz / vollständig / alle', 104, 'تمام روز کار کردم.', 'Ich habe den ganzen Tag gearbeitet.', NULL, 5),
  ('هر', 'har', 'jede/r/s', 104, 'هر روز تمرین می‌کنم.', 'Ich übe jeden Tag.', 'Sehr häufig vor Nomen: هر روز، هر کس.', 5),
  ('همه', 'hame', 'alle / alles', 104, 'همه چیز خوب است.', 'Alles ist gut.', 'Allquantor.', 5),
  ('چند', 'chand', 'einige / mehrere / wie viele', 104, 'چند روز اینجا می‌مانی؟', 'Wie viele Tage bleibst du hier?', NULL, 5),
  ('کم', 'kam', 'wenig / niedrig', 104, 'وقت کم است.', 'Die Zeit ist knapp.', 'Gegensatz zu زیاد/بیشتر.', 5),
  -- L105
  ('آیا', 'âyâ', 'ob (Fragepartikel)', 105, 'آیا تو می‌آیی؟', 'Kommst du?', NULL, 4),
  ('چرا', 'cherâ', 'warum', 105, 'چرا نیامدی؟', 'Warum bist du nicht gekommen?', NULL, 4),
  ('چه', 'che', 'was / welcher / wie', 105, 'چه کتابی می‌خوانی؟', 'Welches Buch liest du?', NULL, 4),
  -- L106
  ('نه', 'na', 'nein / nicht (auch: neun)', 106, 'نه، من نمی‌آیم.', 'Nein, ich komme nicht.', 'Homograph: نه = nein / neun', 4),
  ('هیچ', 'hich', 'kein / nichts / überhaupt', 106, 'هیچ کس خانه نبود.', 'Niemand war zu Hause.', NULL, 4),
  -- L201
  ('آمدن', 'âmadan', 'kommen', 201, 'او دیر آمد.', 'Er ist spät gekommen.', 'Präsensstamm: آی.', 4),
  ('بودن', 'budan', 'sein', 201, 'من خانه بودم.', 'Ich war zu Hause.', 'Präsensstamm: باش. Zentrales Verb; auch als Kopula/Perfekt-Hilfsverb wichtig.', 5),
  ('خواستن', 'khâstan', 'wollen / wünschen', 201, 'می‌خواهم فارسی بخوانم.', 'Ich möchte Persisch lernen/lesen.', 'Präsensstamm: خواه. Für Wünsche und Futurbildung wichtig: خواهم رفت.', 5),
  ('دادن', 'dâdan', 'geben', 201, 'کتاب را به من داد.', 'Er/sie gab mir das Buch.', 'Präsensstamm: ده. Basis vieler zusammengesetzter Verben: نشان دادن، انجام دادن.', 5),
  ('داده', 'dâde', 'gegeben / Daten', 201, 'داده‌ها مهم هستند.', 'Die Daten sind wichtig.', 'Präsensstamm: ده. Partizip von دادن; auch داده = Daten.', 4),
  ('داشتن', 'dâshtan', 'haben', 201, 'من وقت دارم.', 'Ich habe Zeit.', 'Präsensstamm: دار. Besitz, Zustände und Progressive-Konstruktionen.', 5),
  ('داشته', 'dâshte', 'gehabt / Besitz', 201, 'او این تجربه را داشته است.', 'Er/sie hat diese Erfahrung gehabt.', 'Präsensstamm: دار. Partizip/Perfektformen von داشتن.', 4),
  ('دانستن', 'dânestan', 'wissen / kennen', 201, 'می‌خواهم جواب را بدانم.', 'Ich möchte die Antwort wissen.', 'Präsensstamm: دان.', 4),
  ('رسیدن', 'residan', 'ankommen / erreichen', 201, 'قطار رسید.', 'Der Zug kam an.', 'Präsensstamm: رس. Auch: zu etwas gelangen, reif werden.', 5),
  ('شدن', 'shodan', 'werden / geschehen', 201, 'هوا سرد شد.', 'Das Wetter wurde kalt.', 'Präsensstamm: شو. Sehr wichtiges Voll- und Hilfsverb; viele zusammengesetzte Verben.', 5),
  ('کرد', 'kard', 'tat / machte; Kurd', 201, 'او کار کرد.', 'Er/sie arbeitete.', 'Präsensstamm: کن. Als Verbform von کردن erkennen; homonym mit Kurd.', 4),
  ('کردن', 'kardan', 'machen / tun', 201, 'این کار را کردم.', 'Ich habe diese Arbeit gemacht.', 'Präsensstamm: کن. Basis vieler zusammengesetzter Verben: فکر کردن، شروع کردن.', 5),
  ('کند', 'konad / kond', 'macht / langsam', 201, 'او کار می‌کند.', 'Er/sie arbeitet.', 'Präsensstamm: کن. Form von کردن oder Adjektiv کند=langsam.', 4),
  ('گرفتن', 'gereftan', 'nehmen / bekommen / greifen', 201, 'تصمیم گرفتم بروم.', 'Ich entschied mich zu gehen.', 'Präsensstamm: گیر. Sehr produktiv: تصمیم گرفتن، تماس گرفتن.', 5),
  ('گفتن', 'goftan', 'sagen / sprechen', 201, 'او گفت که می‌آید.', 'Er/sie sagte, dass er/sie kommt.', 'Präsensstamm: گوی. Basisverb für Rede und Berichten.', 5),
  ('یافتن', 'yâftan', 'finden', 201, 'راه‌حل را یافتیم.', 'Wir haben die Lösung gefunden.', 'Präsensstamm: یاب.', 4),
  -- L202
  ('آوردن', 'âvardan', 'bringen', 202, 'برایم یک لیوان آب بیاور.', 'Bring mir ein Glas Wasser.', 'Präsensstamm: آور.', 4),
  ('افزودن', 'afzudan', 'hinzufügen', 202, 'کمی نمک به غذا افزود.', 'Er fügte dem Essen etwas Salz hinzu.', 'Präsensstamm: افزا.', 4),
  ('بردن', 'bordan', 'tragen / bringen / nehmen', 202, 'این نامه را به پست ببر.', 'Bring diesen Brief zur Post.', 'Präsensstamm: بر.', 5),
  ('خواندن', 'khândan', 'lesen / studieren', 202, 'هر شب کتاب می‌خوانم.', 'Jeden Abend lese ich ein Buch.', 'Präsensstamm: خوان.', 4),
  ('دیدن', 'didan', 'sehen', 202, 'دیروز او را دیدم.', 'Gestern habe ich ihn gesehen.', 'Präsensstamm: بین.', 4),
  ('رساندن', 'resândan', 'überbringen / zustellen', 202, 'او ما را به خانه رساند.', 'Er hat uns nach Hause gebracht.', 'Präsensstamm: رسان.', 4),
  ('رفتن', 'raftan', 'gehen', 202, 'فردا به مدرسه می‌روم.', 'Morgen gehe ich zur Schule.', 'Präsensstamm: روب.', 5),
  ('زدن', 'zadan', 'schlagen / klopfen', 202, 'در زد و داخل شد.', 'Er klopfte und kam herein.', 'Präsensstamm: زن.', 3),
  ('ساختن', 'sâkhtan', 'bauen / herstellen', 202, 'آن‌ها خانه‌ای نو ساختند.', 'Sie haben ein neues Haus gebaut.', 'Präsensstamm: ساز.', 3),
  ('نمودن', 'nemudan', 'zeigen / tun', 202, 'او سعی نمود به ما کمک کند.', 'Er versuchte, uns zu helfen.', 'Präsensstamm: نمای.', 3),
  ('نوشتن', 'neveshtan', 'schreiben', 202, 'نامه‌ای به دوستم نوشتم.', 'Ich habe meinem Freund einen Brief geschrieben.', 'Präsensstamm: نویس.', 3),
  ('وارد', 'vâred', 'eintretend / importiert / hinein', 202, 'او وارد اتاق شد.', 'Er trat ins Zimmer ein.', NULL, 4),
  ('پرداختن', 'pardâkhtan', 'zahlen / sich befassen', 202, 'صورت‌حساب را پرداختم.', 'Ich habe die Rechnung bezahlt.', 'Präsensstamm: پرداز.', 4),
  ('گذاشتن', 'gozâshtan', 'legen / lassen', 202, 'کلید را روی میز گذاشتم.', 'Ich habe den Schlüssel auf den Tisch gelegt.', 'Präsensstamm: گذار.', 4),
  ('گذشتن', 'gozashtan', 'vorbeigehen / vergehen', 202, 'سال‌ها زود می‌گذرند.', 'Die Jahre vergehen schnell.', 'Präsensstamm: گذر.', 4),
  ('یافته', 'yâfte', 'gefunden / vorgefunden', 202, 'او شغل تازه‌ای یافته است.', 'Er hat eine neue Stelle gefunden.', NULL, 4),
  -- L203
  ('بایستن', 'bâyestan', 'müssen / sollen', 203, 'باید بروم.', 'Ich muss gehen.', 'Präsensstamm: بای. In moderner Umgangssprache oft باید statt Infinitiv.', 4),
  ('توانستن', 'tavânestan', 'können / fähig sein', 203, 'می‌توانم کمک کنم.', 'Ich kann helfen.', 'Präsensstamm: توان. Modalverb; gesprochen oft تونستن.', 5),
  ('شایستن', 'shâyastan', 'möglich sein / sich geziemen', 203, 'شایستن یعنی سزاوار بودن.', '„Schâyestan“ bedeutet „würdig sein“.', 'Präsensstamm: شای.', 3),
  -- L204
  ('ادامه دادن', 'edâme dâdan', 'fortsetzen', 204, 'به کارش ادامه داد.', 'Er setzte seine Arbeit fort.', 'Präsensstamm: ده.', 3),
  ('استفاده کردن', 'estefâde kardan', 'benutzen / verwenden', 204, 'از این روش استفاده می‌کنیم.', 'Wir benutzen diese Methode.', 'Präsensstamm: کن.', 3),
  ('انتخاب کردن', 'entekhâb kardan', 'wählen / auswählen', 204, 'او را به عنوان رئیس انتخاب کردند.', 'Sie wählten ihn zum Vorsitzenden.', 'Präsensstamm: کن.', 3),
  ('انجام دادن', 'anjâm dâdan', 'durchführen / erledigen', 204, 'کار را انجام دادم.', 'Ich habe die Arbeit erledigt.', 'Präsensstamm: ده.', 4),
  ('انجام شدن', 'anjâm shodan', 'erledigt werden / geschehen', 204, 'کار به‌موقع انجام شد.', 'Die Arbeit wurde rechtzeitig erledigt.', 'Präsensstamm: شو.', 3),
  ('خارج شدن', 'khârej shodan', 'hinausgehen / herauskommen', 204, 'از اتاق خارج شد.', 'Er ging aus dem Zimmer hinaus.', 'Präsensstamm: شو.', 3),
  ('دست دادن', 'dast dâdan', 'die Hand geben / verlieren', 204, 'با هم دست دادند.', 'Sie gaben sich die Hand.', 'Präsensstamm: ده.', 4),
  ('قرار بودن', 'gharâr budan', 'vorgesehen sein / sollen', 204, 'قرار بود ساعت پنج بیاید.', 'Er sollte um fünf kommen.', 'Präsensstamm: باش.', 3),
  ('قرار دادن', 'gharâr dâdan', 'platzieren / festlegen', 204, 'گلدان را کنار پنجره قرار داد.', 'Sie stellte die Vase ans Fenster.', 'Präsensstamm: ده.', 3),
  ('قرار داشتن', 'gharâr dâshtan', 'sich befinden / liegen', 204, 'خانه در مرکز شهر قرار دارد.', 'Das Haus befindet sich im Stadtzentrum.', 'Präsensstamm: دار.', 3),
  ('قرار گرفتن', 'gharâr gereftan', 'sich befinden / liegen', 204, 'خانه در شمال شهر قرار گرفته است.', 'Das Haus liegt im Norden der Stadt.', 'Präsensstamm: گیر.', 5),
  ('نشان دادن', 'neshân dâdan', 'zeigen', 204, 'راه را به من نشان داد.', 'Er zeigte mir den Weg.', 'Präsensstamm: ده.', 4),
  ('وجود داشتن', 'vojud dâshtan', 'existieren', 204, 'چنین چیزی وجود دارد.', 'So etwas existiert.', 'Präsensstamm: دار.', 4),
  ('پیدا کردن', 'peydâ kardan', 'finden', 204, 'کلید را پیدا کردم.', 'Ich habe den Schlüssel gefunden.', 'Präsensstamm: کن.', 4),
  -- L301
  ('آزادی', 'âzâdi', 'Freiheit', 301, NULL, NULL, NULL, 3),
  ('اختیار', 'ekhtiyâr', 'Befugnis / Verfügung', 301, 'این تصمیم در اختیار توست.', 'Diese Entscheidung liegt bei dir.', NULL, 4),
  ('امام', 'emâm', 'Imam', 301, NULL, NULL, 'religiöser Begriff', 3),
  ('انتخابات', 'entekhâbât', 'Wahlen', 301, NULL, NULL, NULL, 3),
  ('انقلاب', 'enghelâb', 'Revolution', 301, NULL, NULL, 'politischer Begriff', 3),
  ('جمهوری', 'jomhuri', 'Republik', 301, 'این کشور یک جمهوری است.', 'Dieses Land ist eine Republik.', NULL, 4),
  ('حاکم', 'hâkem', 'Herrscher / herrschend', 301, NULL, NULL, NULL, 3),
  ('حزب', 'hezb', 'Partei', 301, NULL, NULL, 'politischer Begriff', 3),
  ('حق', 'hagh', 'Recht', 301, 'تو حق داری.', 'Du hast recht.', NULL, 4),
  ('حقوق', 'hoghugh', 'Rechte / Gehalt', 301, NULL, NULL, NULL, 3),
  ('دستور', 'dastur', 'Befehl / Anweisung', 301, NULL, NULL, NULL, 3),
  ('دولت', 'dowlat', 'Regierung / Staat', 301, 'دولت قانون تازه‌ای تصویب کرد.', 'Die Regierung verabschiedete ein neues Gesetz.', NULL, 4),
  ('رأی', 'raɁy', 'Stimme / Votum', 301, NULL, NULL, NULL, 3),
  ('رئیس', 'ra''is', 'Leiter / Präsident / Chef', 301, 'رئیس امروز نیامد.', 'Der Chef ist heute nicht gekommen.', NULL, 4),
  ('سیاست', 'siyâsat', 'Politik / Strategie', 301, 'او به سیاست علاقه دارد.', 'Er interessiert sich für Politik.', NULL, 4),
  ('سیاسی', 'siyâsi', 'politisch', 301, 'این یک مسئله‌ی سیاسی است.', 'Das ist eine politische Frage.', NULL, 4),
  ('شورا', 'shurâ', 'Rat / Council', 301, 'شورای شهر جلسه داشت.', 'Der Stadtrat hatte eine Sitzung.', NULL, 5),
  ('قانون', 'ghânun', 'Gesetz', 301, 'باید قانون را رعایت کنیم.', 'Wir müssen das Gesetz beachten.', NULL, 4),
  ('قدرت', 'ghodrat', 'Macht / Stärke', 301, 'این کشور قدرت زیادی دارد.', 'Dieses Land hat große Macht.', NULL, 4),
  ('مجلس', 'majles', 'Parlament / Versammlung', 301, 'مجلس قانون را تصویب کرد.', 'Das Parlament verabschiedete das Gesetz.', NULL, 4),
  ('مقام', 'maghâm', 'Rang / Amt', 301, 'او به مقام بالایی رسید.', 'Er erreichte einen hohen Rang.', NULL, 4),
  ('ملت', 'mellat', 'Nation / Volk', 301, 'یک ملت بزرگ است.', 'Es ist eine große Nation.', NULL, 4),
  ('نظام', 'nezâm', 'System / Ordnung', 301, 'نظام آموزشی تغییر کرد.', 'Das Bildungssystem hat sich geändert.', NULL, 4),
  ('نماینده', 'namâyande', 'Vertreter / Abgeordneter', 301, 'او نماینده‌ی مردم است.', 'Er ist Vertreter des Volkes.', NULL, 4),
  ('هیئت', 'hey''at', 'Gremium / Delegation', 301, NULL, NULL, NULL, 3),
  ('وزارت', 'vezârat', 'Ministerium', 301, 'او در وزارت کار می‌کند.', 'Er arbeitet im Ministerium.', NULL, 4),
  ('وزیر', 'vazir', 'Minister', 301, 'وزیر سخنرانی کرد.', 'Der Minister hielt eine Rede.', NULL, 5),
  -- L302
  ('آقا', 'âghâ', 'Herr (Anrede)', 302, 'آقای محمدی اینجاست؟', 'Ist Herr Mohammadi hier?', 'Anrede / Eigenname', 5),
  ('استاد', 'ostâd', 'Professor / Meister', 302, NULL, NULL, NULL, 3),
  ('اسلام', 'eslâm', 'Islam', 302, 'اسلام در این منطقه گسترش یافت.', 'Der Islam breitete sich in dieser Region aus.', 'religiöser Begriff', 4),
  ('اسلامی', 'eslâmi', 'islamisch', 302, 'این یک هنر اسلامی است.', 'Das ist eine islamische Kunst.', NULL, 4),
  ('انسان', 'ensân', 'Mensch', 302, NULL, NULL, NULL, 3),
  ('تیم', 'tim', 'Team', 302, 'تیم ما برنده شد.', 'Unser Team hat gewonnen.', NULL, 5),
  ('جامعه', 'jâme''e', 'Gesellschaft', 302, 'جامعه در حال تغییر است.', 'Die Gesellschaft verändert sich.', NULL, 4),
  ('جمعیت', 'jam''iyyat', 'Bevölkerung / Menge', 302, NULL, NULL, NULL, 3),
  ('حسن', 'hasan', 'Hasan (Name) / Tugend', 302, 'حسن همسایه‌ی ماست.', 'Hasan ist unser Nachbar.', 'Eigenname', 4),
  ('خانواده', 'khânevâde', 'Familie', 302, 'خانواده‌ی بزرگی داریم.', 'Wir haben eine große Familie.', NULL, 4),
  ('دوست', 'dust', 'Freund', 302, NULL, NULL, NULL, 3),
  ('دکتر', 'doktor', 'Arzt / Doktor', 302, NULL, NULL, NULL, 3),
  ('دین', 'din', 'Religion', 302, NULL, NULL, 'religiöser Begriff', 3),
  ('زن', 'zan', 'Frau', 302, 'آن زن معلم است.', 'Diese Frau ist Lehrerin.', NULL, 4),
  ('زندگی', 'zendegi', 'Leben', 302, 'زندگی در شهر گران است.', 'Das Leben in der Stadt ist teuer.', NULL, 4),
  ('شاهد', 'shâhed', 'Zeuge', 302, NULL, NULL, NULL, 3),
  ('شهید', 'shahid', 'Märtyrer', 302, NULL, NULL, 'religiös/politischer Begriff', 3),
  ('صاحب', 'sâheb', 'Herr / Besitzer', 302, NULL, NULL, NULL, 3),
  ('عضو', 'ozv', 'Mitglied', 302, 'او عضو باشگاه است.', 'Er ist Mitglied des Klubs.', NULL, 4),
  ('علی', 'Ali', 'Ali', 302, 'علی دوست خوبی است.', 'Ali ist ein guter Freund.', NULL, 4),
  ('فرد', 'fard', 'Individuum / Einzelperson', 302, 'هر فرد حقوقی دارد.', 'Jedes Individuum hat Rechte.', NULL, 4),
  ('فرهنگ', 'farhang', 'Kultur', 302, NULL, NULL, NULL, 3),
  ('محمد', 'mohammad', 'Mohammad', 302, 'محمد فردا می‌آید.', 'Mohammad kommt morgen.', 'Eigenname (Person)', 4),
  ('مرد', 'mard', 'Mann', 302, NULL, NULL, NULL, 3),
  ('مردم', 'mardom', 'Menschen / Volk', 302, 'مردم آمدند.', 'Die Leute kamen.', 'Kollektiv; sehr häufig in Medien und Alltag.', 5),
  ('نفر', 'nafar', 'Person / Kopfzahl', 302, 'ده نفر در صف بودند.', 'Zehn Personen standen in der Schlange.', NULL, 4),
  ('کس', 'kas', 'jemand / Person', 302, 'کسی در خانه نیست.', 'Niemand ist zu Hause.', NULL, 5),
  ('کودک', 'kudak', 'Kind', 302, NULL, NULL, NULL, 3),
  ('گروه', 'goruh', 'Gruppe', 302, 'ما یک گروه کوچک هستیم.', 'Wir sind eine kleine Gruppe.', NULL, 5),
  -- L303
  ('اداره', 'edâre', 'Amt / Behörde', 303, NULL, NULL, NULL, 3),
  ('بازار', 'bâzâr', 'Markt / Basar', 303, NULL, NULL, NULL, 3),
  ('بانک', 'bânk', 'Bank', 303, NULL, NULL, NULL, 3),
  ('تأمین', 'ta''min', 'Sicherung / Bereitstellung', 303, NULL, NULL, NULL, 3),
  ('تولید', 'tovlid', 'Produktion', 303, 'تولید این کارخانه زیاد است.', 'Die Produktion dieser Fabrik ist hoch.', NULL, 4),
  ('خدمت', 'khedmat', 'Dienst', 303, 'او سال‌ها خدمت کرد.', 'Er hat jahrelang Dienst geleistet.', NULL, 4),
  ('دستگاه', 'dastgâh', 'Gerät / Apparat', 303, NULL, NULL, NULL, 3),
  ('دلار', 'dolâr', 'Dollar', 303, NULL, NULL, NULL, 3),
  ('سازمان', 'sâzmân', 'Organisation', 303, 'او در یک سازمان بزرگ کار می‌کند.', 'Er arbeitet in einer großen Organisation.', NULL, 4),
  ('سیستم', 'sistem', 'System', 303, NULL, NULL, NULL, 3),
  ('شرکت', 'sherkat', 'Firma / Teilnahme', 303, 'او در یک شرکت بزرگ کار می‌کند.', 'Er arbeitet in einer großen Firma.', NULL, 5),
  ('صنعت', 'san''at', 'Industrie', 303, 'صنعت خودرو مهم است.', 'Die Autoindustrie ist wichtig.', NULL, 4),
  ('فعالیت', 'fa''âliyat', 'Aktivität / Tätigkeit', 303, 'فعالیت ورزشی خوب است.', 'Sportliche Aktivität ist gut.', NULL, 4),
  ('نفت', 'naft', 'Erdöl', 303, NULL, NULL, NULL, 3),
  ('هزینه', 'hazine', 'Kosten', 303, NULL, NULL, NULL, 3),
  ('همکاری', 'hamkâri', 'Zusammenarbeit', 303, 'از همکاری شما ممنونم.', 'Ich danke für Ihre Zusammenarbeit.', NULL, 4),
  ('پرداخت', 'pardâkht', 'Zahlung / bezahlt', 303, NULL, NULL, NULL, 3),
  ('پول', 'pul', 'Geld', 303, NULL, NULL, NULL, 3),
  ('کار', 'kâr', 'Arbeit / Sache', 303, 'کار دارم.', 'Ich habe zu tun.', 'Sehr breit: Arbeit, Angelegenheit, Funktion.', 5),
  ('کنترل', 'kontrol', 'Kontrolle / Steuerung', 303, NULL, NULL, NULL, 3),
  -- L304
  ('آموزش', 'âmuzesh', 'Ausbildung / Unterricht', 304, NULL, NULL, NULL, 3),
  ('اندیشه', 'andishe', 'Gedanke / Idee', 304, 'اندیشه‌ی خوبی است.', 'Das ist eine gute Idee.', NULL, 4),
  ('تحقیق', 'tahghigh', 'Forschung / Recherche', 304, NULL, NULL, NULL, 3),
  ('حوزه', 'hovze', 'Bereich / Bezirk', 304, NULL, NULL, NULL, 3),
  ('دانشگاه', 'dâneshgâh', 'Universität', 304, NULL, NULL, NULL, 3),
  ('رشته', 'reshte', 'Fach / Disziplin', 304, NULL, NULL, NULL, 3),
  ('علم', 'elm', 'Wissenschaft', 304, NULL, NULL, NULL, 3),
  ('فکر', 'fekr', 'Gedanke / Denken', 304, NULL, NULL, NULL, 3),
  ('مدرسه', 'madrese', 'Schule', 304, NULL, NULL, NULL, 3),
  ('کتاب', 'ketâb', 'Buch', 304, 'این کتاب را خواندم.', 'Dieses Buch habe ich gelesen.', NULL, 4),
  -- L305
  ('ارتباط', 'ertebât', 'Verbindung / Kontakt', 305, NULL, NULL, NULL, 3),
  ('اشاره', 'eshâre', 'Hinweis / Andeutung', 305, 'با دست به در اشاره کرد.', 'Er deutete mit der Hand auf die Tür.', NULL, 4),
  ('اطلاع', 'ettelâ''', 'Information / Kenntnis', 305, 'اطلاع تازه‌ای ندارم.', 'Ich habe keine neue Information.', NULL, 4),
  ('اعلام', 'e''lâm', 'Bekanntgabe / Ankündigung', 305, 'نتایج فردا اعلام می‌شود.', 'Die Ergebnisse werden morgen bekannt gegeben.', NULL, 4),
  ('انگلیسی', 'engelisi', 'Englisch / englisch', 305, NULL, NULL, 'Sprach-/Ländername', 3),
  ('بحث', 'bahs', 'Diskussion / Debatte', 305, 'بحث جالبی بود.', 'Es war eine interessante Diskussion.', NULL, 4),
  ('بیان', 'bayân', 'Ausdruck / Äußerung', 305, NULL, NULL, NULL, 3),
  ('تصویر', 'tasvir', 'Bild / Abbildung', 305, NULL, NULL, NULL, 3),
  ('جلسه', 'jalase', 'Sitzung / Treffen', 305, NULL, NULL, NULL, 3),
  ('جمله', 'jomle', 'Satz / Summe', 305, 'این جمله را ترجمه کن.', 'Übersetze diesen Satz.', NULL, 4),
  ('خبر', 'khabar', 'Nachricht', 305, 'خبر خوبی دارم.', 'Ich habe eine gute Nachricht.', NULL, 4),
  ('خط', 'khatt', 'Linie / Schrift', 305, 'یک خط راست بکش.', 'Zieh eine gerade Linie.', NULL, 4),
  ('دیدار', 'didâr', 'Treffen / Besuch', 305, NULL, NULL, NULL, 3),
  ('روزنامه', 'ruznâme', 'Zeitung', 305, 'هر صبح روزنامه می‌خوانم.', 'Jeden Morgen lese ich die Zeitung.', NULL, 4),
  ('زبان', 'zabân', 'Sprache / Zunge', 305, NULL, NULL, NULL, 3),
  ('سؤال', 'so''âl', 'Frage', 305, NULL, NULL, NULL, 3),
  ('سخن', 'sokhan', 'Rede / Wort', 305, NULL, NULL, NULL, 3),
  ('شبکه', 'shabake', 'Netz / Netzwerk', 305, NULL, NULL, NULL, 3),
  ('عنوان', 'onvân', 'Titel / Überschrift / Bezeichnung', 305, 'عنوان این کتاب چیست؟', 'Wie lautet der Titel dieses Buches?', NULL, 5),
  ('فیلم', 'film', 'Film', 305, NULL, NULL, NULL, 3),
  ('معنا', 'ma''nâ', 'Bedeutung / Sinn', 305, NULL, NULL, NULL, 3),
  ('مقاله', 'maghâle', 'Artikel / Aufsatz', 305, NULL, NULL, NULL, 3),
  ('منبع', 'manba''', 'Quelle', 305, 'این آب از یک منبع طبیعی است.', 'Dieses Wasser stammt aus einer natürlichen Quelle.', NULL, 4),
  ('منظور', 'manzur', 'Absicht / Zweck', 305, NULL, NULL, NULL, 3),
  ('موضوع', 'movzu''', 'Thema / Gegenstand', 305, 'موضوع جلسه چیست؟', 'Was ist das Thema der Sitzung?', NULL, 4),
  ('نام', 'nâm', 'Name', 305, 'نام تو چیست؟', 'Wie ist dein Name?', NULL, 5),
  ('نامه', 'nâme', 'Brief', 305, NULL, NULL, NULL, 3),
  ('نشان', 'neshân', 'Zeichen / Abzeichen', 305, NULL, NULL, NULL, 3),
  ('نظر', 'nazar', 'Meinung / Sicht', 305, 'نظر شما چیست؟', 'Was ist Ihre/deine Meinung?', 'Sehr wichtig in نظر داشتن/به نظر.', 5),
  ('نقل', 'naghl', 'Übertragung / Zitat', 305, NULL, NULL, NULL, 3),
  ('پاسخ', 'pâsokh', 'Antwort', 305, NULL, NULL, NULL, 3),
  ('چاپ', 'châp', 'Druck (Print) / Auflage', 305, NULL, NULL, NULL, 3),
  ('گزارش', 'gozâresh', 'Bericht', 305, 'گزارش را به رئیس دادم.', 'Ich habe den Bericht dem Chef gegeben.', NULL, 4),
  ('گفته', 'gofte', 'Aussage / gesagt', 305, 'گفته‌ی او درست بود.', 'Seine Aussage war richtig.', NULL, 4),
  ('گفت‌وگو', 'goftogu', 'Gespräch', 305, 'گفت‌وگوی خوبی داشتیم.', 'Wir hatten ein gutes Gespräch.', NULL, 4),
  -- L306
  ('آمریکا', 'âmrikâ', 'Amerika / USA', 306, 'او در آمریکا زندگی می‌کند.', 'Er lebt in Amerika.', NULL, 4),
  ('اروپا', 'orupâ', 'Europa', 306, NULL, NULL, 'Eigenname (Kontinent)', 3),
  ('استان', 'ostân', 'Provinz', 306, NULL, NULL, NULL, 3),
  ('افغانستان', 'afghânestân', 'Afghanistan', 306, NULL, NULL, 'Eigenname (Land)', 3),
  ('ایران', 'Irân', 'Iran', 306, 'من ایران را دوست دارم.', 'Ich mag Iran.', 'Eigenname; relevant für Medien/Alltag.', 4),
  ('بالا', 'bâlâ', 'oben / hoch', 306, 'کتاب روی طبقه‌ی بالا است.', 'Das Buch ist im oberen Regal.', NULL, 4),
  ('تهران', 'tehrân', 'Teheran', 306, 'تهران پایتخت ایران است.', 'Teheran ist die Hauptstadt des Iran.', 'Eigenname (Ort)', 5),
  ('جا', 'jâ', 'Platz / Stelle', 306, 'اینجا جای خوبی است.', 'Hier ist ein guter Platz.', NULL, 4),
  ('جهان', 'jahân', 'Welt', 306, 'او دور جهان سفر کرد.', 'Er reiste um die Welt.', NULL, 4),
  ('خارج', 'khârej', 'außen / Ausland', 306, 'او در خارج درس می‌خواند.', 'Er studiert im Ausland.', NULL, 4),
  ('خانه', 'khâne', 'Haus', 306, NULL, NULL, NULL, 3),
  ('دفتر', 'daftar', 'Büro / Heft', 306, NULL, NULL, NULL, 3),
  ('دنبال', 'dombâl', 'Verfolgung / hinter', 306, 'دنبال کلیدم می‌گردم.', 'Ich suche nach meinem Schlüssel.', NULL, 4),
  ('دنیا', 'donyâ', 'Welt', 306, 'دنیا خیلی بزرگ است.', 'Die Welt ist sehr groß.', NULL, 4),
  ('راه', 'râh', 'Weg / Straße / Methode', 306, 'راه حل چیست؟', 'Was ist die Lösung?', 'Konkreter und abstrakter Weg.', 5),
  ('زمین', 'zamin', 'Boden / Erde', 306, 'توپ روی زمین افتاد.', 'Der Ball fiel auf den Boden.', NULL, 4),
  ('سفر', 'safar', 'Reise', 306, NULL, NULL, NULL, 3),
  ('سمت', 'samt', 'Seite / Position', 306, 'به سمت چپ برو.', 'Geh nach links.', NULL, 4),
  ('سو', 'su', 'Seite / Richtung', 306, 'از هر سو صدا می‌آمد.', 'Von allen Seiten kamen Geräusche.', NULL, 4),
  ('شهر', 'shahr', 'Stadt', 306, 'تهران شهر بزرگی است.', 'Teheran ist eine große Stadt.', 'Zentraler Ortsbegriff.', 5),
  ('طرف', 'taraf', 'Seite', 306, 'از این طرف بیا.', 'Komm von dieser Seite.', NULL, 4),
  ('عرصه', 'arse', 'Bereich / Arena', 306, NULL, NULL, NULL, 3),
  ('فرانسه', 'farânse', 'Frankreich / französisch', 306, NULL, NULL, 'Eigenname (Land)', 3),
  ('فضا', 'fazâ', 'Raum / Atmosphäre', 306, NULL, NULL, NULL, 3),
  ('محل', 'mahal', 'Ort / Stelle', 306, NULL, NULL, NULL, 3),
  ('مرکز', 'markaz', 'Zentrum', 306, 'مغازه در مرکز شهر است.', 'Der Laden ist im Stadtzentrum.', NULL, 4),
  ('مسیر', 'masir', 'Weg / Route', 306, NULL, NULL, NULL, 3),
  ('منطقه', 'mantaqe', 'Region / Gebiet', 306, 'این منطقه خیلی سرسبز است.', 'Diese Region ist sehr grün.', NULL, 4),
  ('میدان', 'meydân', 'Platz / Feld', 306, NULL, NULL, NULL, 3),
  ('نزدیک', 'nazdik', 'nah / nahe bei', 306, 'خانه‌ام نزدیک ایستگاه است.', 'Mein Haus ist nahe der Station.', NULL, 5),
  ('چین', 'chin', 'China', 306, NULL, NULL, 'Eigenname (Land)', 3),
  ('کشور', 'keshvar', 'Land / Staat', 306, 'کشور بزرگی است.', 'Es ist ein großes Land.', 'Häufig in Nachrichten und Politik.', 5),
  -- L307
  ('امنیت', 'amniyat', 'Sicherheit', 307, NULL, NULL, NULL, 3),
  ('جنگ', 'jang', 'Krieg', 307, 'جنگ سال‌ها طول کشید.', 'Der Krieg dauerte Jahre.', NULL, 4),
  ('حادثه', 'hâdese', 'Vorfall / Unfall', 307, NULL, NULL, NULL, 3),
  ('حفظ', 'hefz', 'Bewahrung / Erhalt', 307, NULL, NULL, NULL, 3),
  ('حمایت', 'hemâyat', 'Unterstützung / Schutz', 307, NULL, NULL, NULL, 3),
  ('خطر', 'khatar', 'Gefahr / Risiko', 307, NULL, NULL, NULL, 3),
  ('دفاع', 'defâ''', 'Verteidigung', 307, NULL, NULL, NULL, 3),
  ('فشار', 'feshâr', 'Druck', 307, NULL, NULL, NULL, 3),
  ('مانع', 'mâne''', 'Hindernis', 307, NULL, NULL, NULL, 3),
  ('مرگ', 'marg', 'Tod', 307, NULL, NULL, NULL, 3),
  ('نیرو', 'niru', 'Kraft / Truppe', 307, 'دیگر نیرو ندارم.', 'Ich habe keine Kraft mehr.', NULL, 4),
  -- L308
  ('اثر', 'asar', 'Spur / Wirkung / Werk', 308, 'این دارو اثر خوبی دارد.', 'Dieses Medikament hat eine gute Wirkung.', NULL, 4),
  ('اساس', 'asâs', 'Grundlage / Basis', 308, 'این کار اساس درستی دارد.', 'Diese Sache hat eine solide Grundlage.', NULL, 4),
  ('امکان', 'emkân', 'Möglichkeit', 308, NULL, NULL, NULL, 3),
  ('باعث', 'bâ''es', 'Ursache / Anlass', 308, 'گرما باعث خستگی می‌شود.', 'Hitze verursacht Müdigkeit.', NULL, 4),
  ('تأثیر', 'ta''sir', 'Einfluss / Wirkung', 308, 'موسیقی تأثیر زیادی دارد.', 'Musik hat großen Einfluss.', NULL, 4),
  ('توجه', 'tavajjoh', 'Aufmerksamkeit', 308, 'لطفاً به من توجه کن.', 'Bitte schenk mir Aufmerksamkeit.', NULL, 5),
  ('خاطر', 'khâter', 'Gedanke / um … willen', 308, 'به خاطر تو ماندم.', 'Deinetwegen bin ich geblieben.', NULL, 4),
  ('دلیل', 'dalil', 'Grund', 308, 'دلیل تأخیرت چیست؟', 'Was ist der Grund für deine Verspätung?', NULL, 5),
  ('رابطه', 'râbete', 'Beziehung / Verbindung', 308, 'رابطه‌ی خوبی با هم داریم.', 'Wir haben eine gute Beziehung zueinander.', NULL, 4),
  ('زمینه', 'zamine', 'Hintergrund / Feld / Grundlage', 308, 'در این زمینه تجربه دارم.', 'Auf diesem Gebiet habe ich Erfahrung.', NULL, 4),
  ('شرط', 'shart', 'Bedingung', 308, 'به یک شرط می‌آیم.', 'Ich komme unter einer Bedingung.', NULL, 4),
  ('عامل', 'âmel', 'Faktor / Akteur', 308, 'خواب کم عامل خستگی است.', 'Wenig Schlaf ist ein Faktor für Müdigkeit.', NULL, 4),
  ('علت', 'ellat', 'Grund / Ursache', 308, NULL, NULL, NULL, 3),
  ('فرصت', 'forsat', 'Gelegenheit / Chance', 308, NULL, NULL, NULL, 3),
  ('موجب', 'mujeb', 'Ursache / Grund', 308, NULL, NULL, NULL, 3),
  ('نتیجه', 'natije', 'Ergebnis / Folge', 308, 'نتیجه‌ی امتحان خوب بود.', 'Das Ergebnis der Prüfung war gut.', NULL, 4),
  ('نسبت', 'nesbat', 'Verhältnis / Bezug', 308, 'نسبت به دیروز بهتر است.', 'Im Vergleich zu gestern ist es besser.', NULL, 4),
  ('نقش', 'naghsh', 'Rolle', 308, 'او نقش مهمی دارد.', 'Er spielt eine wichtige Rolle.', NULL, 5),
  ('نیاز', 'niyâz', 'Bedarf / Bedürfnis', 308, 'به کمک تو نیاز دارم.', 'Ich brauche deine Hilfe.', NULL, 4),
  ('هدف', 'hadaf', 'Ziel', 308, 'هدف من یادگیری فارسی است.', 'Mein Ziel ist es, Persisch zu lernen.', NULL, 4),
  ('پی', 'pey', 'Fundament / Folge', 308, NULL, NULL, NULL, 3),
  -- L309
  ('ارزش', 'arzesh', 'Wert', 309, 'این انگشتر ارزش زیادی دارد.', 'Dieser Ring hat einen hohen Wert.', NULL, 4),
  ('اصل', 'asl', 'Prinzip / Ursprung', 309, 'اصل کار صداقت است.', 'Das Grundprinzip ist Ehrlichkeit.', NULL, 4),
  ('امر', 'amr', 'Angelegenheit / Sache / Befehl', 309, 'این امر مهمی است.', 'Das ist eine wichtige Angelegenheit.', NULL, 5),
  ('اهمیت', 'âhammiyyat', 'Bedeutung / Wichtigkeit', 309, 'این موضوع اهمیت دارد.', 'Dieses Thema ist wichtig.', NULL, 4),
  ('بخش', 'bakhsh', 'Teil / Abschnitt / Bereich', 309, 'این بخش از کتاب سخت است.', 'Dieser Teil des Buches ist schwer.', NULL, 5),
  ('بزرگی', 'bozorgi', 'Größe / Ausmaß', 309, 'بزرگی این شهر مرا شگفت‌زده کرد.', 'Die Größe dieser Stadt erstaunte mich.', NULL, 4),
  ('تعداد', 'te''dâd', 'Anzahl / Anzahl', 309, 'تعداد دانش‌آموزان زیاد است.', 'Die Anzahl der Schüler ist hoch.', NULL, 4),
  ('جمع', 'jam''', 'Summe / Mehrzahl', 309, NULL, NULL, NULL, 3),
  ('حد', 'hadd', 'Grenze / Maß', 309, NULL, NULL, NULL, 3),
  ('حدود', 'hodud', 'Grenzen / etwa', 309, 'حدود صد نفر آمدند.', 'Etwa hundert Leute kamen.', NULL, 5),
  ('حقیقت', 'haghighat', 'Wahrheit / Wirklichkeit', 309, NULL, NULL, NULL, 3),
  ('درصد', 'darsad', 'Prozent', 309, 'ده درصد تخفیف گرفتم.', 'Ich habe zehn Prozent Rabatt bekommen.', NULL, 4),
  ('سطح', 'sath', 'Ebene / Niveau', 309, NULL, NULL, NULL, 3),
  ('شدت', 'sheddat', 'Intensität / Heftigkeit', 309, NULL, NULL, NULL, 3),
  ('شکل', 'shekl', 'Form / Gestalt', 309, 'این میز شکل گردی دارد.', 'Dieser Tisch hat eine runde Form.', NULL, 4),
  ('صورت', 'surat', 'Gesicht / Form / Weise', 309, 'به صورت رسمی', 'auf offizielle Weise', 'In festen Wendungen: به صورتِ = in Form von/als.', 4),
  ('طور', 'towr', 'Art / Weise', 309, 'این طور بهتر است.', 'So ist es besser.', NULL, 5),
  ('طول', 'tul', 'Länge', 309, NULL, NULL, NULL, 3),
  ('قرار', 'gharâr', 'Vereinbarung / Lage / Plan', 309, 'فردا با دکتر قرار دارم.', 'Morgen habe ich einen Termin beim Arzt.', NULL, 5),
  ('ماده', 'mâde', 'Material / Substanz / weiblich', 309, NULL, NULL, NULL, 3),
  ('مورد', 'mowred', 'Fall / Gegenstand / betreffend', 309, 'در این مورد بعداً حرف می‌زنیم.', 'Über diesen Punkt sprechen wir später.', NULL, 5),
  ('میزان', 'mizân', 'Maß / Ausmaß', 309, 'میزان بارش کم بود.', 'Die Niederschlagsmenge war gering.', NULL, 4),
  ('نوع', 'nov''', 'Art / Typ', 309, 'چه نوع موسیقی دوست داری؟', 'Welche Art Musik magst du?', NULL, 4),
  ('واحد', 'vâhed', 'Einheit', 309, NULL, NULL, NULL, 3),
  ('واقعیت', 'vâghe''iyyat', 'Wirklichkeit / Realität', 309, NULL, NULL, NULL, 3),
  ('وجود', 'vojood', 'Existenz / Vorhandensein', 309, 'مشکلی وجود ندارد.', 'Es gibt kein Problem.', NULL, 5),
  ('وضع', 'vaz''', 'Lage / Zustand', 309, NULL, NULL, NULL, 3),
  ('وضعیت', 'vaz''iyyat', 'Situation / Lage', 309, NULL, NULL, NULL, 3),
  ('چیز', 'chiz', 'Ding / Sache', 309, NULL, NULL, NULL, 3),
  ('کل', 'kol', 'Ganzes / gesamt', 309, NULL, NULL, NULL, 3),
  ('گونه', 'gune', 'Art / Sorte', 309, 'این گونه گل کمیاب است.', 'Diese Blumenart ist selten.', NULL, 4),
  -- L310
  ('اجرا', 'ejrâ', 'Ausführung / Umsetzung', 310, 'اجرای کنسرت عالی بود.', 'Die Aufführung des Konzerts war großartig.', NULL, 4),
  ('ادامه', 'edâme', 'Fortsetzung', 310, NULL, NULL, NULL, 3),
  ('ارائه', 'erâ''e', 'Darbietung / Vorlage', 310, 'ارائه‌ی او عالی بود.', 'Seine Präsentation war ausgezeichnet.', NULL, 4),
  ('استفاده', 'estefâde', 'Verwendung / Gebrauch', 310, 'استفاده از تلفن اینجا ممنوع است.', 'Der Gebrauch des Telefons ist hier verboten.', NULL, 5),
  ('اصلاح', 'eslâh', 'Korrektur / Reform', 310, NULL, NULL, NULL, 3),
  ('افزایش', 'afzâyesh', 'Zunahme / Erhöhung', 310, 'قیمت‌ها افزایش یافت.', 'Die Preise sind gestiegen.', NULL, 4),
  ('اقدام', 'eghdâm', 'Maßnahme / Schritt', 310, 'اقدام لازم انجام شد.', 'Die nötige Maßnahme wurde ergriffen.', NULL, 4),
  ('امید', 'omid', 'Hoffnung', 310, NULL, NULL, NULL, 3),
  ('انتخاب', 'entekhâb', 'Auswahl / Wahl', 310, 'انتخاب با توست.', 'Die Wahl liegt bei dir.', NULL, 4),
  ('انتظار', 'entezâr', 'Erwartung / Warten', 310, NULL, NULL, NULL, 3),
  ('انتقال', 'enteghâl', 'Übertragung / Transfer', 310, NULL, NULL, NULL, 3),
  ('انجام', 'anjâm', 'Durchführung / Ausführung', 310, 'انجام این کار وقت می‌برد.', 'Die Durchführung dieser Arbeit braucht Zeit.', NULL, 4),
  ('ایجاد', 'ijâd', 'Schaffung / Erzeugung', 310, 'این کار شغل ایجاد می‌کند.', 'Diese Maßnahme schafft Arbeitsplätze.', NULL, 5),
  ('بازی', 'bâzi', 'Spiel', 310, 'بازی فوتبال شروع شد.', 'Das Fußballspiel hat begonnen.', NULL, 4),
  ('بررسی', 'barresi', 'Untersuchung / Prüfung', 310, 'مدارک را بررسی کردیم.', 'Wir haben die Unterlagen geprüft.', NULL, 4),
  ('برنامه', 'barnâme', 'Programm / Plan', 310, 'برنامه‌ی امروز چیست؟', 'Was ist das Programm für heute?', NULL, 5),
  ('تأکید', 'ta''kid', 'Betonung / Nachdruck', 310, NULL, NULL, NULL, 3),
  ('ترتیب', 'tartib', 'Reihenfolge / Ordnung', 310, NULL, NULL, NULL, 3),
  ('تشکیل', 'tashkil', 'Bildung / Gründung', 310, 'جلسه تشکیل شد.', 'Die Sitzung kam zustande.', NULL, 4),
  ('تغییر', 'taghyir', 'Veränderung', 310, 'تغییر بزرگی لازم است.', 'Eine große Veränderung ist nötig.', NULL, 4),
  ('تلاش', 'talâsh', 'Anstrengung / Bemühung', 310, NULL, NULL, NULL, 3),
  ('توسعه', 'tovse''e', 'Entwicklung / Ausbau', 310, 'توسعه‌ی شهر ادامه دارد.', 'Die Entwicklung der Stadt geht weiter.', NULL, 4),
  ('جریان', 'jarayân', 'Strömung / Vorgang', 310, NULL, NULL, NULL, 3),
  ('حرکت', 'harekat', 'Bewegung', 310, 'قطار در حال حرکت است.', 'Der Zug ist in Bewegung.', NULL, 5),
  ('حضور', 'hozur', 'Anwesenheit / Präsenz', 310, 'حضور شما باعث افتخار است.', 'Ihre Anwesenheit ist eine Ehre.', NULL, 4),
  ('خواست', 'khâst', 'Wunsch / wollte', 310, NULL, NULL, NULL, 3),
  ('رشد', 'roshd', 'Wachstum', 310, 'رشد اقتصادی کند است.', 'Das Wirtschaftswachstum ist langsam.', NULL, 4),
  ('روش', 'ravesh', 'Methode / Vorgehen', 310, NULL, NULL, NULL, 3),
  ('روند', 'ravand', 'Prozess / Verlauf', 310, NULL, NULL, NULL, 3),
  ('ساخت', 'sâkht', 'Bau / Herstellung', 310, 'ساخت این پل دو سال طول کشید.', 'Der Bau dieser Brücke dauerte zwei Jahre.', NULL, 4),
  ('سعی', 'sa''y', 'Versuch / Mühe', 310, NULL, NULL, NULL, 3),
  ('طرح', 'tarh', 'Entwurf / Plan', 310, 'طرح تازه‌ای داریم.', 'Wir haben einen neuen Plan.', NULL, 5),
  ('طریق', 'tarigh', 'Weg / Methode', 310, 'از طریق ایمیل خبر بده.', 'Gib per E-Mail Bescheid.', NULL, 4),
  ('عمل', 'amal', 'Handlung / Tat', 310, 'به عمل خود فکر کن.', 'Denk über deine Tat nach.', NULL, 4),
  ('غیر', 'gheyr', 'Nicht- / andere', 310, 'غیر از این راهی نیست.', 'Außer diesem gibt es keinen Weg.', NULL, 4),
  ('فوتبال', 'futbâl', 'Fußball', 310, NULL, NULL, NULL, 3),
  ('مسئله', 'mas''ale', 'Problem / Frage / Angelegenheit', 310, 'این مسئله را حل کردیم.', 'Wir haben dieses Problem gelöst.', NULL, 5),
  ('مسابقه', 'mosâbeghe', 'Wettbewerb / Wettkampf', 310, NULL, NULL, NULL, 3),
  ('مشکل', 'moshkel', 'Problem / schwierig', 310, 'مشکلی پیش آمد.', 'Ein Problem ist aufgetreten.', NULL, 4),
  ('نقطه', 'noghte', 'Punkt', 310, 'این نقطه را روی نقشه پیدا کن.', 'Finde diesen Punkt auf der Karte.', NULL, 4),
  ('پیشنهاد', 'pishnehâd', 'Vorschlag', 310, NULL, NULL, NULL, 3),
  ('کاهش', 'kâhesh', 'Verringerung', 310, 'کاهش قیمت‌ها خوب است.', 'Die Senkung der Preise ist gut.', NULL, 4),
  ('کمک', 'komak', 'Hilfe', 310, 'به کمکت احتیاج دارم.', 'Ich brauche deine Hilfe.', NULL, 4),
  ('گل', 'gol', 'Blume / Tor (Sport)', 310, NULL, NULL, NULL, 3),
  -- L311
  ('آب', 'âb', 'Wasser', 311, 'یک لیوان آب می‌خواهم.', 'Ich möchte ein Glas Wasser.', NULL, 4),
  ('تن', 'tan', 'Körper / Tonne', 311, 'تنش از سرما می‌لرزید.', 'Sein Körper zitterte vor Kälte.', NULL, 4),
  ('دست', 'dast', 'Hand', 311, 'دستم درد می‌کند.', 'Meine Hand tut weh.', NULL, 5),
  ('دیده', 'dide', 'Auge / gesehen', 311, 'او را قبلاً ندیده بودم.', 'Ich hatte ihn vorher nicht gesehen.', NULL, 4),
  ('سر', 'sar', 'Kopf / Spitze', 311, 'سرم درد می‌کند.', 'Mein Kopf tut weh.', NULL, 4),
  ('هوا', 'havâ', 'Luft / Wetter', 311, NULL, NULL, NULL, 3),
  -- L312
  ('آزاد', 'âzâd', 'frei', 312, 'امروز وقت آزاد دارم.', 'Heute habe ich freie Zeit.', NULL, 4),
  ('اصلی', 'asli', 'haupt- / wesentlich', 312, 'دلیل اصلی این بود.', 'Der Hauptgrund war dieser.', NULL, 4),
  ('اقتصادی', 'eghtesâdi', 'wirtschaftlich', 312, 'وضع اقتصادی بهتر شده است.', 'Die wirtschaftliche Lage hat sich verbessert.', NULL, 5),
  ('ایرانی', 'irâni', 'iranisch', 312, 'غذای ایرانی خوشمزه است.', 'Iranisches Essen ist lecker.', NULL, 4),
  ('برابر', 'barâbar', 'gleich / gegenüber', 312, 'دو نیمه برابر است.', 'Die zwei Hälften sind gleich.', NULL, 4),
  ('بزرگ', 'bozorg', 'groß / wichtig', 312, 'شهر بزرگی است.', 'Es ist eine große Stadt.', 'Auch metaphorisch: wichtig/bedeutend.', 5),
  ('بهتر', 'behtar', 'besser', 312, 'امروز حالم بهتر است.', 'Heute geht es mir besser.', NULL, 4),
  ('جدید', 'jadid', 'neu', 312, 'این کفش‌ها جدید هستند.', 'Diese Schuhe sind neu.', NULL, 4),
  ('جهانی', 'jahâni', 'global / weltweit', 312, 'این یک مشکل جهانی است.', 'Das ist ein globales Problem.', NULL, 4),
  ('جوان', 'javân', 'jung', 312, 'او مرد جوانی است.', 'Er ist ein junger Mann.', NULL, 5),
  ('حاضر', 'hâzer', 'anwesend / bereit', 312, 'همه در جلسه حاضر بودند.', 'Alle waren bei der Sitzung anwesend.', NULL, 4),
  ('خارجی', 'khâreji', 'ausländisch / fremd', 312, 'او یک زبان خارجی بلد است.', 'Er kann eine Fremdsprache.', NULL, 4),
  ('زیادی', 'ziyâdi', 'übermäßig / zu viel', 312, 'قند زیادی خوردی.', 'Du hast zu viel Zucker gegessen.', NULL, 4),
  ('مختلف', 'mokhtalef', 'verschieden / unterschiedlich', 312, 'رنگ‌های مختلفی دارد.', 'Es hat verschiedene Farben.', NULL, 4),
  ('مسئول', 'mas''ul', 'verantwortlich / zuständig', 312, 'چه کسی مسئول است؟', 'Wer ist verantwortlich?', NULL, 4),
  ('ملی', 'melli', 'national', 312, 'امروز جشن ملی است.', 'Heute ist Nationalfeiertag.', NULL, 5),
  ('ممکن', 'momken', 'möglich', 312, 'این کار ممکن است.', 'Diese Sache ist möglich.', NULL, 4),
  ('مهم', 'mohem', 'wichtig', 312, 'این موضوع مهم است.', 'Dieses Thema ist wichtig.', 'Sehr häufig, auch substantivisch.', 5),
  ('موفق', 'movaffagh', 'erfolgreich', 312, 'در امتحان موفق شدم.', 'Ich war in der Prüfung erfolgreich.', NULL, 4),
  ('همراه', 'hamrâh', 'begleitend / zusammen mit', 312, 'همراه دوستم آمدم.', 'Ich kam zusammen mit meinem Freund.', NULL, 4),
  ('ویژه', 'vizhe', 'besonders / speziell', 312, 'این روز ویژه‌ای است.', 'Das ist ein besonderer Tag.', NULL, 4),
  ('کامل', 'kâmel', 'vollständig', 312, 'کار را کامل انجام بده.', 'Erledige die Arbeit vollständig.', NULL, 4),
  -- L313
  ('اجتماعی', 'ejtemâ''i', 'sozial', 313, NULL, NULL, NULL, 3),
  ('اخیر', 'akhir', 'jüngst / kürzlich', 313, 'در روزهای اخیر سرد بوده است.', 'In den letzten Tagen war es kalt.', NULL, 4),
  ('الزم', 'lâzem', 'nötig / erforderlich', 313, NULL, NULL, NULL, 3),
  ('انسانی', 'ensâni', 'menschlich', 313, NULL, NULL, NULL, 3),
  ('برگزار', 'bargozâr', 'abgehalten / veranstaltet', 313, 'جشن دیشب برگزار شد.', 'Das Fest fand gestern Abend statt.', NULL, 4),
  ('جدی', 'jeddi', 'ernst', 313, NULL, NULL, NULL, 3),
  ('خاص', 'khâss', 'speziell / eigen', 313, NULL, NULL, NULL, 3),
  ('داخلی', 'dâkheli', 'intern / inländisch', 313, NULL, NULL, NULL, 3),
  ('دور', 'dovr', 'fern / Runde', 313, 'شهر آن‌ها دور است.', 'Ihre Stadt ist weit weg.', NULL, 4),
  ('زمانی', 'zamâni', 'zeitlich', 313, NULL, NULL, NULL, 3),
  ('علمی', 'elmi', 'wissenschaftlich', 313, NULL, NULL, NULL, 3),
  ('عمومی', 'omumi', 'öffentlich / allgemein', 313, NULL, NULL, NULL, 3),
  ('فرهنگی', 'farhangi', 'kulturell', 313, NULL, NULL, NULL, 3),
  ('قابل', 'ghâbel', 'fähig / verfügbar', 313, 'این آب قابل نوشیدن است.', 'Dieses Wasser ist trinkbar.', NULL, 4),
  ('مرکزی', 'markazi', 'zentral', 313, NULL, NULL, NULL, 3),
  ('مشخص', 'moshakhkhas', 'bestimmt / festgelegt', 313, NULL, NULL, NULL, 3),
  ('مطرح', 'matrah', 'viel diskutiert / aufgeworfen', 313, NULL, NULL, NULL, 3),
  ('مناسب', 'monâseb', 'passend / geeignet', 313, NULL, NULL, NULL, 3),
  ('موافق', 'movâfegh', 'einverstanden', 313, NULL, NULL, NULL, 3),
  ('کاری', 'kâri', 'arbeits- / tätig', 313, NULL, NULL, NULL, 3),
  ('کلی', 'kolli', 'allgemein / gesamt', 313, NULL, NULL, NULL, 3),
  ('کوتاه', 'kutâh', 'kurz', 313, NULL, NULL, NULL, 3),
  -- L314
  ('آماده', 'âmâde', 'bereit', 314, NULL, NULL, NULL, 3),
  ('آمریکایی', 'âmrikâyi', 'amerikanisch', 314, NULL, NULL, NULL, 3),
  ('دولتی', 'dovlati', 'staatlich / Regierungs-', 314, NULL, NULL, NULL, 3),
  ('دینی', 'dini', 'religiös', 314, NULL, NULL, NULL, 3),
  ('رسمی', 'rasmi', 'offiziell', 314, NULL, NULL, NULL, 3),
  ('ساخته', 'sâkhte', 'hergestellt / gefertigt', 314, NULL, NULL, NULL, 3),
  ('سنگین', 'sangin', 'schwer', 314, NULL, NULL, NULL, 3),
  ('شدید', 'shadid', 'heftig / stark', 314, NULL, NULL, NULL, 3),
  ('طولانی', 'tulâni', 'lang / langwierig', 314, NULL, NULL, NULL, 3),
  ('مالی', 'mâli', 'finanziell', 314, NULL, NULL, NULL, 3),
  ('مربوط', 'marbut', 'zugehörig / betreffend', 314, NULL, NULL, NULL, 3),
  ('مستقیم', 'mostaghim', 'direkt / gerade', 314, NULL, NULL, NULL, 3),
  ('مشترک', 'moshtarak', 'gemeinsam / Teilnehmer', 314, NULL, NULL, NULL, 3),
  ('معتقد', 'mo''taghed', 'überzeugt / gläubig', 314, NULL, NULL, NULL, 3),
  ('موجود', 'movjud', 'vorhanden / Lebewesen', 314, NULL, NULL, NULL, 3),
  ('نظامی', 'nezâmi', 'militärisch', 314, NULL, NULL, 'Homograph: نظامی = militärisch / Nezami', 3),
  ('واقع', 'vâghe''', 'gelegen / tatsächlich', 314, NULL, NULL, NULL, 3),
  ('واقعی', 'vâghe''i', 'echt / wirklich', 314, NULL, NULL, NULL, 3),
  ('پیدا', 'peydâ', 'gefunden / sichtbar', 314, NULL, NULL, NULL, 3),
  ('کافی', 'kâfi', 'ausreichend / genug', 314, NULL, NULL, NULL, 3),
  ('کوچک', 'kuchak', 'klein', 314, NULL, NULL, NULL, 3),
  -- L315
  ('آخر', 'âkhar', 'letzte/r/s / schließlich', 315, 'آخرِ ماه پول کم می‌آورم.', 'Am Monatsende fehlt mir Geld.', NULL, 4),
  ('البته', 'albatte', 'natürlich / freilich', 315, 'البته که کمکت می‌کنم.', 'Natürlich helfe ich dir.', NULL, 5),
  ('اکنون', 'aknun', 'jetzt / nun', 315, 'اکنون وقت رفتن است.', 'Jetzt ist es Zeit zu gehen.', NULL, 4),
  ('بسیار', 'besyâr', 'sehr / viel', 315, 'بسیار خوب.', 'Sehr gut.', 'Etwas formeller als خیلی.', 5),
  ('تازه', 'tâze', 'frisch / neu', 315, NULL, NULL, NULL, 3),
  ('تاکنون', 'tâknun', 'bisher', 315, NULL, NULL, NULL, 3),
  ('تنها', 'tanhâ', 'allein / nur', 315, 'تنها یک راه وجود دارد.', 'Es gibt nur einen Weg.', 'Kann ''allein'' oder ''nur'' bedeuten.', 5),
  ('حتی', 'hattâ', 'sogar', 315, 'حتی او هم آمد.', 'Sogar er kam auch.', NULL, 4),
  ('خوبی', 'khubi', 'Güte / gut', 315, NULL, NULL, NULL, 3),
  ('خیلی', 'kheyli', 'sehr', 315, NULL, NULL, NULL, 3),
  ('در حال', 'darhâl', 'im Begriff (zu) / dabei', 315, 'او در حال خواندن است.', 'Er ist gerade beim Lesen.', NULL, 5),
  ('زیاد', 'ziyâd', 'viel / sehr', 315, NULL, NULL, NULL, 3),
  ('فقط', 'faghat', 'nur / bloß', 315, NULL, NULL, NULL, 3),
  ('مانند', 'mânand', 'wie / ähnlich', 315, 'او مانند پدرش است.', 'Er ist wie sein Vater.', NULL, 4),
  ('نخست', 'nokhost', 'zuerst / erstens', 315, 'نخست باید استراحت کنی.', 'Zuerst musst du dich ausruhen.', NULL, 4),
  ('هنوز', 'hanuz', 'noch / immer noch', 315, 'او هنوز نیامده است.', 'Er ist noch nicht gekommen.', NULL, 4),
  ('کاملاً', 'kâmelan', 'völlig / vollständig', 315, 'کاملاً درست می‌گویی.', 'Du hast völlig recht.', NULL, 4),
  -- L401
  ('آینده', 'âyande', 'Zukunft / künftig', 401, 'به آینده امیدوارم.', 'Ich bin hoffnungsvoll für die Zukunft.', NULL, 4),
  ('اول', 'avval', 'erste/r/s / zuerst', 401, 'اول گوش بده.', 'Hör zuerst zu.', 'Reihenfolge und Diskursstruktur.', 5),
  ('بار', 'bâr', 'Mal / Last', 401, 'این بار من می‌پردازم.', 'Dieses Mal zahle ich.', NULL, 4),
  ('بعد', 'ba''d', 'danach / nach / später', 401, 'بعد از ناهار می‌آیم.', 'Nach dem Mittagessen komme ich.', NULL, 4),
  ('حال', 'hâl', 'Zustand / Gegenwart / jetzt', 401, 'حالت چطور است؟', 'Wie ist dein Befinden?', NULL, 4),
  ('دوره', 'dovre', 'Periode / Kurs', 401, 'یک دوره‌ی زبان شروع کردم.', 'Ich habe einen Sprachkurs begonnen.', NULL, 5),
  ('روز', 'ruz', 'Tag', 401, 'روز خوبی بود.', 'Es war ein guter Tag.', 'Zeit, Datum, Routine.', 5),
  ('زمان', 'zamân', 'Zeit', 401, 'زمان زود می‌گذرد.', 'Die Zeit vergeht schnell.', NULL, 4),
  ('سال', 'sâl', 'Jahr', 401, 'سه سال پیش', 'vor drei Jahren', 'Zentrales Zeitwort; auch Alter: ساله.', 5),
  ('قبل', 'ghabl', 'vorher / bevor', 401, 'قبل از جلسه', 'vor dem Treffen', 'Mit از: قبل از = vor.', 5),
  ('ماه', 'mâh', 'Monat / Mond', 401, 'ماه آینده تعطیلات دارم.', 'Nächsten Monat habe ich Urlaub.', NULL, 5),
  ('مدت', 'moddat', 'Dauer / Zeitraum', 401, 'برای مدت کوتاهی', 'für kurze Zeit', 'Häufig in مدت کوتاه/طولانی.', 4),
  ('پایان', 'pâyân', 'Ende', 401, 'تا پایان فیلم ماندیم.', 'Wir blieben bis zum Ende des Films.', NULL, 4),
  ('پیش', 'pish', 'vor / vorher / bei', 401, 'دو سال پیش', 'vor zwei Jahren', 'Zeitlich und räumlich; auch bei Personen: پیش من.', 5),
  ('گذشته', 'gozashte', 'Vergangenheit / vergangen', 401, 'گذشته را فراموش کن.', 'Vergiss die Vergangenheit.', NULL, 5),
  -- L402
  ('آغاز', 'âghâz', 'Beginn / Anfang', 402, 'آغاز سال نو مبارک.', 'Frohen Beginn des neuen Jahres.', NULL, 4),
  ('ابتدا', 'ebtedâ', 'Anfang / zuerst', 402, NULL, NULL, NULL, 3),
  ('امروز', 'emruz', 'heute', 402, 'امروز هوا آفتابی است.', 'Heute ist das Wetter sonnig.', NULL, 4),
  ('تاریخ', 'târikh', 'Geschichte / Datum', 402, NULL, NULL, NULL, 3),
  ('دقیقه', 'daghighe', 'Minute', 402, NULL, NULL, NULL, 3),
  ('دهه', 'dahe', 'Jahrzehnt', 402, NULL, NULL, NULL, 3),
  ('دوران', 'dovrân', 'Ära / Zeitraum', 402, NULL, NULL, NULL, 3),
  ('ساعت', 'sâ''at', 'Stunde / Uhr', 402, 'ساعت چند است؟', 'Wie spät ist es?', NULL, 4),
  ('شب', 'shab', 'Nacht', 402, NULL, NULL, NULL, 3),
  ('شروع', 'shoru''', 'Beginn / Start', 402, NULL, NULL, NULL, 3),
  ('شنبه', 'shambe', 'Samstag', 402, NULL, NULL, NULL, 3),
  ('فصل', 'fasl', 'Jahreszeit / Kapitel', 402, NULL, NULL, NULL, 3),
  ('مرحله', 'marhale', 'Stufe / Phase', 402, 'به مرحله‌ی بعد رسیدیم.', 'Wir haben die nächste Stufe erreicht.', NULL, 4),
  ('هفته', 'hafte', 'Woche', 402, 'این هفته خیلی شلوغ است.', 'Diese Woche ist sehr voll.', NULL, 4),
  ('وقت', 'vaght', 'Zeit', 402, NULL, NULL, NULL, 3),
  -- L403
  ('ده', 'dah', 'zehn (auch: Dorf)', 403, NULL, NULL, NULL, 3),
  ('دو', 'do', 'zwei', 403, 'دو سؤال دارم.', 'Ich habe zwei Fragen.', 'Zahlwort.', 5),
  ('دوم', 'dovvom', 'zweite/r/s', 403, 'این بار دوم است.', 'Das ist das zweite Mal.', NULL, 5),
  ('سه', 'se', 'drei', 403, 'سه کتاب خریدم.', 'Ich habe drei Bücher gekauft.', NULL, 5),
  ('سوم', 'sevvom', 'dritte/r/s', 403, 'او در مسابقه سوم شد.', 'Er wurde im Wettbewerb Dritter.', NULL, 4),
  ('میلیارد', 'milyârd', 'Milliarde', 403, NULL, NULL, NULL, 3),
  ('میلیون', 'milyun', 'Million', 403, 'این شهر دو میلیون نفر جمعیت دارد.', 'Diese Stadt hat zwei Millionen Einwohner.', NULL, 4),
  ('هزار', 'hezâr', 'tausend', 403, 'این لباس صد هزار تومان است.', 'Dieses Kleid kostet hunderttausend Tuman.', NULL, 5),
  ('چهار', 'chahâr', 'vier', 403, NULL, NULL, NULL, 3),
  ('چهارم', 'chahârom', 'vierte/r/s', 403, NULL, NULL, NULL, 3),
  ('یک', 'yek', 'eins / ein', 403, 'یک سؤال دارم.', 'Ich habe eine Frage.', 'Zahlwort und unbestimmter Artikel-ähnliche Funktion.', 5),
  -- L501
  ('بازیکن', 'bâzikon', 'Spieler', 501, NULL, NULL, NULL, 3),
  ('تیم', 'tim', 'Mannschaft / Team', 501, NULL, NULL, NULL, 3),
  ('جام', 'jâm', 'Pokal', 501, NULL, NULL, NULL, 3),
  ('داور', 'dâvar', 'Schiedsrichter', 501, NULL, NULL, NULL, 3),
  ('دروازه‌بان', 'darvâze-bân', 'Torwart', 501, NULL, NULL, NULL, 3),
  ('شوت', 'shut', 'Schuss', 501, NULL, NULL, NULL, 3),
  ('شکست', 'shekast', 'Niederlage', 501, NULL, NULL, NULL, 3),
  ('ضربه آزاد', 'zarbe-ye âzâd', 'Freistoß', 501, NULL, NULL, NULL, 3),
  ('فوتبال', 'futbâl', 'Fußball', 501, NULL, NULL, NULL, 3),
  ('قهرمان', 'ghahremân', 'Meister', 501, NULL, NULL, NULL, 3),
  ('مدافع', 'modâfe''', 'Verteidiger', 501, NULL, NULL, NULL, 3),
  ('مربی', 'morabbi', 'Trainer', 501, NULL, NULL, NULL, 3),
  ('مسابقه', 'mosâbeghe', 'Spiel / Match', 501, NULL, NULL, NULL, 3),
  ('مساوی', 'mosâvi', 'Unentschieden', 501, NULL, NULL, NULL, 3),
  ('مهاجم', 'mohâjem', 'Stürmer', 501, NULL, NULL, NULL, 3),
  ('نیمه اول', 'nime-ye avval', 'Erste Halbzeit', 501, NULL, NULL, NULL, 3),
  ('نیمه دوم', 'nime-ye dovvom', 'Zweite Halbzeit', 501, NULL, NULL, NULL, 3),
  ('هافبک', 'hâfbak', 'Mittelfeldspieler', 501, NULL, NULL, NULL, 3),
  ('هوادار', 'havâdâr', 'Fan', 501, NULL, NULL, NULL, 3),
  ('ورزشگاه', 'varzeshgâh', 'Stadion', 501, NULL, NULL, NULL, 3),
  ('وقت اضافه', 'vaght-e ezâfe', 'Verlängerung', 501, NULL, NULL, NULL, 3),
  ('پاس', 'pâs', 'Pass', 501, NULL, NULL, NULL, 3),
  ('پنالتی', 'penâlti', 'Elfmeter', 501, NULL, NULL, NULL, 3),
  ('پیروزی', 'piruzi', 'Sieg', 501, NULL, NULL, NULL, 3),
  ('کارت زرد', 'kârt-e zard', 'Gelbe Karte', 501, NULL, NULL, NULL, 3),
  ('کارت قرمز', 'kârt-e ghermez', 'Rote Karte', 501, NULL, NULL, NULL, 3),
  ('کاپیتان', 'kâpitân', 'Kapitän', 501, NULL, NULL, NULL, 3),
  ('کرنر', 'korner', 'Eckball', 501, NULL, NULL, NULL, 3),
  ('گروه', 'goruh', 'Gruppe', 501, NULL, NULL, NULL, 3),
  ('گل', 'gol', 'Tor', 501, NULL, NULL, NULL, 3),
  -- L502
  ('استراحت', 'esterâhat', 'Erholung', 502, 'بعد از کار به استراحت نیاز دارم.', 'Nach der Arbeit brauche ich Erholung.', NULL, 3),
  ('امتحان', 'emtehân', 'Prüfung', 502, 'فردا امتحان ریاضی دارم.', 'Morgen habe ich eine Matheprüfung.', NULL, 3),
  ('برنامه‌ریزی', 'barnâme-rizi', 'Planung', 502, 'برنامه‌ریزی برای سفر مهم است.', 'Planung ist wichtig für eine Reise.', NULL, 3),
  ('تجربه', 'tajrobe', 'Erfahrung', 502, 'این سفر تجربه‌ی خوبی بود.', 'Diese Reise war eine gute Erfahrung.', NULL, 3),
  ('تجربه کاری', 'tajrobe-ye kâri', 'Berufserfahrung', 502, 'این کار به من تجربه‌ی کاری داد.', 'Diese Arbeit gab mir Berufserfahrung.', NULL, 3),
  ('تعطیلات', 'ta''tilât', 'Ferien', 502, 'تعطیلات تابستان را کجا می‌گذرانی؟', 'Wo verbringst du die Sommerferien?', NULL, 3),
  ('جشنواره', 'jashnvâre', 'Festival', 502, 'تابستان به یک جشنواره‌ی موسیقی رفتیم.', 'Im Sommer gingen wir zu einem Musikfestival.', NULL, 3),
  ('خاطره', 'khâtere', 'Erinnerung', 502, 'از این تعطیلات خاطره‌ی خوبی دارم.', 'Von diesen Ferien habe ich eine schöne Erinnerung.', NULL, 3),
  ('دانش‌آموز', 'dânesh-âmuz', 'Schüler / Schülerin', 502, 'این دانش‌آموز خیلی کوشاست.', 'Dieser Schüler ist sehr fleißig.', NULL, 3),
  ('دریا', 'daryâ', 'Meer', 502, 'در تعطیلات کنار دریا رفتیم.', 'In den Ferien fuhren wir ans Meer.', NULL, 3),
  ('دوچرخه‌سواری', 'docharkhe-savâri', 'Radfahren', 502, 'دوچرخه‌سواری در پارک لذت‌بخش است.', 'Radfahren im Park macht Spaß.', NULL, 3),
  ('رشد شخصی', 'roshd-e shakhsi', 'Persönliche Entwicklung', 502, 'سفر به رشد شخصی کمک می‌کند.', 'Reisen hilft der persönlichen Entwicklung.', NULL, 3),
  ('زبان خارجی', 'zabân-e khâreji', 'Fremdsprache', 502, 'یادگیری یک زبان خارجی مفید است.', 'Eine Fremdsprache zu lernen ist nützlich.', NULL, 3),
  ('ساز', 'sâz', 'Musikinstrument', 502, 'می‌خواهم یک ساز یاد بگیرم.', 'Ich möchte ein Musikinstrument lernen.', NULL, 3),
  ('سال تحصیلی', 'sâl-e tahsili', 'Schuljahr', 502, 'سال تحصیلی جدید پاییز شروع می‌شود.', 'Das neue Schuljahr beginnt im Herbst.', NULL, 3),
  ('سفر', 'safar', 'Reise', 502, 'تابستان به یک سفر طولانی می‌رویم.', 'Im Sommer machen wir eine lange Reise.', NULL, 3),
  ('شنا', 'shenâ', 'Schwimmen', 502, 'هر روز صبح شنا می‌کنم.', 'Jeden Morgen schwimme ich.', NULL, 3),
  ('طبیعت', 'tabi''at', 'Natur', 502, 'عاشق گردش در طبیعت هستم.', 'Ich liebe Ausflüge in die Natur.', NULL, 3),
  ('فرصت', 'forsat', 'Gelegenheit', 502, 'این فرصت خوبی برای یادگیری است.', 'Das ist eine gute Gelegenheit zum Lernen.', NULL, 3),
  ('فرهنگ', 'farhang', 'Kultur', 502, 'با فرهنگ کشورهای دیگر آشنا شدم.', 'Ich habe die Kultur anderer Länder kennengelernt.', NULL, 3),
  ('مهارت', 'mahârat', 'Fähigkeit', 502, 'او در آشپزی مهارت دارد.', 'Er hat Geschick beim Kochen.', NULL, 3),
  ('ورزش', 'varzesh', 'Sport', 502, 'هر هفته ورزش می‌کنم.', 'Jede Woche treibe ich Sport.', NULL, 3),
  ('چادر', 'châdor', 'Zelt', 502, 'چادر را کنار رودخانه برپا کردیم.', 'Wir stellten das Zelt am Fluss auf.', NULL, 3),
  ('کار پاره‌وقت', 'kâr-e pâre-vaght', 'Teilzeitjob', 502, 'تابستان یک کار پاره‌وقت پیدا کردم.', 'Im Sommer habe ich einen Teilzeitjob gefunden.', NULL, 3),
  ('کمپینگ', 'kemping', 'Camping', 502, 'آخر هفته به کمپینگ می‌رویم.', 'Am Wochenende gehen wir campen.', NULL, 3),
  -- L503
  ('آتش', 'âtash', 'Feuer', 503, 'آتش خانه را سوزاند.', 'Das Feuer verbrannte das Haus.', NULL, 3),
  ('انفجار', 'enfejâr', 'Explosion', 503, 'صدای انفجار همه را ترساند.', 'Der Knall der Explosion erschreckte alle.', NULL, 3),
  ('تانک', 'tânk', 'Panzer', 503, 'تانک در خیابان ایستاد.', 'Der Panzer stand auf der Straße.', NULL, 3),
  ('جنگ', 'jang', 'Krieg', 503, 'جنگ سال‌ها طول کشید.', 'Der Krieg dauerte Jahre.', NULL, 3),
  ('خانه', 'khâne', 'Haus', 503, 'خانه‌ی ما در جنگ ویران شد.', 'Unser Haus wurde im Krieg zerstört.', NULL, 3),
  ('دود', 'dud', 'Rauch', 503, 'دود سیاه از خانه بلند شد.', 'Schwarzer Rauch stieg aus dem Haus.', NULL, 3),
  ('سرباز', 'sarbâz', 'Soldat', 503, 'سرباز از شهر دفاع کرد.', 'Der Soldat verteidigte die Stadt.', NULL, 3),
  ('شهر', 'shahr', 'Stadt', 503, 'شهر پس از جنگ ویران بود.', 'Die Stadt war nach dem Krieg zerstört.', NULL, 3),
  ('صلح', 'solh', 'Frieden', 503, 'همه مردم صلح می‌خواهند.', 'Alle Menschen wollen Frieden.', NULL, 3),
  ('مردم', 'mardom', 'Menschen / Volk', 503, 'مردم از شهر فرار کردند.', 'Die Menschen flohen aus der Stadt.', NULL, 3),
  ('هواپیما', 'havâpeymâ', 'Flugzeug', 503, 'هواپیما بر فراز شهر پرواز کرد.', 'Das Flugzeug flog über die Stadt.', NULL, 3),
  ('ویران', 'virân', 'zerstört', 503, 'این ساختمان کاملاً ویران شده است.', 'Dieses Gebäude ist völlig zerstört.', NULL, 3),
  ('پناهنده', 'panâhande', 'Flüchtling', 503, 'پناهنده‌ها به کشور دیگری رفتند.', 'Die Flüchtlinge gingen in ein anderes Land.', NULL, 3),
  -- L601
  ('آره', 'âre', 'Ja', 601, 'آره، من هم می‌آم.', 'Ja, ich komme auch mit.', NULL, 5),
  ('باشه', 'bâshe', 'Okay / Einverstanden', 601, 'باشه، فردا بهت زنگ می‌زنم.', 'Okay, ich rufe dich morgen an.', NULL, 5),
  ('ببخشید', 'bebakhshid', 'Entschuldigung', 601, 'ببخشید، ساعت چند است؟', 'Entschuldigung, wie spät ist es?', NULL, 5),
  ('بفرمایید', 'befarmâyid', 'Bitte schön / Hier bitte', 601, 'بفرمایید، این هم چای شما.', 'Bitte schön, hier ist Ihr Tee.', NULL, 5),
  ('بله', 'bale', 'Ja (höflich)', 601, 'بله، حتماً در خدمتم.', 'Ja, sehr gern, ich stehe zur Verfügung.', NULL, 5),
  ('به خدا', 'be khodâ', 'Bei Gott / Ich schwöre', 601, 'به خدا من کاری نکردم.', 'Bei Gott, ich habe nichts getan.', NULL, 5),
  ('خدا رو شکر', 'khodâ ro shokr', 'Gott sei Dank', 601, 'خدا رو شکر که سالم رسیدی.', 'Gott sei Dank bist du heil angekommen.', NULL, 5),
  ('خداحافظ', 'khodâ hâfez', 'Auf Wiedersehen', 601, 'خداحافظ، مواظب خودت باش.', 'Auf Wiedersehen, pass auf dich auf.', NULL, 5),
  ('خسته نباشین', 'khaste nabâshin', 'Gute Arbeit! (Grußformel)', 601, 'سلام، خسته نباشین! کارتون تمام شد؟', 'Hallo, gute Arbeit! Sind Sie fertig?', 'wörtl. „Mögen Sie nicht müde sein“', 5),
  ('خواهش می‌کنم', 'khâhesh mikonam', 'Bitte / Gern geschehen', 601, 'ـ ممنون! ـ خواهش می‌کنم.', '– Danke! – Gern geschehen.', NULL, 5),
  ('خوبی', 'khubi', 'Alles gut? / Geht''s dir gut?', 601, 'خوبی؟ چند وقته ندیدمت.', 'Geht''s dir gut? Ich hab dich lange nicht gesehen.', NULL, 5),
  ('خوشحال شدم', 'khoshhâl shodam', 'Hat mich gefreut', 601, 'از آشنایی با شما خوشحال شدم.', 'Hat mich gefreut, Sie kennenzulernen.', NULL, 5),
  ('خوشحالم', 'khoshhâlam', 'Ich freue mich / Ich bin froh', 601, 'از دیدنت خیلی خوشحالم.', 'Ich freue mich sehr, dich zu sehen.', NULL, 5),
  ('دست شما درد نکنه', 'dast-e shomâ dard nakone', 'Vielen Dank', 601, 'دست شما درد نکنه، خیلی کمک کردید.', 'Vielen Dank, Sie haben sehr geholfen.', 'wörtl. „Möge Ihre Hand nicht schmerzen“', 5),
  ('روز بخیر', 'ruz bekheir', 'Guten Tag', 601, 'روز بخیر، خوش آمدید.', 'Guten Tag, willkommen.', NULL, 5),
  ('سلام', 'salâm', 'Hallo', 601, 'سلام، حال شما چطور است؟', 'Hallo, wie geht es Ihnen?', NULL, 5),
  ('شب بخیر', 'shab bekheir', 'Gute Nacht', 601, 'شب بخیر، فردا می‌بینمت.', 'Gute Nacht, bis morgen.', NULL, 5),
  ('شرمنده', 'sharmande', 'Tut mir leid / beschämt', 601, 'شرمنده که دیر کردم.', 'Tut mir leid, dass ich zu spät bin.', NULL, 5),
  ('صبح بخیر', 'sobh bekheir', 'Guten Morgen', 601, 'صبح بخیر! خوب خوابیدی؟', 'Guten Morgen! Hast du gut geschlafen?', NULL, 5),
  ('قابلی نداره', 'ghâbeli nadâre', 'Keine Ursache', 601, 'ـ ممنون بابت کمک. ـ قابلی نداره.', '– Danke für die Hilfe. – Keine Ursache.', 'wörtl. „Es ist nichts wert“', 5),
  ('قدمتون روی چشم', 'ghadametun ru cheshm', 'Herzlich willkommen', 601, 'بیایید تو، قدمتون روی چشم.', 'Kommen Sie herein, herzlich willkommen.', 'wörtl. „Ihr Schritt auf mein Auge“', 5),
  ('قربان شما', 'ghorbân-e shomâ', 'Sehr verbunden (höflich)', 601, 'لطف دارید، قربان شما.', 'Sehr freundlich, ich bin Ihnen verbunden.', 'wörtl. „Ihr Opfer (sei ich)“', 5),
  ('متشکرم', 'moteshakkeram', 'Ich danke Ihnen', 601, 'از همراهی‌تان متشکرم.', 'Ich danke Ihnen für Ihre Begleitung.', NULL, 5),
  ('مرسی', 'mersi', 'Danke', 601, 'مرسی که اومدی.', 'Danke, dass du gekommen bist.', NULL, 5),
  ('ممنون', 'mamnun', 'Danke', 601, 'ممنون از وقتی که گذاشتی.', 'Danke für deine Zeit.', NULL, 5),
  ('نخیر', 'nakheir', 'Nein (bestimmt/höflich)', 601, 'نخیر، این درست نیست.', 'Nein, das stimmt nicht.', NULL, 5),
  ('نه', 'na', 'Nein', 601, 'نه، ممنون، سیر هستم.', 'Nein danke, ich bin satt.', NULL, 5),
  ('پناه بر خدا', 'panâh bar khodâ', 'Um Gottes Willen', 601, 'پناه بر خدا، چه اتفاقی افتاده؟', 'Um Gottes Willen, was ist passiert?', NULL, 5),
  ('چشم', 'cheshm', 'Gerne / Mach ich', 601, 'ـ لطفاً در را ببند. ـ چشم.', '– Mach bitte die Tür zu. – Gerne, mach ich.', 'wörtl. „Auge“ = zu Befehl', 5),
  ('چطوری', 'chetori', 'Wie geht''s?', 601, 'سلام، چطوری؟ چه خبر؟', 'Hallo, wie geht''s? Was gibt''s Neues?', NULL, 5),
  -- L602
  ('الآن', 'alân', 'jetzt', 602, 'الآن نمی‌توانم صحبت کنم.', 'Jetzt kann ich nicht sprechen.', NULL, 4),
  ('امروز', 'emruz', 'heute', 602, 'امروز هوا خیلی خوب است.', 'Heute ist das Wetter sehr schön.', NULL, 4),
  ('امروز صبح', 'emruz sobh', 'heute Morgen', 602, 'امروز صبح زود بیدار شدم.', 'Heute Morgen bin ich früh aufgewacht.', NULL, 4),
  ('امروز ظهر', 'emruz zohr', 'heute Mittag', 602, 'امروز ظهر با هم ناهار بخوریم.', 'Lass uns heute Mittag zusammen essen.', NULL, 4),
  ('امشب', 'emshab', 'heute Abend', 602, 'امشب خانه می‌مانم.', 'Heute Abend bleibe ich zu Hause.', NULL, 4),
  ('تا بعد', 'tâ ba''d', 'bis später', 602, 'فعلاً کاری ندارم، تا بعد.', 'Ich hab gerade nichts zu tun, bis später.', NULL, 4),
  ('تا فردا', 'tâ fardâ', 'bis morgen', 602, 'خسته‌ام، تا فردا.', 'Ich bin müde, bis morgen.', NULL, 4),
  ('تا هفته آینده', 'tâ hafte âyande', 'bis nächste Woche', 602, 'قرارمان باشد تا هفته آینده.', 'Bleiben wir bei nächster Woche, bis dann.', NULL, 4),
  ('دیروز', 'diruz', 'gestern', 602, 'دیروز تو را در بازار دیدم.', 'Gestern habe ich dich auf dem Markt gesehen.', NULL, 4),
  ('دیروز صبح', 'diruz sobh', 'gestern Morgen', 602, 'دیروز صبح باران می‌بارید.', 'Gestern Morgen hat es geregnet.', NULL, 4),
  ('دیروز ظهر', 'diruz zohr', 'gestern Mittag', 602, 'دیروز ظهر چه خوردی؟', 'Was hast du gestern Mittag gegessen?', NULL, 4),
  ('دیشب', 'dishab', 'gestern Abend', 602, 'دیشب خوب نخوابیدم.', 'Gestern Abend habe ich schlecht geschlafen.', NULL, 4),
  ('روز به روز', 'ruz be ruz', 'Tag für Tag', 602, 'حالش روز به روز بهتر می‌شود.', 'Es geht ihm Tag für Tag besser.', NULL, 4),
  ('شبانه روز', 'shabâne ruz', 'rund um die Uhr', 602, 'این داروخانه شبانه روز باز است.', 'Diese Apotheke hat rund um die Uhr geöffnet.', 'wörtl. „Nacht und Tag“', 4),
  ('فردا', 'fardâ', 'morgen', 602, 'فردا امتحان دارم.', 'Morgen habe ich eine Prüfung.', NULL, 4),
  ('فردا شب', 'fardâ shab', 'morgen Abend', 602, 'فردا شب مهمان داریم.', 'Morgen Abend haben wir Gäste.', NULL, 4),
  ('فردا صبح', 'fardâ sobh', 'morgen früh', 602, 'فردا صبح زود حرکت می‌کنیم.', 'Morgen früh brechen wir auf.', NULL, 4),
  ('فردا ظهر', 'fardâ zohr', 'morgen Mittag', 602, 'فردا ظهر وقت داری؟', 'Hast du morgen Mittag Zeit?', NULL, 4),
  ('ماه آینده', 'mâh-e âyande', 'nächster Monat', 602, 'ماه آینده اسباب‌کشی می‌کنیم.', 'Nächsten Monat ziehen wir um.', NULL, 4),
  ('ماه پیش', 'mâh-e pish', 'letzter Monat', 602, 'ماه پیش کار جدیدی شروع کردم.', 'Letzten Monat habe ich einen neuen Job angefangen.', NULL, 4),
  ('ماه گذشته', 'mâh-e gozashte', 'vergangener Monat', 602, 'ماه گذشته باران زیادی بارید.', 'Im vergangenen Monat hat es viel geregnet.', NULL, 4),
  ('هر روز', 'har ruz', 'jeden Tag', 602, 'هر روز پیاده‌روی می‌کنم.', 'Ich gehe jeden Tag spazieren.', NULL, 4),
  ('هفته‌ی آینده', 'hafte-ye âyande', 'nächste Woche', 602, 'هفته‌ی آینده سفر می‌روم.', 'Nächste Woche verreise ich.', NULL, 4),
  ('هفته‌ی پیش', 'hafte-ye pish', 'letzte Woche', 602, 'هفته‌ی پیش او را دیدم.', 'Letzte Woche habe ich ihn gesehen.', NULL, 4),
  ('هفته‌ی گذشته', 'hafte-ye gozashte', 'vergangene Woche', 602, 'هفته‌ی گذشته خیلی شلوغ بود.', 'Die vergangene Woche war sehr voll.', NULL, 4),
  ('همین حالا', 'hamin hâlâ', 'genau jetzt / sofort', 602, 'همین حالا بیا اینجا.', 'Komm sofort her.', NULL, 4),
  ('پریروز', 'pariruz', 'vorgestern', 602, 'پریروز به تهران رفتم.', 'Vorgestern bin ich nach Teheran gefahren.', NULL, 4),
  ('پریشب', 'parishab', 'vorgestern Abend', 602, 'پریشب تا دیروقت بیدار بودم.', 'Vorgestern Abend war ich bis spät wach.', NULL, 4),
  ('پس فردا', 'pasfardâ', 'übermorgen', 602, 'پس فردا تعطیل است.', 'Übermorgen ist frei.', NULL, 4),
  -- L603
  ('این چنده', 'in chande', 'Wie viel kostet das?', 603, 'ببخشید، این چنده؟', 'Entschuldigung, wie viel kostet das?', NULL, 4),
  ('این چیه', 'in chie', 'Was ist das?', 603, 'ببخشید، این چیه؟', 'Entschuldigung, was ist das?', NULL, 4),
  ('این چیه دیگه', 'in chie dige', 'Was ist das denn?', 603, 'این چیه دیگه روی میز؟', 'Was ist das denn da auf dem Tisch?', NULL, 4),
  ('این کیه', 'in kie', 'Wer ist das?', 603, 'این کیه توی عکس؟', 'Wer ist das auf dem Foto?', NULL, 4),
  ('تعارف می‌کنی؟', 'ta''ârof mikoni', 'Machst du Ta''arof? (Höflichkeitsspiel)', 603, 'راحت باش، تعارف می‌کنی؟', 'Fühl dich frei, machst du etwa Ta''arof?', NULL, 4),
  ('حالا که چی', 'hâlâ ke chi', 'Na und?', 603, 'خب دیر شد، حالا که چی؟', 'Na ja, es ist spät geworden, na und?', NULL, 4),
  ('خبری نیست', 'khabari nist', 'Nichts Neues', 603, 'فعلاً خبری نیست، همه چیز آرام است.', 'Im Moment nichts Neues, alles ruhig.', NULL, 4),
  ('راس میگی', 'râst migi', 'Echt? / Im Ernst?', 603, 'راس میگی؟ باورم نمی‌شه.', 'Echt? Das glaub ich nicht.', NULL, 4),
  ('مطمئنی', 'motma''eni', 'Bist du sicher?', 603, 'مطمئنی که در را بستی؟', 'Bist du sicher, dass du die Tür zugemacht hast?', NULL, 4),
  ('می‌فهمی؟', 'mifahmi', 'Verstehst du?', 603, 'منظورم را می‌فهمی؟', 'Verstehst du, was ich meine?', NULL, 4),
  ('چرا', 'cherâ', 'Warum', 603, 'چرا دیروز نیامدی؟', 'Warum bist du gestern nicht gekommen?', NULL, 4),
  ('چقدر بدم؟', 'cheghadr bedam', 'Wie viel soll ich geben?', 603, 'چقدر بدم خدمتتون؟', 'Wie viel soll ich Ihnen geben?', NULL, 4),
  ('چقدر تقدیم کنم؟', 'cheghadr taghdim konam', 'Wie viel darf ich geben? (höflich)', 603, 'چقدر تقدیم کنم؟', 'Wie viel darf ich Ihnen entrichten?', NULL, 4),
  ('چقدر می‌شه؟', 'cheghadr mishe', 'Wie viel macht das?', 603, 'همه‌اش چقدر می‌شه؟', 'Wie viel macht das alles zusammen?', NULL, 4),
  ('چند تا', 'chand tâ', 'Wie viele?', 603, 'چند تا بلیط می‌خوای؟', 'Wie viele Tickets willst du?', NULL, 4),
  ('چند سالته', 'chand sâlete', 'Wie alt bist du?', 603, 'ببخشید، چند سالته؟', 'Sag mal, wie alt bist du?', NULL, 4),
  ('چه جوری', 'che juri', 'Wie? / Wie das?', 603, 'این دستگاه چه جوری کار می‌کند؟', 'Wie funktioniert dieses Gerät?', NULL, 4),
  ('چه خبر', 'che khabar', 'Was gibt''s Neues?', 603, 'سلام، چه خبر؟', 'Hallo, was gibt''s Neues?', NULL, 4),
  ('چی میگی', 'chi migi', 'Was sagst du?', 603, 'چی میگی؟ نشنیدم.', 'Was sagst du? Ich hab''s nicht gehört.', NULL, 4),
  ('چی گفتی', 'chi gofti', 'Was hast du gesagt?', 603, 'ببخشید، چی گفتی؟', 'Entschuldigung, was hast du gesagt?', NULL, 4),
  ('چیکار می‌کنی', 'chikâr mikoni', 'Was machst du?', 603, 'الان داری چیکار می‌کنی؟', 'Was machst du gerade?', NULL, 4),
  ('کجاس', 'kojâs', 'Wo ist er/sie/es?', 603, 'کلید کجاس؟', 'Wo ist der Schlüssel?', NULL, 4),
  ('کجایی', 'kojâyi', 'Wo bist du?', 603, 'الو، کجایی؟ منتظرتم.', 'Hallo, wo bist du? Ich warte.', NULL, 4),
  ('کو', 'ku', 'Wo ist es?', 603, 'کیفم کو؟ همین‌جا بود.', 'Wo ist meine Tasche? Sie war doch hier.', NULL, 4),
  ('کیه', 'kie', 'Wer ist es?', 603, 'در می‌زنند، کیه؟', 'Es klopft, wer ist da?', NULL, 4),
  ('یعنی چه', 'ya''ni che', 'Was soll das heißen?', 603, 'این کارت یعنی چه؟', 'Was soll dieses Verhalten heißen?', NULL, 4),
  ('یعنی چی', 'ya''ni chi', 'Was bedeutet das?', 603, 'این کلمه یعنی چی؟', 'Was bedeutet dieses Wort?', NULL, 4),
  -- L604
  ('اجازه بده', 'ejâze bede', 'Lass mich / Erlaube', 604, 'اجازه بده خودم انجامش بدهم.', 'Lass mich das selbst machen.', NULL, 4),
  ('بخورش', 'bokhoresh', 'Iss es!', 604, 'غذات سرد شد، بخورش.', 'Dein Essen wird kalt, iss es.', NULL, 4),
  ('بده من', 'bede man', 'Gib mir', 604, 'نمک را بده من، لطفاً.', 'Gib mir bitte das Salz.', NULL, 4),
  ('بدو', 'bedow', 'Lauf', 604, 'بدو که جا نمانیم.', 'Lauf, damit wir es nicht verpassen.', NULL, 4),
  ('برو', 'boro', 'Geh', 604, 'برو، دیرت می‌شود.', 'Geh, sonst kommst du zu spät.', NULL, 4),
  ('برو بیرون', 'boro birun', 'Geh raus', 604, 'لطفاً یک لحظه برو بیرون.', 'Geh bitte einen Moment raus.', NULL, 4),
  ('بزنش', 'bezanesh', 'Schlag ihn!', 604, 'توپ جلوته، بزنش!', 'Der Ball ist vor dir, schieß!', NULL, 4),
  ('بکن', 'bokon', 'Mach / Tu', 604, 'این کار را همین حالا بکن.', 'Mach diese Aufgabe sofort.', NULL, 4),
  ('بگو', 'begu', 'Sag', 604, 'هر چه می‌خواهی بگو.', 'Sag, was du willst.', NULL, 4),
  ('بگو دیگه', 'begu dige', 'Sag schon', 604, 'زود باش، بگو دیگه!', 'Komm schon, sag schon!', NULL, 4),
  ('بگیرش', 'begiresh', 'Nimm es / Schnapp ihn', 604, 'بیا، این کتاب را بگیرش.', 'Hier, nimm dieses Buch.', NULL, 4),
  ('بیا', 'biâ', 'Komm', 604, 'بیا، با هم برویم.', 'Komm, lass uns zusammen gehen.', NULL, 4),
  ('بیا اینجا', 'biâ injâ', 'Komm her', 604, 'بیا اینجا، باید حرف بزنیم.', 'Komm her, wir müssen reden.', NULL, 4),
  ('بیا تو', 'biâ tu', 'Komm rein', 604, 'در باز است، بیا تو.', 'Die Tür ist offen, komm rein.', NULL, 4),
  ('حرفشم نزن', 'harfesham nazan', 'Kein Wort davon', 604, 'حرفشم نزن، خودم حساب می‌کنم.', 'Kein Wort davon, ich zahle.', NULL, 4),
  ('خجالت بکش', 'khejâlat bekesh', 'Schäm dich', 604, 'خجالت بکش، این کار درست نبود.', 'Schäm dich, das war nicht in Ordnung.', NULL, 4),
  ('خجالتم ندین', 'khejâlatam nadin', 'Bringt mich nicht in Verlegenheit', 604, 'این‌قدر تعریف نکنید، خجالتم ندین.', 'Lobt mich nicht so, ihr bringt mich in Verlegenheit.', NULL, 4),
  ('دروغ نگو', 'dorugh nagu', 'Lüg nicht', 604, 'به من دروغ نگو.', 'Lüg mich nicht an.', NULL, 4),
  ('دوباره بگو', 'dobâre begu', 'Sag nochmal', 604, 'نفهمیدم، دوباره بگو.', 'Ich hab''s nicht verstanden, sag nochmal.', NULL, 4),
  ('زود باش', 'zud bâsh', 'Schnell / Beeil dich', 604, 'زود باش، دیر شد.', 'Schnell, es ist spät geworden.', NULL, 4),
  ('صبر کن', 'sabr kon', 'Warte / Hab Geduld', 604, 'یک لحظه صبر کن، الان می‌آیم.', 'Warte einen Moment, ich komme gleich.', NULL, 4),
  ('عجله کن', 'ajale kon', 'Beeil dich', 604, 'عجله کن، اتوبوس رسید.', 'Beeil dich, der Bus ist da.', NULL, 4),
  ('غر نزن', 'ghor nazan', 'Meckere nicht', 604, 'این‌قدر غر نزن، درست می‌شود.', 'Meckere nicht so, das wird schon.', NULL, 4),
  ('لاف نزن', 'lâf nazan', 'Prahle nicht', 604, 'لاف نزن، همه می‌دانند.', 'Prahle nicht, das wissen doch alle.', NULL, 4),
  ('مزخرف نگو', 'mozakhraf nagu', 'Red keinen Unsinn', 604, 'مزخرف نگو، این‌طور نیست.', 'Red keinen Unsinn, so ist es nicht.', NULL, 4),
  ('مواظب باش', 'movâzeb bâsh', 'Pass auf / Sei vorsichtig', 604, 'مواظب باش، پله لیز است.', 'Pass auf, die Stufe ist rutschig.', NULL, 4),
  ('نکن', 'nakon', 'Lass das', 604, 'این کار را نکن، خطرناک است.', 'Lass das, es ist gefährlich.', NULL, 4),
  ('نگو', 'nagu', 'Sag nicht', 604, 'به کسی نگو.', 'Sag es niemandem.', NULL, 4),
  ('پز نده', 'poz nade', 'Gib nicht an', 604, 'این‌قدر پز نده.', 'Gib nicht so an.', NULL, 4),
  ('چرند نگو', 'charand nagu', 'Red keinen Quatsch', 604, 'چرند نگو، جدی باش.', 'Red keinen Quatsch, sei ernst.', NULL, 4),
  ('کرم نریز', 'kerm nariz', 'Provoziere nicht', 604, 'آرام بنشین و کرم نریز.', 'Sitz still und provoziere nicht.', 'wörtl. „Wirf keine Würmer“', 4),
  ('یواش', 'yavâsh', 'Langsam / Sachte', 604, 'یواش برو، جاده لغزنده است.', 'Fahr langsam, die Straße ist glatt.', NULL, 4),
  -- L605
  ('آها', 'âhâ', 'Aha', 605, 'آها، حالا فهمیدم.', 'Aha, jetzt verstehe ich.', NULL, 4),
  ('اومدم', 'umadam', 'Ich komme (schon)', 605, 'یک لحظه، اومدم!', 'Einen Moment, ich komme schon!', NULL, 4),
  ('ای بابا', 'ey bâbâ', 'Ach Mann / Na sowas', 605, 'ای بابا، باز هم دیر شد.', 'Ach Mann, schon wieder zu spät.', NULL, 4),
  ('اینجوری', 'injuri', 'So', 605, 'اینجوری بگیرش که نیفتد.', 'Halt es so, damit es nicht runterfällt.', NULL, 4),
  ('اینطوری نه', 'intori na', 'Nicht so', 605, 'اینطوری نه، بذار نشانت بدهم.', 'Nicht so, lass es mich dir zeigen.', NULL, 4),
  ('ببینیم چی', 'bebinim chi', 'Mal sehen', 605, 'ببینیم چی پیش می‌آید.', 'Mal sehen, was passiert.', NULL, 4),
  ('بد نیست', 'bad nist', 'Nicht schlecht', 605, 'این رستوران بد نیست.', 'Dieses Restaurant ist nicht schlecht.', NULL, 4),
  ('برای اینکه', 'barâye inke', 'weil / damit', 605, 'زود آمدم برای اینکه کمک کنم.', 'Ich kam früh, um zu helfen.', NULL, 4),
  ('بسه', 'base', 'Es reicht', 605, 'بسه، دیگر کافی است.', 'Es reicht, genug jetzt.', NULL, 4),
  ('بسه دیگه', 'base dige', 'Jetzt reicht''s', 605, 'بسه دیگه، تمامش کن.', 'Jetzt reicht''s, hör auf.', NULL, 4),
  ('بسیار خب', 'besyâr khob', 'Sehr gut / Alles klar', 605, 'بسیار خب، قبول است.', 'Alles klar, einverstanden.', NULL, 4),
  ('بی زحمت', 'bi zahmat', 'Bitte (wenn''s keine Mühe macht)', 605, 'بی زحمت در را ببند.', 'Mach bitte die Tür zu, wenn es keine Mühe macht.', NULL, 4),
  ('تقصیر تو', 'taghsir-e to', 'Deine Schuld', 605, 'این تقصیر تو نیست.', 'Das ist nicht deine Schuld.', NULL, 4),
  ('تقصیر خودته', 'taghsir-e khodete', 'Selber schuld', 605, 'تقصیر خودته که گوش ندادی.', 'Selber schuld, dass du nicht zugehört hast.', NULL, 4),
  ('حتیٰ', 'hattâ', 'sogar', 605, 'حتی یک لحظه هم استراحت نکرد.', 'Er ruhte sich nicht einmal einen Moment aus.', NULL, 4),
  ('خب', 'khob', 'Na ja / Okay', 605, 'خب، از کجا شروع کنیم؟', 'Also, wo fangen wir an?', NULL, 4),
  ('خوبه', 'khube', 'Gut / Passt', 605, 'خوبه، همین کافی است.', 'Gut, das reicht.', NULL, 4),
  ('خودتی', 'khodeti', 'Selber! (Retourkutsche)', 605, 'ـ تو تنبلی! ـ خودتی!', '– Du bist faul! – Selber!', NULL, 4),
  ('خوش میگذره', 'khosh migzare', 'Es macht Spaß / läuft gut', 605, 'اینجا بهمان خوش می‌گذره.', 'Hier haben wir es schön.', NULL, 4),
  ('خوش گذشت', 'khosh gozasht', 'Es war schön', 605, 'دیشب خیلی خوش گذشت.', 'Gestern Abend war es sehr schön.', NULL, 4),
  ('خیلی بده', 'kheili bade', 'Sehr schlecht', 605, 'هوای امروز خیلی بده.', 'Das Wetter ist heute sehr schlecht.', NULL, 4),
  ('خیلی خب', 'kheili khob', 'Sehr gut / Okay', 605, 'خیلی خب، پس فردا می‌بینمت.', 'Okay, dann sehen wir uns morgen.', NULL, 4),
  ('درست می‌شه', 'dorost mishe', 'Das wird schon', 605, 'نگران نباش، درست می‌شه.', 'Mach dir keine Sorgen, das wird schon.', NULL, 4),
  ('درسته', 'doroste', 'Richtig / Korrekt', 605, 'درسته، حق با توست.', 'Richtig, du hast recht.', NULL, 4),
  ('دقیقاً', 'daghighan', 'Genau', 605, 'دقیقاً همین را می‌خواستم بگویم.', 'Genau das wollte ich sagen.', NULL, 4),
  ('دلم می‌خواد', 'delam mikhâd', 'Ich möchte', 605, 'دلم می‌خواد یک قهوه بخورم.', 'Ich möchte einen Kaffee trinken.', 'wörtl. „Mein Herz will“', 4),
  ('دوباره', 'dobâre', 'Nochmal', 605, 'دوباره امتحان کن.', 'Versuch es nochmal.', NULL, 4),
  ('دوست دارم', 'duset dâram', 'Ich hab dich lieb / Ich liebe dich', 605, 'من تو را دوست دارم.', 'Ich liebe dich.', NULL, 4),
  ('دیگه بسته', 'dige baste', 'Schluss jetzt', 605, 'دیگه بسته، باید برویم.', 'Schluss jetzt, wir müssen los.', NULL, 4),
  ('دیگه نمی‌خوام', 'dige nemikhâm', 'Ich will nicht mehr', 605, 'ممنون، دیگه نمی‌خوام.', 'Danke, ich will nichts mehr.', NULL, 4),
  ('دیگه نمی‌شه', 'dige nemishe', 'Das geht nicht mehr', 605, 'متأسفم، دیگه نمی‌شه کاری کرد.', 'Tut mir leid, da kann man nichts mehr machen.', NULL, 4),
  ('دیگه نه', 'dige na', 'Nicht mehr', 605, 'نه، دیگه نه، خسته شدم.', 'Nein, nicht mehr, ich bin müde geworden.', NULL, 4),
  ('شاید', 'shâyad', 'Vielleicht', 605, 'شاید فردا بیایم.', 'Vielleicht komme ich morgen.', NULL, 4),
  ('عجیبه', 'ajibe', 'Seltsam', 605, 'عجیبه، چراغ خودش روشن شد.', 'Seltsam, das Licht ging von selbst an.', NULL, 4),
  ('عیبی نداره', 'eibi nadâre', 'Macht nichts', 605, 'عیبی نداره، دفعه‌ی بعد.', 'Macht nichts, dann eben nächstes Mal.', NULL, 4),
  ('فرقی نمی‌کنه', 'farghi nemikone', 'Macht keinen Unterschied', 605, 'برای من فرقی نمی‌کنه.', 'Für mich macht das keinen Unterschied.', NULL, 4),
  ('مسئله‌ای نیست', 'mas''ale-i nist', 'Kein Problem', 605, 'اگر دیر کنی هم مسئله‌ای نیست.', 'Wenn du dich verspätest, ist das kein Problem.', NULL, 4),
  ('مسلمه', 'mosallame', 'Sicher / Zweifellos', 605, 'مسلمه که حق با توست.', 'Sicher hast du recht.', NULL, 4),
  ('مشکلی نداره', 'moshkeli nadâre', 'Kein Problem', 605, 'مشکلی نداره، من صبر می‌کنم.', 'Kein Problem, ich warte.', NULL, 4),
  ('معلومه', 'ma''lume', 'Klar / Selbstverständlich', 605, 'معلومه که کمکت می‌کنم.', 'Klar helfe ich dir.', NULL, 4),
  ('مهم نیست', 'mohem nist', 'Nicht wichtig', 605, 'مهم نیست، فراموشش کن.', 'Nicht wichtig, vergiss es.', NULL, 4),
  ('می‌خوام', 'mikhâm', 'Ich will', 605, 'می‌خوام فارسی یاد بگیرم.', 'Ich will Persisch lernen.', NULL, 4),
  ('می‌دونم', 'midunam', 'Ich weiß', 605, 'می‌دونم، خودم دیدم.', 'Ich weiß, ich hab es selbst gesehen.', NULL, 4),
  ('می‌دونی', 'miduni', 'Weißt du', 605, 'می‌دونی خانه‌اش کجاست؟', 'Weißt du, wo sein Haus ist?', NULL, 4),
  ('می‌شه دیگه', 'mishe dige', 'Das klappt schon', 605, 'یک کم تلاش کن، می‌شه دیگه.', 'Streng dich etwas an, das klappt schon.', NULL, 4),
  ('نمی‌خوام', 'nemikhâm', 'Ich will nicht', 605, 'نمی‌خوام دیر کنم.', 'Ich will mich nicht verspäten.', NULL, 4),
  ('نمی‌دونم', 'nemidunam', 'Ich weiß nicht', 605, 'نمی‌دونم چی بگم.', 'Ich weiß nicht, was ich sagen soll.', NULL, 4),
  ('نه بابا', 'na bâbâ', 'Ach was! / Nein wirklich?', 605, 'نه بابا! واقعاً این‌طور شد؟', 'Ach was! Ist das wirklich so passiert?', NULL, 4),
  ('هر چی تو بگی', 'har chi to begi', 'Wie du meinst', 605, 'باشه، هر چی تو بگی.', 'Okay, wie du meinst.', NULL, 4),
  ('همینطوره', 'hamintore', 'Genau so ist es', 605, 'بله، همینطوره.', 'Ja, genau so ist es.', NULL, 4),
  ('همینه دیگه', 'hamine dige', 'Das ist halt so', 605, 'زندگی همینه دیگه.', 'So ist das Leben halt.', NULL, 4),
  ('هنوز نه', 'hanuz na', 'Noch nicht', 605, 'ـ تمام شد؟ ـ هنوز نه.', '– Fertig? – Noch nicht.', NULL, 4),
  ('ول کن بابا', 'vel kon bâbâ', 'Lass es / Hör auf', 605, 'ول کن بابا، ارزشش را ندارد.', 'Lass es doch, das ist es nicht wert.', NULL, 4),
  ('ولش کن', 'velesh kon', 'Lass ihn/es', 605, 'ولش کن، خودش درست می‌شود.', 'Lass es, das regelt sich von selbst.', NULL, 4),
  ('ولم کن بابا', 'velam kon bâbâ', 'Lass mich in Ruhe', 605, 'خسته‌ام، ولم کن بابا.', 'Ich bin müde, lass mich in Ruhe.', NULL, 4),
  ('چه بخوای', 'che bekhây', 'Was auch immer du willst', 605, 'چه بخوای انجامش می‌دهم.', 'Was auch immer du willst, ich tue es.', NULL, 4),
  ('چه عجب', 'che ajab', 'Na endlich!', 605, 'چه عجب! بالاخره آمدی.', 'Na endlich! Du bist ja doch gekommen.', NULL, 4),
  ('چه نخوای', 'che nakhây', 'Was du nicht willst', 605, 'چه نخوای هم باید قبول کنی.', 'Auch was du nicht willst, musst du akzeptieren.', NULL, 4),
  ('چون', 'chun', 'weil', 605, 'نیامدم چون مریض بودم.', 'Ich kam nicht, weil ich krank war.', NULL, 4),
  ('چونکه', 'chunke', 'weil / da', 605, 'خوشحالم چونکه تو اینجایی.', 'Ich bin froh, weil du hier bist.', NULL, 4),
  ('چی بگم', 'chi begam', 'Was soll ich sagen', 605, 'چی بگم، واقعاً متأسفم.', 'Was soll ich sagen, es tut mir wirklich leid.', NULL, 4),
  ('چی شده', 'chi shode', 'Was ist passiert?', 605, 'چی شده؟ چرا ناراحتی؟', 'Was ist passiert? Warum bist du traurig?', NULL, 4),
  ('کاری نداره', 'kâri nadâre', 'Kein Problem / easy', 605, 'این کار اصلاً کاری نداره.', 'Das ist überhaupt nicht schwer.', NULL, 4),
  ('کاری نداری', 'kâri nadâri', 'Sonst noch was? (Tel.-Abschied)', 605, 'خب، من رفتم؛ کاری نداری؟', 'Also, ich gehe dann; brauchst du sonst noch was?', NULL, 4),
  ('یک بار دیگه', 'yek bâr-e dige', 'Noch einmal', 605, 'یک بار دیگه توضیح بده.', 'Erklär es noch einmal.', NULL, 4),
  -- L606
  ('حالتو می‌گیرم', 'hâleto migiram', 'Ich mach dich fertig', 606, 'شوخی‌شوخی گفت «حالتو می‌گیرم»، بعد خندیدیم.', 'Scherzhaft sagte er „dir zeig ich''s", dann lachten wir.', NULL, 4),
  ('حالم گرفته', 'hâlam gerefte', 'Ich bin schlecht drauf', 606, 'از این خبر حالم گرفته.', 'Diese Nachricht hat mich schlecht drauf gemacht.', NULL, 4),
  ('حوصله ندارم', 'hosele nadâram', 'Ich hab keine Lust', 606, 'امروز اصلاً حوصله ندارم.', 'Heute habe ich überhaupt keine Lust.', NULL, 4),
  ('خستمه', 'khastame', 'Ich bin müde', 606, 'خیلی کار کردم، خستمه.', 'Ich habe viel gearbeitet, ich bin müde.', NULL, 4),
  ('خوشمزس', 'khoshmazas', 'Es ist lecker', 606, 'این غذا خیلی خوشمزس.', 'Dieses Essen ist sehr lecker.', NULL, 4),
  ('دلم گرفته', 'delam gerefte', 'Ich bin bedrückt', 606, 'امروز دلم گرفته.', 'Heute bin ich bedrückt.', 'wörtl. „Mein Herz ist beklommen“', 4),
  ('سردمه', 'sardame', 'Mir ist kalt', 606, 'پنجره را ببند، سردمه.', 'Mach das Fenster zu, mir ist kalt.', NULL, 4),
  ('سرم شلوغه', 'saram sholughe', 'Ich hab viel zu tun', 606, 'این هفته خیلی سرم شلوغه.', 'Diese Woche habe ich sehr viel zu tun.', 'wörtl. „Mein Kopf ist voll“', 4),
  ('شکمو', 'shekamu', 'Verfressen / Vielfraß', 606, 'برادرم خیلی شکمو است.', 'Mein Bruder ist ein richtiger Vielfraß.', NULL, 4),
  ('عمراً', 'omran', 'Niemals / Auf keinen Fall', 606, 'عمراً دیگر آنجا بروم.', 'Niemals gehe ich da nochmal hin.', NULL, 4),
  ('هیچی', 'hichi', 'Nichts', 606, 'ـ چی شده؟ ـ هیچی، مهم نیست.', '– Was ist los? – Nichts, nicht wichtig.', NULL, 4),
  ('گرسنمه', 'gorosname', 'Ich bin hungrig', 606, 'بریم ناهار، گرسنمه.', 'Lass uns Mittag essen, ich bin hungrig.', NULL, 4),
  ('گرممه', 'garmame', 'Mir ist warm', 606, 'کولر را روشن کن، گرممه.', 'Mach die Klimaanlage an, mir ist warm.', NULL, 4),
  ('گشنمه', 'goshname', 'Ich hab Hunger', 606, 'از صبح چیزی نخوردم، گشنمه.', 'Ich habe seit dem Morgen nichts gegessen, ich habe Hunger.', NULL, 4),
  -- L607
  ('آشغال', 'âshghâl', 'Müll / Abschaum', 607, 'گفتن «آشغال» به یک نفر سخت توهین‌آمیز است.', 'Jemanden „Abschaum" zu nennen ist schwer beleidigend.', NULL, 3),
  ('احمق', 'ahmagh', 'Dummkopf', 607, 'به‌جای «احمق» بهتر است محترمانه صحبت کنیم.', 'Statt „Dummkopf" sprechen wir besser respektvoll.', NULL, 3),
  ('برو پی کارت', 'boro pey-e kâret', 'Kümmer dich um deine Sachen', 607, '«برو پی کارت» یعنی دست از سر کسی بردار، ولی لحنش تند است.', '„Kümmer dich um deine Sachen" heißt, jemanden in Ruhe zu lassen, klingt aber schroff.', NULL, 3),
  ('به تو مربوط نیست', 'be to marbut nist', 'Das geht dich nichts an', 607, 'به‌جای «به تو مربوط نیست» می‌توان مؤدب‌تر پاسخ داد.', 'Statt „das geht dich nichts an" kann man höflicher antworten.', NULL, 3),
  ('به تو چه', 'be to che', 'Was geht''s dich an?', 607, 'مؤدبانه نیست که بگویی «به تو چه».', 'Es ist unhöflich zu sagen „Was geht''s dich an".', NULL, 3),
  ('بی عرضه', 'bi orze', 'Versager / unfähig', 607, 'به کسی نگو بی‌عرضه؛ این توهین است.', 'Nenn niemanden „unfähig"; das ist eine Beleidigung.', NULL, 3),
  ('بی وجدان', 'bi vejdân', 'Gewissenlos', 607, '«بی‌وجدان» خواندن دیگران توهین است.', 'Andere „gewissenlos" zu nennen ist eine Beleidigung.', NULL, 3),
  ('تو گه می‌خوری', 'to goh mikhori', 'du laberst Mist', 607, 'این جمله یک دشنام بسیار زشت است.', 'Dieser Satz ist eine sehr vulgäre Beschimpfung.', 'sehr vulgär', 3),
  ('خاک بر سرت', 'khâk bar saret', 'Schande über dich', 607, '«خاک بر سرت» نفرینی رایج اما بسیار توهین‌آمیز است.', '„Schande über dich" ist ein gängiger, aber sehr beleidigender Fluch.', 'wörtl. „Erde auf deinen Kopf“', 3),
  ('خر', 'khar', 'Esel', 607, '«خر» در مقام دشنام یعنی نادان، و توهین‌آمیز است.', '„Esel" als Schimpfwort bedeutet „dumm" und ist beleidigend.', NULL, 3),
  ('خفه شو', 'khafe sho', 'Halt den Mund', 607, '«خفه شو» بسیار بی‌ادبانه است؛ بهتر است گفته نشود.', '„Halt den Mund" ist sehr unhöflich; besser nicht sagen.', NULL, 3),
  ('دهنت رو ببند', 'dahanet ro beband', 'Halt den Mund', 607, 'این عبارت پرخاشگرانه است و بهتر است از آن پرهیز شود.', 'Dieser Ausdruck ist aggressiv und sollte vermieden werden.', 'wörtl. „Schließ deinen Mund“', 3),
  ('دیوث', 'deyus', 'schwere Beleidigung (Zuhälter/Hahnrei)', 607, 'این کلمه دشنامی بسیار رکیک است و کاربردش پسندیده نیست.', 'Dieses Wort ist eine sehr vulgäre Beschimpfung und sollte nicht verwendet werden.', 'sehr vulgär', 3),
  ('زهر مار', 'zahr-e mâr', 'Halt den Mund!', 607, '«زهر مار» واکنشی خشن و بی‌ادبانه است.', '„Halt den Mund" (wörtl. „Schlangengift") ist eine grobe, unhöfliche Reaktion.', 'wörtl. „Schlangengift“', 3),
  ('غلط کردی', 'ghalat kardi', 'Du hast Mist gebaut', 607, '«غلط کردی» لحنی بسیار تند و تحقیرآمیز دارد.', '„Du hast Mist gebaut" hat einen sehr scharfen, herabsetzenden Ton.', NULL, 3),
  ('مرتیکه الاغ', 'martike olâgh', 'Du Esel', 607, '«مرتیکه الاغ» ناسزایی رایج است و بهتر است گفته نشود.', '„Du Esel" ist ein gängiges Schimpfwort und sollte vermieden werden.', NULL, 3),
  ('مرتیکه خر', 'martike khar', 'Du Esel', 607, 'این عبارت توهین‌آمیز است؛ از آن استفاده نکن.', 'Dieser Ausdruck ist beleidigend; benutze ihn nicht.', NULL, 3),
  ('مرتیکه نفهم', 'martike nafahm', 'Du Begriffsstutziger', 607, 'گفتن «نفهم» به دیگران بی‌ادبی است.', 'Andere „begriffsstutzig" zu nennen ist unhöflich.', NULL, 3),
  ('پدر سوخته', 'pedar-sukhte', 'Schlingel / Schlitzohr', 607, '«پدر سوخته» اغلب شوخی و محبت‌آمیز برای بچه‌ی شیطان است.', '„Pedar-sukhte" ist oft scherzhaft-liebevoll für ein freches Kind.', 'wörtl. „verbrannter Vater“', 3),
  ('پدر سگ', 'pedar-sag', 'Schimpfwort', 607, '«پدر سگ» گاهی شوخی و گاهی دشنام است؛ با احتیاط.', '„Pedar-sag" ist mal scherzhaft, mal Schimpfwort; mit Vorsicht zu verwenden.', 'wörtl. „Hundevater“', 3),
  ('پفیوز', 'pofyuz', 'Nichtsnutz / willenlos', 607, '«پفیوز» دشنامی زننده است.', '„Nichtsnutz" ist ein anstößiges Schimpfwort.', 'vulgär', 3),
  ('چه خاکی به سرم بریزم', 'che khâki be saram berizam', 'Was soll ich nur tun! (verzweifelt)', 607, 'وقتی کسی درمانده است می‌گوید «چه خاکی به سرم بریزم».', 'Wenn jemand verzweifelt ist, sagt er „Was soll ich nur tun".', NULL, 3),
  ('چه غلطا', 'che ghalatâ', 'Was erlaubst du dir!', 607, '«چه غلطا» عبارتی تند و گله‌مندانه است.', '„Was erlaubst du dir" ist ein scharfer, vorwurfsvoller Ausdruck.', NULL, 3),
  ('کثافت', 'kesâfat', 'Dreckskerl', 607, '«کثافت» دشنامی شدید است.', '„Dreckskerl" ist ein heftiges Schimpfwort.', NULL, 3),
  ('کون گشاد', 'kun goshâd', 'Faulpelz', 607, '«کون گشاد» اصطلاحی عامیانه و بی‌ادبانه برای آدم تنبل است.', 'Dieser derbe Ausdruck steht umgangssprachlich für einen faulen Menschen.', 'vulgär', 3),
  ('گمشو', 'gomsho', 'Hau ab / Verschwinde', 607, '«گمشو» دستوری خشن و توهین‌آمیز است.', '„Hau ab" ist ein grober, beleidigender Befehl.', NULL, 3),
  ('گه خوردی', 'goh khordi', 'du hast was Falsches gesagt', 607, 'این عبارت بسیار رکیک است و نباید به کار رود.', 'Dieser Ausdruck ist sehr vulgär und sollte nicht verwendet werden.', 'sehr vulgär, wörtl. „du hast Sch… gegessen“', 3)
) as v(hangul, romanisierung, deutsch, lektion_nummer, beispielsatz_ko, beispielsatz_de, hinweis, haeufigkeit)
on conflict (user_id, hangul, lektion_nummer) do update set
  romanisierung=excluded.romanisierung, deutsch=excluded.deutsch,
  beispielsatz_ko=excluded.beispielsatz_ko, beispielsatz_de=excluded.beispielsatz_de,
  hinweis=excluded.hinweis, haeufigkeit=excluded.haeufigkeit;
