-- ============================================================================
-- Persische Alltagsphrasen – Seed (Teil 6, 224 Einträge, Lektionen 601–607)
-- Quelle: handschriftliche Phrasensammlung (PDF), transkribiert & dedupliziert.
-- Schema-konform zu vocab_items / lessons. Spalte hangul = Persisch-Schrift,
-- beispielsatz_ko ungenutzt (keine Beispielsätze), literal -> hinweis.
-- Unabhängig vom 101–499-Frequenz-Seed; eigener Bereich 601–699, idempotent.
-- Im Supabase SQL Editor ausführen. App-Login-E-Mail: jreitzenstein@gmail.com
-- ============================================================================

-- 1) Lektionen (Teil 6)
insert into public.lessons (user_id, buch, lektion_nummer, titel, beschreibung, reihenfolge)
select (select id from auth.users where email='jreitzenstein@gmail.com'), v.buch, v.lektion_nummer, v.titel, v.beschreibung, v.reihenfolge
from (values
  (6, 601, 'Begrüßung & Höflichkeit', 'Teil 6 – Alltag & Redewendungen', 601),
  (6, 602, 'Zeit & Datum', 'Teil 6 – Alltag & Redewendungen', 602),
  (6, 603, 'Fragen', 'Teil 6 – Alltag & Redewendungen', 603),
  (6, 604, 'Aufforderungen', 'Teil 6 – Alltag & Redewendungen', 604),
  (6, 605, 'Alltag & Ausdrücke', 'Teil 6 – Alltag & Redewendungen', 605),
  (6, 606, 'Gefühle & Zustände', 'Teil 6 – Alltag & Redewendungen', 606),
  (6, 607, 'Umgangssprache: Beleidigungen (Vorsicht)', 'Teil 6 – Alltag & Redewendungen', 607)
) as v(buch, lektion_nummer, titel, beschreibung, reihenfolge)
on conflict (user_id, lektion_nummer) do update
  set titel=excluded.titel, buch=excluded.buch, beschreibung=excluded.beschreibung, reihenfolge=excluded.reihenfolge;

-- 2) Vorherige Phrasen-Seeds dieses Nutzers entfernen (idempotent, Bereich 601–699).
delete from public.vocab_items where user_id = (select id from auth.users where email='jreitzenstein@gmail.com') and lektion_nummer between 601 and 699;

-- 3) 224 Phrasen
insert into public.vocab_items
  (user_id, hangul, romanisierung, deutsch, lektion_nummer, beispielsatz_ko, beispielsatz_de, hinweis, haeufigkeit)
select (select id from auth.users where email='jreitzenstein@gmail.com'), v.*
from (values
  ('سلام', 'salām', 'Hallo', 601, 'سلام، حال شما چطور است؟', 'Hallo, wie geht es Ihnen?', NULL, 5),
  ('صبح بخیر', 'sobh bekheir', 'Guten Morgen', 601, 'صبح بخیر! خوب خوابیدی؟', 'Guten Morgen! Hast du gut geschlafen?', NULL, 5),
  ('روز بخیر', 'ruz bekheir', 'Guten Tag', 601, 'روز بخیر، خوش آمدید.', 'Guten Tag, willkommen.', NULL, 5),
  ('شب بخیر', 'shab bekheir', 'Gute Nacht', 601, 'شب بخیر، فردا می‌بینمت.', 'Gute Nacht, bis morgen.', NULL, 5),
  ('خداحافظ', 'khodā hāfez', 'Auf Wiedersehen', 601, 'خداحافظ، مواظب خودت باش.', 'Auf Wiedersehen, pass auf dich auf.', NULL, 5),
  ('چطوری', 'chetori', 'Wie geht''s?', 601, 'سلام، چطوری؟ چه خبر؟', 'Hallo, wie geht''s? Was gibt''s Neues?', NULL, 5),
  ('خوبی', 'khubi', 'Alles gut? / Geht''s dir gut?', 601, 'خوبی؟ چند وقته ندیدمت.', 'Geht''s dir gut? Ich hab dich lange nicht gesehen.', NULL, 5),
  ('خوشحالم', 'khoshhālam', 'Ich freue mich / Ich bin froh', 601, 'از دیدنت خیلی خوشحالم.', 'Ich freue mich sehr, dich zu sehen.', NULL, 5),
  ('خوشحال شدم', 'khoshhāl shodam', 'Hat mich gefreut', 601, 'از آشنایی با شما خوشحال شدم.', 'Hat mich gefreut, Sie kennenzulernen.', NULL, 5),
  ('خسته نباشین', 'khaste nabāshin', 'Gute Arbeit! (Grußformel)', 601, 'سلام، خسته نباشین! کارتون تمام شد؟', 'Hallo, gute Arbeit! Sind Sie fertig?', 'wörtl. „Mögen Sie nicht müde sein“', 5),
  ('ببخشید', 'bebakhshid', 'Entschuldigung', 601, 'ببخشید، ساعت چند است؟', 'Entschuldigung, wie spät ist es?', NULL, 5),
  ('شرمنده', 'sharmande', 'Tut mir leid / beschämt', 601, 'شرمنده که دیر کردم.', 'Tut mir leid, dass ich zu spät bin.', NULL, 5),
  ('خواهش می‌کنم', 'khāhesh mikonam', 'Bitte / Gern geschehen', 601, 'ـ ممنون! ـ خواهش می‌کنم.', '– Danke! – Gern geschehen.', NULL, 5),
  ('قابلی نداره', 'ghābeli nadāre', 'Keine Ursache', 601, 'ـ ممنون بابت کمک. ـ قابلی نداره.', '– Danke für die Hilfe. – Keine Ursache.', 'wörtl. „Es ist nichts wert“', 5),
  ('قربان شما', 'ghorbān-e shomā', 'Sehr verbunden (höflich)', 601, 'لطف دارید، قربان شما.', 'Sehr freundlich, ich bin Ihnen verbunden.', 'wörtl. „Ihr Opfer (sei ich)“', 5),
  ('دست شما درد نکنه', 'dast-e shomā dard nakone', 'Vielen Dank', 601, 'دست شما درد نکنه، خیلی کمک کردید.', 'Vielen Dank, Sie haben sehr geholfen.', 'wörtl. „Möge Ihre Hand nicht schmerzen“', 5),
  ('مرسی', 'mersi', 'Danke', 601, 'مرسی که اومدی.', 'Danke, dass du gekommen bist.', NULL, 5),
  ('ممنون', 'mamnun', 'Danke', 601, 'ممنون از وقتی که گذاشتی.', 'Danke für deine Zeit.', NULL, 5),
  ('متشکرم', 'moteshakkeram', 'Ich danke Ihnen', 601, 'از همراهی‌تان متشکرم.', 'Ich danke Ihnen für Ihre Begleitung.', NULL, 5),
  ('بفرمایید', 'befarmāyid', 'Bitte schön / Hier bitte', 601, 'بفرمایید، این هم چای شما.', 'Bitte schön, hier ist Ihr Tee.', NULL, 5),
  ('خدا رو شکر', 'khodā ro shokr', 'Gott sei Dank', 601, 'خدا رو شکر که سالم رسیدی.', 'Gott sei Dank bist du heil angekommen.', NULL, 5),
  ('به خدا', 'be khodā', 'Bei Gott / Ich schwöre', 601, 'به خدا من کاری نکردم.', 'Bei Gott, ich habe nichts getan.', NULL, 5),
  ('پناه بر خدا', 'panāh bar khodā', 'Um Gottes Willen', 601, 'پناه بر خدا، چه اتفاقی افتاده؟', 'Um Gottes Willen, was ist passiert?', NULL, 5),
  ('باشه', 'bāshe', 'Okay / Einverstanden', 601, 'باشه، فردا بهت زنگ می‌زنم.', 'Okay, ich rufe dich morgen an.', NULL, 5),
  ('آره', 'āre', 'Ja', 601, 'آره، من هم می‌آم.', 'Ja, ich komme auch mit.', NULL, 5),
  ('بله', 'bale', 'Ja (höflich)', 601, 'بله، حتماً در خدمتم.', 'Ja, sehr gern, ich stehe zur Verfügung.', NULL, 5),
  ('نه', 'na', 'Nein', 601, 'نه، ممنون، سیر هستم.', 'Nein danke, ich bin satt.', NULL, 5),
  ('نخیر', 'nakheir', 'Nein (bestimmt/höflich)', 601, 'نخیر، این درست نیست.', 'Nein, das stimmt nicht.', NULL, 5),
  ('قدمتون روی چشم', 'ghadametun ru cheshm', 'Herzlich willkommen', 601, 'بیایید تو، قدمتون روی چشم.', 'Kommen Sie herein, herzlich willkommen.', 'wörtl. „Ihr Schritt auf mein Auge“', 5),
  ('چشم', 'cheshm', 'Gerne / Mach ich', 601, 'ـ لطفاً در را ببند. ـ چشم.', '– Mach bitte die Tür zu. – Gerne, mach ich.', 'wörtl. „Auge“ = zu Befehl', 5),
  ('امروز', 'emruz', 'heute', 602, 'امروز هوا خیلی خوب است.', 'Heute ist das Wetter sehr schön.', NULL, 4),
  ('امروز صبح', 'emruz sobh', 'heute Morgen', 602, 'امروز صبح زود بیدار شدم.', 'Heute Morgen bin ich früh aufgewacht.', NULL, 4),
  ('امروز ظهر', 'emruz zohr', 'heute Mittag', 602, 'امروز ظهر با هم ناهار بخوریم.', 'Lass uns heute Mittag zusammen essen.', NULL, 4),
  ('امشب', 'emshab', 'heute Abend', 602, 'امشب خانه می‌مانم.', 'Heute Abend bleibe ich zu Hause.', NULL, 4),
  ('فردا', 'fardā', 'morgen', 602, 'فردا امتحان دارم.', 'Morgen habe ich eine Prüfung.', NULL, 4),
  ('فردا صبح', 'fardā sobh', 'morgen früh', 602, 'فردا صبح زود حرکت می‌کنیم.', 'Morgen früh brechen wir auf.', NULL, 4),
  ('فردا ظهر', 'fardā zohr', 'morgen Mittag', 602, 'فردا ظهر وقت داری؟', 'Hast du morgen Mittag Zeit?', NULL, 4),
  ('فردا شب', 'fardā shab', 'morgen Abend', 602, 'فردا شب مهمان داریم.', 'Morgen Abend haben wir Gäste.', NULL, 4),
  ('دیروز', 'diruz', 'gestern', 602, 'دیروز تو را در بازار دیدم.', 'Gestern habe ich dich auf dem Markt gesehen.', NULL, 4),
  ('دیروز صبح', 'diruz sobh', 'gestern Morgen', 602, 'دیروز صبح باران می‌بارید.', 'Gestern Morgen hat es geregnet.', NULL, 4),
  ('دیروز ظهر', 'diruz zohr', 'gestern Mittag', 602, 'دیروز ظهر چه خوردی؟', 'Was hast du gestern Mittag gegessen?', NULL, 4),
  ('دیشب', 'dishab', 'gestern Abend', 602, 'دیشب خوب نخوابیدم.', 'Gestern Abend habe ich schlecht geschlafen.', NULL, 4),
  ('پریروز', 'pariruz', 'vorgestern', 602, 'پریروز به تهران رفتم.', 'Vorgestern bin ich nach Teheran gefahren.', NULL, 4),
  ('پریشب', 'parishab', 'vorgestern Abend', 602, 'پریشب تا دیروقت بیدار بودم.', 'Vorgestern Abend war ich bis spät wach.', NULL, 4),
  ('پس فردا', 'pasfardā', 'übermorgen', 602, 'پس فردا تعطیل است.', 'Übermorgen ist frei.', NULL, 4),
  ('هفته‌ی آینده', 'hafte-ye āyande', 'nächste Woche', 602, 'هفته‌ی آینده سفر می‌روم.', 'Nächste Woche verreise ich.', NULL, 4),
  ('هفته‌ی پیش', 'hafte-ye pish', 'letzte Woche', 602, 'هفته‌ی پیش او را دیدم.', 'Letzte Woche habe ich ihn gesehen.', NULL, 4),
  ('هفته‌ی گذشته', 'hafte-ye gozashte', 'vergangene Woche', 602, 'هفته‌ی گذشته خیلی شلوغ بود.', 'Die vergangene Woche war sehr voll.', NULL, 4),
  ('ماه آینده', 'māh-e āyande', 'nächster Monat', 602, 'ماه آینده اسباب‌کشی می‌کنیم.', 'Nächsten Monat ziehen wir um.', NULL, 4),
  ('ماه پیش', 'māh-e pish', 'letzter Monat', 602, 'ماه پیش کار جدیدی شروع کردم.', 'Letzten Monat habe ich einen neuen Job angefangen.', NULL, 4),
  ('ماه گذشته', 'māh-e gozashte', 'vergangener Monat', 602, 'ماه گذشته باران زیادی بارید.', 'Im vergangenen Monat hat es viel geregnet.', NULL, 4),
  ('الآن', 'alān', 'jetzt', 602, 'الآن نمی‌توانم صحبت کنم.', 'Jetzt kann ich nicht sprechen.', NULL, 4),
  ('همین حالا', 'hamin hālā', 'genau jetzt / sofort', 602, 'همین حالا بیا اینجا.', 'Komm sofort her.', NULL, 4),
  ('هر روز', 'har ruz', 'jeden Tag', 602, 'هر روز پیاده‌روی می‌کنم.', 'Ich gehe jeden Tag spazieren.', NULL, 4),
  ('روز به روز', 'ruz be ruz', 'Tag für Tag', 602, 'حالش روز به روز بهتر می‌شود.', 'Es geht ihm Tag für Tag besser.', NULL, 4),
  ('شبانه روز', 'shabāne ruz', 'rund um die Uhr', 602, 'این داروخانه شبانه روز باز است.', 'Diese Apotheke hat rund um die Uhr geöffnet.', 'wörtl. „Nacht und Tag“', 4),
  ('تا بعد', 'tā ba''d', 'bis später', 602, 'فعلاً کاری ندارم، تا بعد.', 'Ich hab gerade nichts zu tun, bis später.', NULL, 4),
  ('تا فردا', 'tā fardā', 'bis morgen', 602, 'خسته‌ام، تا فردا.', 'Ich bin müde, bis morgen.', NULL, 4),
  ('تا هفته آینده', 'tā hafte āyande', 'bis nächste Woche', 602, 'قرارمان باشد تا هفته آینده.', 'Bleiben wir bei nächster Woche, bis dann.', NULL, 4),
  ('کو', 'ku', 'Wo ist es?', 603, 'کیفم کو؟ همین‌جا بود.', 'Wo ist meine Tasche? Sie war doch hier.', NULL, 4),
  ('کجایی', 'kojāyi', 'Wo bist du?', 603, 'الو، کجایی؟ منتظرتم.', 'Hallo, wo bist du? Ich warte.', NULL, 4),
  ('کجاس', 'kojās', 'Wo ist er/sie/es?', 603, 'کلید کجاس؟', 'Wo ist der Schlüssel?', NULL, 4),
  ('کیه', 'kie', 'Wer ist es?', 603, 'در می‌زنند، کیه؟', 'Es klopft, wer ist da?', NULL, 4),
  ('این کیه', 'in kie', 'Wer ist das?', 603, 'این کیه توی عکس؟', 'Wer ist das auf dem Foto?', NULL, 4),
  ('یعنی چی', 'ya''ni chi', 'Was bedeutet das?', 603, 'این کلمه یعنی چی؟', 'Was bedeutet dieses Wort?', NULL, 4),
  ('یعنی چه', 'ya''ni che', 'Was soll das heißen?', 603, 'این کارت یعنی چه؟', 'Was soll dieses Verhalten heißen?', NULL, 4),
  ('این چیه', 'in chie', 'Was ist das?', 603, 'ببخشید، این چیه؟', 'Entschuldigung, was ist das?', NULL, 4),
  ('این چیه دیگه', 'in chie dige', 'Was ist das denn?', 603, 'این چیه دیگه روی میز؟', 'Was ist das denn da auf dem Tisch?', NULL, 4),
  ('این چنده', 'in chande', 'Wie viel kostet das?', 603, 'ببخشید، این چنده؟', 'Entschuldigung, wie viel kostet das?', NULL, 4),
  ('چقدر می‌شه؟', 'cheghadr mishe', 'Wie viel macht das?', 603, 'همه‌اش چقدر می‌شه؟', 'Wie viel macht das alles zusammen?', NULL, 4),
  ('چقدر بدم؟', 'cheghadr bedam', 'Wie viel soll ich geben?', 603, 'چقدر بدم خدمتتون؟', 'Wie viel soll ich Ihnen geben?', NULL, 4),
  ('چقدر تقدیم کنم؟', 'cheghadr taghdim konam', 'Wie viel darf ich geben? (höflich)', 603, 'چقدر تقدیم کنم؟', 'Wie viel darf ich Ihnen entrichten?', NULL, 4),
  ('چرا', 'cherā', 'Warum', 603, 'چرا دیروز نیامدی؟', 'Warum bist du gestern nicht gekommen?', NULL, 4),
  ('چه خبر', 'che khabar', 'Was gibt''s Neues?', 603, 'سلام، چه خبر؟', 'Hallo, was gibt''s Neues?', NULL, 4),
  ('خبری نیست', 'khabari nist', 'Nichts Neues', 603, 'فعلاً خبری نیست، همه چیز آرام است.', 'Im Moment nichts Neues, alles ruhig.', NULL, 4),
  ('چند تا', 'chand tā', 'Wie viele?', 603, 'چند تا بلیط می‌خوای؟', 'Wie viele Tickets willst du?', NULL, 4),
  ('چند سالته', 'chand sālete', 'Wie alt bist du?', 603, 'ببخشید، چند سالته؟', 'Sag mal, wie alt bist du?', NULL, 4),
  ('می‌فهمی؟', 'mifahmi', 'Verstehst du?', 603, 'منظورم را می‌فهمی؟', 'Verstehst du, was ich meine?', NULL, 4),
  ('مطمئنی', 'motma''eni', 'Bist du sicher?', 603, 'مطمئنی که در را بستی؟', 'Bist du sicher, dass du die Tür zugemacht hast?', NULL, 4),
  ('تعارف می‌کنی؟', 'ta''ārof mikoni', 'Machst du Ta''arof? (Höflichkeitsspiel)', 603, 'راحت باش، تعارف می‌کنی؟', 'Fühl dich frei, machst du etwa Ta''arof?', NULL, 4),
  ('چه جوری', 'che juri', 'Wie? / Wie das?', 603, 'این دستگاه چه جوری کار می‌کند؟', 'Wie funktioniert dieses Gerät?', NULL, 4),
  ('چیکار می‌کنی', 'chikār mikoni', 'Was machst du?', 603, 'الان داری چیکار می‌کنی؟', 'Was machst du gerade?', NULL, 4),
  ('چی میگی', 'chi migi', 'Was sagst du?', 603, 'چی میگی؟ نشنیدم.', 'Was sagst du? Ich hab''s nicht gehört.', NULL, 4),
  ('چی گفتی', 'chi gofti', 'Was hast du gesagt?', 603, 'ببخشید، چی گفتی؟', 'Entschuldigung, was hast du gesagt?', NULL, 4),
  ('راس میگی', 'rāst migi', 'Echt? / Im Ernst?', 603, 'راس میگی؟ باورم نمی‌شه.', 'Echt? Das glaub ich nicht.', NULL, 4),
  ('حالا که چی', 'hālā ke chi', 'Na und?', 603, 'خب دیر شد، حالا که چی؟', 'Na ja, es ist spät geworden, na und?', NULL, 4),
  ('بیا', 'biā', 'Komm', 604, 'بیا، با هم برویم.', 'Komm, lass uns zusammen gehen.', NULL, 4),
  ('بیا اینجا', 'biā injā', 'Komm her', 604, 'بیا اینجا، باید حرف بزنیم.', 'Komm her, wir müssen reden.', NULL, 4),
  ('بیا تو', 'biā tu', 'Komm rein', 604, 'در باز است، بیا تو.', 'Die Tür ist offen, komm rein.', NULL, 4),
  ('برو', 'boro', 'Geh', 604, 'برو، دیرت می‌شود.', 'Geh, sonst kommst du zu spät.', NULL, 4),
  ('برو بیرون', 'boro birun', 'Geh raus', 604, 'لطفاً یک لحظه برو بیرون.', 'Geh bitte einen Moment raus.', NULL, 4),
  ('بگو', 'begu', 'Sag', 604, 'هر چه می‌خواهی بگو.', 'Sag, was du willst.', NULL, 4),
  ('نگو', 'nagu', 'Sag nicht', 604, 'به کسی نگو.', 'Sag es niemandem.', NULL, 4),
  ('بگو دیگه', 'begu dige', 'Sag schon', 604, 'زود باش، بگو دیگه!', 'Komm schon, sag schon!', NULL, 4),
  ('دوباره بگو', 'dobāre begu', 'Sag nochmal', 604, 'نفهمیدم، دوباره بگو.', 'Ich hab''s nicht verstanden, sag nochmal.', NULL, 4),
  ('بکن', 'bokon', 'Mach / Tu', 604, 'این کار را همین حالا بکن.', 'Mach diese Aufgabe sofort.', NULL, 4),
  ('نکن', 'nakon', 'Lass das', 604, 'این کار را نکن، خطرناک است.', 'Lass das, es ist gefährlich.', NULL, 4),
  ('بده من', 'bede man', 'Gib mir', 604, 'نمک را بده من، لطفاً.', 'Gib mir bitte das Salz.', NULL, 4),
  ('بگیرش', 'begiresh', 'Nimm es / Schnapp ihn', 604, 'بیا، این کتاب را بگیرش.', 'Hier, nimm dieses Buch.', NULL, 4),
  ('صبر کن', 'sabr kon', 'Warte / Hab Geduld', 604, 'یک لحظه صبر کن، الان می‌آیم.', 'Warte einen Moment, ich komme gleich.', NULL, 4),
  ('عجله کن', 'ajale kon', 'Beeil dich', 604, 'عجله کن، اتوبوس رسید.', 'Beeil dich, der Bus ist da.', NULL, 4),
  ('زود باش', 'zud bāsh', 'Schnell / Beeil dich', 604, 'زود باش، دیر شد.', 'Schnell, es ist spät geworden.', NULL, 4),
  ('بدو', 'bedow', 'Lauf', 604, 'بدو که جا نمانیم.', 'Lauf, damit wir es nicht verpassen.', NULL, 4),
  ('یواش', 'yavāsh', 'Langsam / Sachte', 604, 'یواش برو، جاده لغزنده است.', 'Fahr langsam, die Straße ist glatt.', NULL, 4),
  ('مواظب باش', 'movāzeb bāsh', 'Pass auf / Sei vorsichtig', 604, 'مواظب باش، پله لیز است.', 'Pass auf, die Stufe ist rutschig.', NULL, 4),
  ('اجازه بده', 'ejāze bede', 'Lass mich / Erlaube', 604, 'اجازه بده خودم انجامش بدهم.', 'Lass mich das selbst machen.', NULL, 4),
  ('خجالت بکش', 'khejālat bekesh', 'Schäm dich', 604, 'خجالت بکش، این کار درست نبود.', 'Schäm dich, das war nicht in Ordnung.', NULL, 4),
  ('خجالتم ندین', 'khejālatam nadin', 'Bringt mich nicht in Verlegenheit', 604, 'این‌قدر تعریف نکنید، خجالتم ندین.', 'Lobt mich nicht so, ihr bringt mich in Verlegenheit.', NULL, 4),
  ('غر نزن', 'ghor nazan', 'Meckere nicht', 604, 'این‌قدر غر نزن، درست می‌شود.', 'Meckere nicht so, das wird schon.', NULL, 4),
  ('لاف نزن', 'lāf nazan', 'Prahle nicht', 604, 'لاف نزن، همه می‌دانند.', 'Prahle nicht, das wissen doch alle.', NULL, 4),
  ('پز نده', 'poz nade', 'Gib nicht an', 604, 'این‌قدر پز نده.', 'Gib nicht so an.', NULL, 4),
  ('مزخرف نگو', 'mozakhraf nagu', 'Red keinen Unsinn', 604, 'مزخرف نگو، این‌طور نیست.', 'Red keinen Unsinn, so ist es nicht.', NULL, 4),
  ('چرند نگو', 'charand nagu', 'Red keinen Quatsch', 604, 'چرند نگو، جدی باش.', 'Red keinen Quatsch, sei ernst.', NULL, 4),
  ('دروغ نگو', 'dorugh nagu', 'Lüg nicht', 604, 'به من دروغ نگو.', 'Lüg mich nicht an.', NULL, 4),
  ('کرم نریز', 'kerm nariz', 'Provoziere nicht', 604, 'آرام بنشین و کرم نریز.', 'Sitz still und provoziere nicht.', 'wörtl. „Wirf keine Würmer“', 4),
  ('حرفشم نزن', 'harfesham nazan', 'Kein Wort davon', 604, 'حرفشم نزن، خودم حساب می‌کنم.', 'Kein Wort davon, ich zahle.', NULL, 4),
  ('بخورش', 'bokhoresh', 'Iss es!', 604, 'غذات سرد شد، بخورش.', 'Dein Essen wird kalt, iss es.', NULL, 4),
  ('بزنش', 'bezanesh', 'Schlag ihn!', 604, 'توپ جلوته، بزنش!', 'Der Ball ist vor dir, schieß!', NULL, 4),
  ('آها', 'āhā', 'Aha', 605, 'آها، حالا فهمیدم.', 'Aha, jetzt verstehe ich.', NULL, 4),
  ('خب', 'khob', 'Na ja / Okay', 605, 'خب، از کجا شروع کنیم؟', 'Also, wo fangen wir an?', NULL, 4),
  ('بسیار خب', 'besyār khob', 'Sehr gut / Alles klar', 605, 'بسیار خب، قبول است.', 'Alles klar, einverstanden.', NULL, 4),
  ('خیلی خب', 'kheili khob', 'Sehr gut / Okay', 605, 'خیلی خب، پس فردا می‌بینمت.', 'Okay, dann sehen wir uns morgen.', NULL, 4),
  ('خوبه', 'khube', 'Gut / Passt', 605, 'خوبه، همین کافی است.', 'Gut, das reicht.', NULL, 4),
  ('خیلی بده', 'kheili bade', 'Sehr schlecht', 605, 'هوای امروز خیلی بده.', 'Das Wetter ist heute sehr schlecht.', NULL, 4),
  ('بد نیست', 'bad nist', 'Nicht schlecht', 605, 'این رستوران بد نیست.', 'Dieses Restaurant ist nicht schlecht.', NULL, 4),
  ('دقیقاً', 'daghighan', 'Genau', 605, 'دقیقاً همین را می‌خواستم بگویم.', 'Genau das wollte ich sagen.', NULL, 4),
  ('درسته', 'doroste', 'Richtig / Korrekt', 605, 'درسته، حق با توست.', 'Richtig, du hast recht.', NULL, 4),
  ('همینطوره', 'hamintore', 'Genau so ist es', 605, 'بله، همینطوره.', 'Ja, genau so ist es.', NULL, 4),
  ('همینه دیگه', 'hamine dige', 'Das ist halt so', 605, 'زندگی همینه دیگه.', 'So ist das Leben halt.', NULL, 4),
  ('اینجوری', 'injuri', 'So', 605, 'اینجوری بگیرش که نیفتد.', 'Halt es so, damit es nicht runterfällt.', NULL, 4),
  ('اینطوری نه', 'intori na', 'Nicht so', 605, 'اینطوری نه، بذار نشانت بدهم.', 'Nicht so, lass es mich dir zeigen.', NULL, 4),
  ('چه بخوای', 'che bekhāy', 'Was auch immer du willst', 605, 'چه بخوای انجامش می‌دهم.', 'Was auch immer du willst, ich tue es.', NULL, 4),
  ('چه نخوای', 'che nakhāy', 'Was du nicht willst', 605, 'چه نخوای هم باید قبول کنی.', 'Auch was du nicht willst, musst du akzeptieren.', NULL, 4),
  ('دوباره', 'dobāre', 'Nochmal', 605, 'دوباره امتحان کن.', 'Versuch es nochmal.', NULL, 4),
  ('یک بار دیگه', 'yek bār-e dige', 'Noch einmal', 605, 'یک بار دیگه توضیح بده.', 'Erklär es noch einmal.', NULL, 4),
  ('بسه', 'base', 'Es reicht', 605, 'بسه، دیگر کافی است.', 'Es reicht, genug jetzt.', NULL, 4),
  ('بسه دیگه', 'base dige', 'Jetzt reicht''s', 605, 'بسه دیگه، تمامش کن.', 'Jetzt reicht''s, hör auf.', NULL, 4),
  ('دیگه بسته', 'dige baste', 'Schluss jetzt', 605, 'دیگه بسته، باید برویم.', 'Schluss jetzt, wir müssen los.', NULL, 4),
  ('دیگه نه', 'dige na', 'Nicht mehr', 605, 'نه، دیگه نه، خسته شدم.', 'Nein, nicht mehr, ich bin müde geworden.', NULL, 4),
  ('درست می‌شه', 'dorost mishe', 'Das wird schon', 605, 'نگران نباش، درست می‌شه.', 'Mach dir keine Sorgen, das wird schon.', NULL, 4),
  ('ببینیم چی', 'bebinim chi', 'Mal sehen', 605, 'ببینیم چی پیش می‌آید.', 'Mal sehen, was passiert.', NULL, 4),
  ('می‌شه دیگه', 'mishe dige', 'Das klappt schon', 605, 'یک کم تلاش کن، می‌شه دیگه.', 'Streng dich etwas an, das klappt schon.', NULL, 4),
  ('دیگه نمی‌شه', 'dige nemishe', 'Das geht nicht mehr', 605, 'متأسفم، دیگه نمی‌شه کاری کرد.', 'Tut mir leid, da kann man nichts mehr machen.', NULL, 4),
  ('تقصیر خودته', 'taghsir-e khodete', 'Selber schuld', 605, 'تقصیر خودته که گوش ندادی.', 'Selber schuld, dass du nicht zugehört hast.', NULL, 4),
  ('تقصیر تو', 'taghsir-e to', 'Deine Schuld', 605, 'این تقصیر تو نیست.', 'Das ist nicht deine Schuld.', NULL, 4),
  ('هر چی تو بگی', 'har chi to begi', 'Wie du meinst', 605, 'باشه، هر چی تو بگی.', 'Okay, wie du meinst.', NULL, 4),
  ('بی زحمت', 'bi zahmat', 'Bitte (wenn''s keine Mühe macht)', 605, 'بی زحمت در را ببند.', 'Mach bitte die Tür zu, wenn es keine Mühe macht.', NULL, 4),
  ('چی شده', 'chi shode', 'Was ist passiert?', 605, 'چی شده؟ چرا ناراحتی؟', 'Was ist passiert? Warum bist du traurig?', NULL, 4),
  ('معلومه', 'ma''lume', 'Klar / Selbstverständlich', 605, 'معلومه که کمکت می‌کنم.', 'Klar helfe ich dir.', NULL, 4),
  ('مسلمه', 'mosallame', 'Sicher / Zweifellos', 605, 'مسلمه که حق با توست.', 'Sicher hast du recht.', NULL, 4),
  ('چه عجب', 'che ajab', 'Na endlich!', 605, 'چه عجب! بالاخره آمدی.', 'Na endlich! Du bist ja doch gekommen.', NULL, 4),
  ('عجیبه', 'ajibe', 'Seltsam', 605, 'عجیبه، چراغ خودش روشن شد.', 'Seltsam, das Licht ging von selbst an.', NULL, 4),
  ('مهم نیست', 'mohem nist', 'Nicht wichtig', 605, 'مهم نیست، فراموشش کن.', 'Nicht wichtig, vergiss es.', NULL, 4),
  ('فرقی نمی‌کنه', 'farghi nemikone', 'Macht keinen Unterschied', 605, 'برای من فرقی نمی‌کنه.', 'Für mich macht das keinen Unterschied.', NULL, 4),
  ('مسئله‌ای نیست', 'mas''ale-i nist', 'Kein Problem', 605, 'اگر دیر کنی هم مسئله‌ای نیست.', 'Wenn du dich verspätest, ist das kein Problem.', NULL, 4),
  ('مشکلی نداره', 'moshkeli nadāre', 'Kein Problem', 605, 'مشکلی نداره، من صبر می‌کنم.', 'Kein Problem, ich warte.', NULL, 4),
  ('کاری نداره', 'kāri nadāre', 'Kein Problem / easy', 605, 'این کار اصلاً کاری نداره.', 'Das ist überhaupt nicht schwer.', NULL, 4),
  ('کاری نداری', 'kāri nadāri', 'Sonst noch was? (Tel.-Abschied)', 605, 'خب، من رفتم؛ کاری نداری؟', 'Also, ich gehe dann; brauchst du sonst noch was?', NULL, 4),
  ('عیبی نداره', 'eibi nadāre', 'Macht nichts', 605, 'عیبی نداره، دفعه‌ی بعد.', 'Macht nichts, dann eben nächstes Mal.', NULL, 4),
  ('شاید', 'shāyad', 'Vielleicht', 605, 'شاید فردا بیایم.', 'Vielleicht komme ich morgen.', NULL, 4),
  ('چون', 'chun', 'weil', 605, 'نیامدم چون مریض بودم.', 'Ich kam nicht, weil ich krank war.', NULL, 4),
  ('چونکه', 'chunke', 'weil / da', 605, 'خوشحالم چونکه تو اینجایی.', 'Ich bin froh, weil du hier bist.', NULL, 4),
  ('برای اینکه', 'barāye inke', 'weil / damit', 605, 'زود آمدم برای اینکه کمک کنم.', 'Ich kam früh, um zu helfen.', NULL, 4),
  ('حتیٰ', 'hattā', 'sogar', 605, 'حتی یک لحظه هم استراحت نکرد.', 'Er ruhte sich nicht einmal einen Moment aus.', NULL, 4),
  ('خودتی', 'khodeti', 'Selber! (Retourkutsche)', 605, 'ـ تو تنبلی! ـ خودتی!', '– Du bist faul! – Selber!', NULL, 4),
  ('نه بابا', 'na bābā', 'Ach was! / Nein wirklich?', 605, 'نه بابا! واقعاً این‌طور شد؟', 'Ach was! Ist das wirklich so passiert?', NULL, 4),
  ('ای بابا', 'ey bābā', 'Ach Mann / Na sowas', 605, 'ای بابا، باز هم دیر شد.', 'Ach Mann, schon wieder zu spät.', NULL, 4),
  ('ول کن بابا', 'vel kon bābā', 'Lass es / Hör auf', 605, 'ول کن بابا، ارزشش را ندارد.', 'Lass es doch, das ist es nicht wert.', NULL, 4),
  ('ولش کن', 'velesh kon', 'Lass ihn/es', 605, 'ولش کن، خودش درست می‌شود.', 'Lass es, das regelt sich von selbst.', NULL, 4),
  ('ولم کن بابا', 'velam kon bābā', 'Lass mich in Ruhe', 605, 'خسته‌ام، ولم کن بابا.', 'Ich bin müde, lass mich in Ruhe.', NULL, 4),
  ('خوش گذشت', 'khosh gozasht', 'Es war schön', 605, 'دیشب خیلی خوش گذشت.', 'Gestern Abend war es sehr schön.', NULL, 4),
  ('خوش میگذره', 'khosh migzare', 'Es macht Spaß / läuft gut', 605, 'اینجا بهمان خوش می‌گذره.', 'Hier haben wir es schön.', NULL, 4),
  ('اومدم', 'umadam', 'Ich komme (schon)', 605, 'یک لحظه، اومدم!', 'Einen Moment, ich komme schon!', NULL, 4),
  ('چی بگم', 'chi begam', 'Was soll ich sagen', 605, 'چی بگم، واقعاً متأسفم.', 'Was soll ich sagen, es tut mir wirklich leid.', NULL, 4),
  ('هنوز نه', 'hanuz na', 'Noch nicht', 605, 'ـ تمام شد؟ ـ هنوز نه.', '– Fertig? – Noch nicht.', NULL, 4),
  ('دوست دارم', 'duset dāram', 'Ich hab dich lieb / Ich liebe dich', 605, 'من تو را دوست دارم.', 'Ich liebe dich.', NULL, 4),
  ('دلم می‌خواد', 'delam mikhād', 'Ich möchte', 605, 'دلم می‌خواد یک قهوه بخورم.', 'Ich möchte einen Kaffee trinken.', 'wörtl. „Mein Herz will“', 4),
  ('می‌خوام', 'mikhām', 'Ich will', 605, 'می‌خوام فارسی یاد بگیرم.', 'Ich will Persisch lernen.', NULL, 4),
  ('نمی‌خوام', 'nemikhām', 'Ich will nicht', 605, 'نمی‌خوام دیر کنم.', 'Ich will mich nicht verspäten.', NULL, 4),
  ('دیگه نمی‌خوام', 'dige nemikhām', 'Ich will nicht mehr', 605, 'ممنون، دیگه نمی‌خوام.', 'Danke, ich will nichts mehr.', NULL, 4),
  ('می‌دونی', 'miduni', 'Weißt du', 605, 'می‌دونی خانه‌اش کجاست؟', 'Weißt du, wo sein Haus ist?', NULL, 4),
  ('می‌دونم', 'midunam', 'Ich weiß', 605, 'می‌دونم، خودم دیدم.', 'Ich weiß, ich hab es selbst gesehen.', NULL, 4),
  ('نمی‌دونم', 'nemidunam', 'Ich weiß nicht', 605, 'نمی‌دونم چی بگم.', 'Ich weiß nicht, was ich sagen soll.', NULL, 4),
  ('دلم گرفته', 'delam gerefte', 'Ich bin bedrückt', 606, 'امروز دلم گرفته.', 'Heute bin ich bedrückt.', 'wörtl. „Mein Herz ist beklommen“', 4),
  ('حالم گرفته', 'hālam gerefte', 'Ich bin schlecht drauf', 606, 'از این خبر حالم گرفته.', 'Diese Nachricht hat mich schlecht drauf gemacht.', NULL, 4),
  ('حالتو می‌گیرم', 'hāleto migiram', 'Ich mach dich fertig', 606, 'شوخی‌شوخی گفت «حالتو می‌گیرم»، بعد خندیدیم.', 'Scherzhaft sagte er „dir zeig ich''s", dann lachten wir.', NULL, 4),
  ('خستمه', 'khastame', 'Ich bin müde', 606, 'خیلی کار کردم، خستمه.', 'Ich habe viel gearbeitet, ich bin müde.', NULL, 4),
  ('حوصله ندارم', 'hosele nadāram', 'Ich hab keine Lust', 606, 'امروز اصلاً حوصله ندارم.', 'Heute habe ich überhaupt keine Lust.', NULL, 4),
  ('عمراً', 'omran', 'Niemals / Auf keinen Fall', 606, 'عمراً دیگر آنجا بروم.', 'Niemals gehe ich da nochmal hin.', NULL, 4),
  ('گشنمه', 'goshname', 'Ich hab Hunger', 606, 'از صبح چیزی نخوردم، گشنمه.', 'Ich habe seit dem Morgen nichts gegessen, ich habe Hunger.', NULL, 4),
  ('گرسنمه', 'gorosname', 'Ich bin hungrig', 606, 'بریم ناهار، گرسنمه.', 'Lass uns Mittag essen, ich bin hungrig.', NULL, 4),
  ('سردمه', 'sardame', 'Mir ist kalt', 606, 'پنجره را ببند، سردمه.', 'Mach das Fenster zu, mir ist kalt.', NULL, 4),
  ('گرممه', 'garmame', 'Mir ist warm', 606, 'کولر را روشن کن، گرممه.', 'Mach die Klimaanlage an, mir ist warm.', NULL, 4),
  ('سرم شلوغه', 'saram sholughe', 'Ich hab viel zu tun', 606, 'این هفته خیلی سرم شلوغه.', 'Diese Woche habe ich sehr viel zu tun.', 'wörtl. „Mein Kopf ist voll“', 4),
  ('خوشمزس', 'khoshmazas', 'Es ist lecker', 606, 'این غذا خیلی خوشمزس.', 'Dieses Essen ist sehr lecker.', NULL, 4),
  ('شکمو', 'shekamu', 'Verfressen / Vielfraß', 606, 'برادرم خیلی شکمو است.', 'Mein Bruder ist ein richtiger Vielfraß.', NULL, 4),
  ('هیچی', 'hichi', 'Nichts', 606, 'ـ چی شده؟ ـ هیچی، مهم نیست.', '– Was ist los? – Nichts, nicht wichtig.', NULL, 4),
  ('بی عرضه', 'bi orze', 'Versager / unfähig', 607, 'به کسی نگو بی‌عرضه؛ این توهین است.', 'Nenn niemanden „unfähig"; das ist eine Beleidigung.', NULL, 3),
  ('به تو چه', 'be to che', 'Was geht''s dich an?', 607, 'مؤدبانه نیست که بگویی «به تو چه».', 'Es ist unhöflich zu sagen „Was geht''s dich an".', NULL, 3),
  ('به تو مربوط نیست', 'be to marbut nist', 'Das geht dich nichts an', 607, 'به‌جای «به تو مربوط نیست» می‌توان مؤدب‌تر پاسخ داد.', 'Statt „das geht dich nichts an" kann man höflicher antworten.', NULL, 3),
  ('چه غلطا', 'che ghalatā', 'Was erlaubst du dir!', 607, '«چه غلطا» عبارتی تند و گله‌مندانه است.', '„Was erlaubst du dir" ist ein scharfer, vorwurfsvoller Ausdruck.', NULL, 3),
  ('مرتیکه الاغ', 'martike olāgh', 'Du Esel', 607, '«مرتیکه الاغ» ناسزایی رایج است و بهتر است گفته نشود.', '„Du Esel" ist ein gängiges Schimpfwort und sollte vermieden werden.', NULL, 3),
  ('مرتیکه خر', 'martike khar', 'Du Esel', 607, 'این عبارت توهین‌آمیز است؛ از آن استفاده نکن.', 'Dieser Ausdruck ist beleidigend; benutze ihn nicht.', NULL, 3),
  ('مرتیکه نفهم', 'martike nafahm', 'Du Begriffsstutziger', 607, 'گفتن «نفهم» به دیگران بی‌ادبی است.', 'Andere „begriffsstutzig" zu nennen ist unhöflich.', NULL, 3),
  ('پفیوز', 'pofyuz', 'Nichtsnutz / willenlos', 607, '«پفیوز» دشنامی زننده است.', '„Nichtsnutz" ist ein anstößiges Schimpfwort.', 'vulgär', 3),
  ('دیوث', 'deyus', 'schwere Beleidigung (Zuhälter/Hahnrei)', 607, 'این کلمه دشنامی بسیار رکیک است و کاربردش پسندیده نیست.', 'Dieses Wort ist eine sehr vulgäre Beschimpfung und sollte nicht verwendet werden.', 'sehr vulgär', 3),
  ('کون گشاد', 'kun goshād', 'Faulpelz', 607, '«کون گشاد» اصطلاحی عامیانه و بی‌ادبانه برای آدم تنبل است.', 'Dieser derbe Ausdruck steht umgangssprachlich für einen faulen Menschen.', 'vulgär', 3),
  ('آشغال', 'āshghāl', 'Müll / Abschaum', 607, 'گفتن «آشغال» به یک نفر سخت توهین‌آمیز است.', 'Jemanden „Abschaum" zu nennen ist schwer beleidigend.', NULL, 3),
  ('زهر مار', 'zahr-e mār', 'Halt den Mund!', 607, '«زهر مار» واکنشی خشن و بی‌ادبانه است.', '„Halt den Mund" (wörtl. „Schlangengift") ist eine grobe, unhöfliche Reaktion.', 'wörtl. „Schlangengift“', 3),
  ('خاک بر سرت', 'khāk bar saret', 'Schande über dich', 607, '«خاک بر سرت» نفرینی رایج اما بسیار توهین‌آمیز است.', '„Schande über dich" ist ein gängiger, aber sehr beleidigender Fluch.', 'wörtl. „Erde auf deinen Kopf“', 3),
  ('چه خاکی به سرم بریزم', 'che khāki be saram berizam', 'Was soll ich nur tun! (verzweifelt)', 607, 'وقتی کسی درمانده است می‌گوید «چه خاکی به سرم بریزم».', 'Wenn jemand verzweifelt ist, sagt er „Was soll ich nur tun".', NULL, 3),
  ('بی وجدان', 'bi vejdān', 'Gewissenlos', 607, '«بی‌وجدان» خواندن دیگران توهین است.', 'Andere „gewissenlos" zu nennen ist eine Beleidigung.', NULL, 3),
  ('برو پی کارت', 'boro pey-e kāret', 'Kümmer dich um deine Sachen', 607, '«برو پی کارت» یعنی دست از سر کسی بردار، ولی لحنش تند است.', '„Kümmer dich um deine Sachen" heißt, jemanden in Ruhe zu lassen, klingt aber schroff.', NULL, 3),
  ('کثافت', 'kesāfat', 'Dreckskerl', 607, '«کثافت» دشنامی شدید است.', '„Dreckskerl" ist ein heftiges Schimpfwort.', NULL, 3),
  ('احمق', 'ahmagh', 'Dummkopf', 607, 'به‌جای «احمق» بهتر است محترمانه صحبت کنیم.', 'Statt „Dummkopf" sprechen wir besser respektvoll.', NULL, 3),
  ('خر', 'khar', 'Esel', 607, '«خر» در مقام دشنام یعنی نادان، و توهین‌آمیز است.', '„Esel" als Schimpfwort bedeutet „dumm" und ist beleidigend.', NULL, 3),
  ('خفه شو', 'khafe sho', 'Halt den Mund', 607, '«خفه شو» بسیار بی‌ادبانه است؛ بهتر است گفته نشود.', '„Halt den Mund" ist sehr unhöflich; besser nicht sagen.', NULL, 3),
  ('دهنت رو ببند', 'dahanet ro beband', 'Halt den Mund', 607, 'این عبارت پرخاشگرانه است و بهتر است از آن پرهیز شود.', 'Dieser Ausdruck ist aggressiv und sollte vermieden werden.', 'wörtl. „Schließ deinen Mund“', 3),
  ('گمشو', 'gomsho', 'Hau ab / Verschwinde', 607, '«گمشو» دستوری خشن و توهین‌آمیز است.', '„Hau ab" ist ein grober, beleidigender Befehl.', NULL, 3),
  ('غلط کردی', 'ghalat kardi', 'Du hast Mist gebaut', 607, '«غلط کردی» لحنی بسیار تند و تحقیرآمیز دارد.', '„Du hast Mist gebaut" hat einen sehr scharfen, herabsetzenden Ton.', NULL, 3),
  ('گه خوردی', 'goh khordi', 'du hast was Falsches gesagt', 607, 'این عبارت بسیار رکیک است و نباید به کار رود.', 'Dieser Ausdruck ist sehr vulgär und sollte nicht verwendet werden.', 'sehr vulgär, wörtl. „du hast Sch… gegessen“', 3),
  ('تو گه می‌خوری', 'to goh mikhori', 'du laberst Mist', 607, 'این جمله یک دشنام بسیار زشت است.', 'Dieser Satz ist eine sehr vulgäre Beschimpfung.', 'sehr vulgär', 3),
  ('پدر سگ', 'pedar-sag', 'Schimpfwort', 607, '«پدر سگ» گاهی شوخی و گاهی دشنام است؛ با احتیاط.', '„Pedar-sag" ist mal scherzhaft, mal Schimpfwort; mit Vorsicht zu verwenden.', 'wörtl. „Hundevater“', 3),
  ('پدر سوخته', 'pedar-sukhte', 'Schlingel / Schlitzohr', 607, '«پدر سوخته» اغلب شوخی و محبت‌آمیز برای بچه‌ی شیطان است.', '„Pedar-sukhte" ist oft scherzhaft-liebevoll für ein freches Kind.', 'wörtl. „verbrannter Vater“', 3)
) as v(hangul, romanisierung, deutsch, lektion_nummer, beispielsatz_ko, beispielsatz_de, hinweis, haeufigkeit);
